'use client';
/**
 * React wrapper for <hx-toast-stack> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixToastStack } from '@helixui/library/components/hx-toast';

import type { HxToastStackProps } from './types.js';

export type { HxToastStackProps };

/**
 * A fixed-position container that stacks `hx-toast` elements at the specified
corner of the viewport. Enforces a maximum visible toast count via `stack-limit`.
 *
 * @example
 * ```tsx
 * import { HxToastStack } from '@helixui/react';
 *
 * <HxToastStack />
 * ```
 */
export const HxToastStack = createComponent({
  tagName: 'hx-toast-stack',
  elementClass: HelixToastStack,
  react: React,
  events: {},
  displayName: 'HxToastStack',
});

export default HxToastStack;
