/**
 * TypeScript types for HxToastStack React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxToastStackProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Corner of the viewport where toasts appear. */
  placement?: string | 'top-start' | 'top-center' | 'top-end' | 'bottom-start' | 'bottom-center' | 'bottom-end';
  /** Maximum number of simultaneously visible toasts. 0 = unlimited. */
  stackLimit?: number;
}
