'use client';
/**
 * React wrapper for <hx-menu-item> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixMenuItem } from '@helixui/library/components/hx-menu';

import type { HxMenuItemProps } from './types.js';

export type { HxMenuItemProps };

/**
 * A single interactive item for use inside `hx-menu`. Supports normal, checkbox,
and radio types, loading state, prefix/suffix slots, and submenu nesting.
Use `aria-label` on the parent `hx-menu` to provide an accessible name.
 *
 * @example
 * ```tsx
 * import { HxMenuItem } from '@helixui/react';
 *
 * <HxMenuItem />
 * ```
 */
export const HxMenuItem = createComponent({
  tagName: 'hx-menu-item',
  elementClass: HelixMenuItem,
  react: React,
  events: {
    onHxItemSelect: 'hx-item-select',
    onHxItemSubmenuOpen: 'hx-item-submenu-open',
  },
  displayName: 'HxMenuItem',
});

export default HxMenuItem;
