/**
 * TypeScript types for HxMenuItem React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxMenuItemProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The value associated with this item, emitted in the hx-select event. */
  value?: string;
  /** Whether the item is disabled. Prevents interaction and event dispatch. */
  disabled?: boolean;
  /** Whether the item is checked. Only meaningful when type="checkbox". */
  checked?: boolean;
  /** The type of menu item. "checkbox" renders a checkmark and toggles checked state.
"radio" renders a checkmark and emits selection for radio-group behavior. */
  type?: 'normal' | 'checkbox' | 'radio';
  /** Whether the item is in a loading state. Shows a spinner and prevents interaction. */
  loading?: boolean;

  // Event callbacks
  /** Dispatched when the item is activated via click, Enter, or Space. */
  onHxItemSelect?: (event: Event) => void;
  /** Dispatched when ArrowRight is pressed on an item with a submenu. */
  onHxItemSubmenuOpen?: (event: Event) => void;
}
