'use client';
/**
 * React wrapper for <hx-button-group> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixButtonGroup } from '@helixui/library/components/hx-button-group';

import type { HxButtonGroupProps } from './types.js';

export type { HxButtonGroupProps };

/**
 * A container component that groups related hx-button elements into a cohesive
horizontal or vertical action set. Eliminates double borders between adjacent
buttons and squares off inner border-radius for a unified visual appearance.

**Accessibility:** Always provide an accessible label via `aria-label` or
`aria-labelledby` so screen readers can announce the group purpose.
 *
 * @example
 * ```tsx
 * import { HxButtonGroup } from '@helixui/react';
 *
 * <HxButtonGroup />
 * ```
 */
export const HxButtonGroup = createComponent({
  tagName: 'hx-button-group',
  elementClass: HelixButtonGroup,
  react: React,
  events: {},
  displayName: 'HxButtonGroup',
});

export default HxButtonGroup;
