/**
 * TypeScript types for HxButtonGroup React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxButtonGroupProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Layout orientation of the button group. */
  orientation?: 'horizontal' | 'vertical';
  /** Size applied to the button group and cascaded to child buttons via
the --hx-button-group-size CSS custom property. */
  size?: 'sm' | 'md' | 'lg';
  /** Accessible label for the button group. Sets aria-label via ElementInternals.
**Strongly recommended** for WCAG 2.1 AA compliance — without it, screen
readers announce an unnamed "group". For Drupal/Twig compatibility, prefer
applying `aria-label` directly as an HTML attribute instead. */
  label?: string;
  internals?: unknown;
  role?: string;
}
