'use client';
/**
 * React wrapper for <hx-clinical-status> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixClinicalStatus } from '@helixui/library/components/hx-clinical-status';

import type { HxClinicalStatusProps } from './types.js';

export type { HxClinicalStatusProps };

/**
 * A clinical status indicator designed for healthcare alert fatigue prevention.
Standardizes clinical alert presentations to reduce cognitive overload from
inconsistent color/icon combinations across healthcare interfaces.
 *
 * @example
 * ```tsx
 * import { HxClinicalStatus } from '@helixui/react';
 *
 * <HxClinicalStatus />
 * ```
 */
export const HxClinicalStatus = createComponent({
  tagName: 'hx-clinical-status',
  elementClass: HelixClinicalStatus,
  react: React,
  events: {
    onHxDismiss: 'hx-dismiss',
    onHxAcknowledge: 'hx-acknowledge',
  },
  displayName: 'HxClinicalStatus',
});

export default HxClinicalStatus;
