/**
 * TypeScript types for HxClinicalStatus React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxClinicalStatusProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Clinical severity level that determines visual styling and ARIA semantics.
- `info`: Informational, non-urgent (role="status")
- `warning`: Requires attention but not immediate (role="status")
- `critical`: Requires prompt clinical attention (role="alert")
- `emergent`: Life-threatening, immediate action required (role="alert") */
  severity?: string;
  /** Status message text. Displayed as the primary content of the indicator. */
  message?: string;
  /** Whether the status can be dismissed by the user.
Critical and emergent statuses should require acknowledgment rather than simple dismissal. */
  dismissible?: boolean;
  /** Whether the status survives page navigation.
Defaults to false for info/warning, true for critical/emergent.
When set explicitly, overrides the severity-based default. */
  persistent?: boolean;
  /** Optional custom icon name. When not set, a default severity-appropriate icon is shown. */
  icon?: string;
  /** Compact mode for dense clinical UIs (e.g. patient dashboards, bedside displays).
Reduces padding, font size, and icon size. */
  compact?: boolean;

  // Event callbacks
  /** Dispatched when the user dismisses the status. */
  onHxDismiss?: (event: Event) => void;
  /** Dispatched when the user acknowledges a critical/emergent status. */
  onHxAcknowledge?: (event: Event) => void;
}
