'use client';
/**
 * React wrapper for <hx-banner> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixBanner } from '@helixui/library/components/hx-banner';

import type { HxBannerProps } from './types.js';

export type { HxBannerProps };

/**
 * A full-width page-level banner for persistent notifications and announcements.
Designed for healthcare applications requiring prominent system-level messaging.
 *
 * @example
 * ```tsx
 * import { HxBanner } from '@helixui/react';
 *
 * <HxBanner />
 * ```
 */
export const HxBanner = createComponent({
  tagName: 'hx-banner',
  elementClass: HelixBanner,
  react: React,
  events: {
    onHxDismiss: 'hx-dismiss',
  },
  displayName: 'HxBanner',
});

export default HxBanner;
