/**
 * TypeScript types for HxBanner React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxBannerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual variant of the banner that determines colors and ARIA semantics. */
  variant?: string;
  /** CSS positioning behavior. "sticky" keeps the banner in flow; "fixed" pins it to the viewport. */
  position?: string;
  /** Whether the banner can be dismissed by the user. */
  dismissible?: boolean;
  /** Heading text for the banner, used to provide context in the action link's and
close button's accessible labels. */
  heading?: string;
  /** Label text for the optional action link. Requires action-href to render. */
  actionLabel?: string;
  /** URL for the optional action link. Requires action-label to render. */
  actionHref?: string;
  /** Whether the banner is visible. Defaults to true — banners are shown by default. */
  open?: boolean;

  // Event callbacks
  /** Dispatched when the user dismisses the banner. */
  onHxDismiss?: (event: Event) => void;
}
