'use client';
/**
 * React wrapper for <hx-copy-button> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixCopyButton } from '@helixui/library/components/hx-copy-button';

import type { HxCopyButtonProps } from './types.js';

export type { HxCopyButtonProps };

/**
 * A clipboard copy button component that writes a given value to the system
clipboard. Provides idle and success states with configurable feedback
duration, slot-based icon overrides, and an accessible live region that
announces copy completion to screen reader users.

The `aria-label` reflects the current copy state: idle shows `label`,
copied state appends " — Copied" so screen reader users who re-focus the
button after copy receive an accurate accessible name.

Note: `aria-pressed` is intentionally NOT used. This is not a toggle button;
copied is a transient feedback state, not a persistent on/off toggle.
 *
 * @example
 * ```tsx
 * import { HxCopyButton } from '@helixui/react';
 *
 * <HxCopyButton />
 * ```
 */
export const HxCopyButton = createComponent({
  tagName: 'hx-copy-button',
  elementClass: HelixCopyButton,
  react: React,
  events: {
    onHxCopyError: 'hx-copy-error',
    onHxCopy: 'hx-copy',
  },
  displayName: 'HxCopyButton',
});

export default HxCopyButton;
