/**
 * TypeScript types for HxCopyButton React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxCopyButtonProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The text value to write to the clipboard on click. Required for the
component to perform a copy operation. */
  value?: string;
  /** Accessible label applied as `aria-label` and `title` on the button. */
  label?: string;
  /** Duration in milliseconds to display the success (copied) state before
reverting to the idle state. Values below 300 ms are clamped to 300 ms
to ensure the success announcement remains visible long enough for
assistive technology and human perception. */
  feedbackDuration?: number;
  /** Visual size of the button. Maps to fixed height and padding tokens.
Accepts: 'sm' | 'md' | 'lg'. Invalid values are silently coerced to 'md'.

**Accessibility (WCAG 2.5.8):** The `sm` variant uses `--hx-size-8` for
its minimum width and height. Ensure this token resolves to at least 24×24 px
(WCAG 2.5.8 AA minimum target size). For touch-primary interfaces such as
mobile clinical apps, prefer `md` or `lg` to meet the 44×44 px recommended
target size (WCAG 2.5.5 AAA / Apple HIG / Android guidelines). */
  size?: 'sm' | 'md' | 'lg';
  /** Whether the button is disabled. When true, click events are suppressed
and clipboard writes do not occur. */
  disabled?: boolean;
  /** Text announced to screen readers and appended to aria-label after a
successful copy. Also used as the content of the aria-live announcement. */
  labelCopied?: string;
  /** Accessible label announced when copy fails. Override for i18n. */
  labelError?: string;

  // Event callbacks
  /** Dispatched when the clipboard write fails (permission denied, iframe restriction, etc.). The `error` detail contains the caught error for diagnostic use. */
  onHxCopyError?: (event: Event) => void;
  /** Dispatched after the value has been successfully written to the clipboard. */
  onHxCopy?: (event: Event) => void;
}
