'use client';
/**
 * React wrapper for <hx-visually-hidden> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixVisuallyHidden } from '@helixui/library/components/hx-visually-hidden';

import type { HxVisuallyHiddenProps } from './types.js';

export type { HxVisuallyHiddenProps };

/**
 * A utility component that hides content visually while keeping it
accessible to screen readers. Uses the standard visually-hidden CSS
technique — does NOT use `visibility: hidden` or `display: none`,
which would also hide content from assistive technologies.
 *
 * @example
 * ```tsx
 * import { HxVisuallyHidden } from '@helixui/react';
 *
 * <HxVisuallyHidden />
 * ```
 */
export const HxVisuallyHidden = createComponent({
  tagName: 'hx-visually-hidden',
  elementClass: HelixVisuallyHidden,
  react: React,
  events: {},
  displayName: 'HxVisuallyHidden',
});

export default HxVisuallyHidden;
