/**
 * TypeScript types for HxVisuallyHidden React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxVisuallyHiddenProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** When true, the component becomes visible when a focusable child
(such as a skip link) receives focus. This enables the standard
"skip to content" accessibility pattern. */
  focusable?: boolean;
}
