'use client';
/**
 * React wrapper for <hx-meter> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixMeter } from '@helixui/library/components/hx-meter';

import type { HxMeterProps } from './types.js';

export type { HxMeterProps };

/**
 * A scalar measurement within a known range — e.g., disk usage, health score,
or any numeric value with defined min/max bounds. Supports low/high/optimum
threshold markers for semantic color feedback.
 *
 * @example
 * ```tsx
 * import { HxMeter } from '@helixui/react';
 *
 * <HxMeter />
 * ```
 */
export const HxMeter = createComponent({
  tagName: 'hx-meter',
  elementClass: HelixMeter,
  react: React,
  events: {},
  displayName: 'HxMeter',
});

export default HxMeter;
