/**
 * TypeScript types for HxMeter React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxMeterProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Current value of the meter. */
  value?: number;
  /** Minimum value of the range. */
  min?: number;
  /** Maximum value of the range. */
  max?: number;
  /** Threshold below which the value is considered suboptimal (lower range warning). */
  low?: number | undefined;
  /** Threshold above which the value is considered suboptimal (upper range warning). */
  high?: number | undefined;
  /** The optimal value within the range. Used to determine which zone is "good". */
  optimum?: number | undefined;
  /** Accessible label for the meter. Used as the visible label text and as
the source for `aria-labelledby`. When only slot content is provided
(no `label` attribute), the slot content is used for the accessible name. */
  label?: string | undefined;
}
