'use client';
/**
 * React wrapper for <hx-code-snippet> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixCodeSnippet } from '@helixui/library/components/hx-code-snippet';

import type { HxCodeSnippetProps } from './types.js';

export type { HxCodeSnippetProps };

/**
 * A styled code block with optional copy button and max-lines truncation.
Supports block (`<pre><code>`) and inline (`<code>`) rendering modes.
No external syntax highlighting dependency — use the `language` attribute
as a hint for consumers integrating their own highlighter via slotted content.
 *
 * @example
 * ```tsx
 * import { HxCodeSnippet } from '@helixui/react';
 *
 * <HxCodeSnippet />
 * ```
 */
export const HxCodeSnippet = createComponent({
  tagName: 'hx-code-snippet',
  elementClass: HelixCodeSnippet,
  react: React,
  events: {
    onHxCopy: 'hx-copy',
  },
  displayName: 'HxCodeSnippet',
});

export default HxCodeSnippet;
