/**
 * TypeScript types for HxCodeSnippet React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxCodeSnippetProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Language hint for consumers to apply syntax highlighting.
Does not affect rendering directly; it is applied as a `language-*` class
on the `<code>` element so external highlighters can target it. */
  language?: string;
  /** When true, renders as an inline `<code>` element instead of a `<pre><code>` block. */
  inline?: boolean;
  /** When true, enables word-wrap in block mode. */
  wrap?: boolean;
  /** When true, shows a copy-to-clipboard button. Add the `copyable` attribute to enable it. */
  copyable?: boolean;
  /** Maximum number of lines to display before showing a "Show more" button.
Set to 0 (default) to disable truncation. */
  maxLines?: number;
  /** When true, prepends line numbers to each displayed line in block mode.
Line numbers are rendered as `aria-hidden` spans so screen readers skip them. */
  lineNumbers?: boolean;
  /** Label for the copy button in idle state. */
  labelCopy?: string;
  /** Label for the copy button after successful copy. */
  labelCopied?: string;
  /** Label for the expand button when content is collapsed. */
  labelShowMore?: string;
  /** Label for the expand button when content is expanded. */
  labelShowLess?: string;

  // Event callbacks
  /** Dispatched when the copy button is clicked. */
  onHxCopy?: (event: Event) => void;
}
