'use client';
/**
 * React wrapper for <hx-nav> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixNav } from '@helixui/library/components/hx-nav';

import type { HxNavProps } from './types.js';

export type { HxNavProps };

/**
 * Primary and secondary navigation component.
Supports horizontal menu bar and vertical sidebar patterns.
Mobile responsive with hamburger toggle.
 *
 * @example
 * ```tsx
 * import { HxNav } from '@helixui/react';
 *
 * <HxNav />
 * ```
 */
export const HxNav = createComponent({
  tagName: 'hx-nav',
  elementClass: HelixNav,
  react: React,
  events: {
    onHxNavSelect: 'hx-nav-select',
  },
  displayName: 'HxNav',
});

export default HxNav;
