/**
 * TypeScript types for HxNav React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxNavProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Navigation items array. */
  items?: string;
  /** Layout orientation: 'horizontal' (menu bar) or 'vertical' (sidebar). */
  orientation?: string;
  /** Accessible label for the nav landmark. */
  label?: string;
  /** Accessible label for the navigation toggle button when menu is closed. */
  labelOpenMenu?: string;
  /** Accessible label for the navigation toggle button when menu is open. */
  labelCloseMenu?: string;

  // Event callbacks
  /** Dispatched when a nav item is activated. */
  onHxNavSelect?: (event: Event) => void;
}
