'use client';
/**
 * React wrapper for <hx-icon> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixIcon } from '@helixui/library/components/hx-icon';

import type { HxIconProps } from './types.js';

export type { HxIconProps };

/**
 * An icon component that supports inline SVG fetching and SVG sprite sheet references.
Decorative icons are automatically hidden from assistive technology.
When a label is provided the icon is announced as an image with that label.

**Render modes:**
- **Sprite mode** (recommended for Drupal/SSR): Set `name` and optionally `sprite-url`.
  Renders an `<svg><use href="...#name">` — works server-side without JavaScript.
- **Inline mode**: Set `src` to a URL of a standalone SVG file. The component fetches,
  sanitizes, and embeds the SVG markup. Requires JavaScript; not server-side renderable.
  For Drupal/Twig templates use sprite mode to avoid content shift before hydration.
 *
 * @example
 * ```tsx
 * import { HxIcon } from '@helixui/react';
 *
 * <HxIcon />
 * ```
 */
export const HxIcon = createComponent({
  tagName: 'hx-icon',
  elementClass: HelixIcon,
  react: React,
  events: {},
  displayName: 'HxIcon',
});

export default HxIcon;
