/**
 * TypeScript types for HxIcon React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxIconProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Icon name used as the fragment identifier when referencing a sprite sheet.
For sprite mode provide the bare symbol id (e.g. `check`). The component
will build the full href as `${spriteUrl}#${name}`. If `name` already
starts with `#` it is used as-is (inline sprite reference without a base
URL). */
  name?: string;
  /** URL of a standalone SVG file to fetch and render inline. Takes precedence
over sprite mode when both `src` and `spriteUrl`/`name` are set.

**Note:** Inline mode requires browser JavaScript (`fetch` + `DOMParser`).
It is not server-side renderable. For Drupal/Twig use sprite mode instead. */
  src?: string | undefined;
  /** Base URL of the SVG sprite sheet. Used together with `name` to construct
the `<use>` href: `${spriteUrl}#${name}`. */
  spriteUrl?: string | undefined;
  /** Size variant of the icon.

Set via the `hx-size` HTML attribute (e.g. `hx-size="lg"`) or via the
`size` JavaScript property (e.g. `el.size = 'lg'`). Both are equivalent —
the `attribute: 'hx-size'` mapping is used to avoid colliding with the
native `<input>` `size` attribute in Drupal attribute-passthrough scenarios.
The CEM exposes both the JS property name (`size`) and the HTML attribute
name (`hx-size`). */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /** Accessible label for the icon. When non-empty, `role="img"` and
`aria-label` are applied so assistive technology announces the icon.
When empty the icon is treated as decorative and `aria-hidden="true"` is
applied. */
  label?: string;
}
