/**
 * TypeScript types for HxIcon React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxIconProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Icon name used as the fragment identifier when referencing a sprite sheet.
For sprite mode provide the bare symbol id (e.g. `check`). The component
will build the full href as `${spriteUrl}#${name}`. If `name` already
starts with `#` it is used as-is (inline sprite reference without a base
URL). */
  name?: string;
  /** Identifier of the icon library to resolve `name` through. Default is
the empty string — meaning bare `<hx-icon name="foo">` continues to
render a document-local sprite fragment (`<use href="#foo">`) per the
pre-3.9.0 contract. Set explicitly to `'fa-free'` for the FA Free Solid
set bundled with `@helixui/icons`, `'helix'` for the curated 32-glyph
helix set, or to any consumer-registered library identifier.

Library resolution applies only when `src` is empty AND `sprite-url` is
not set; the inline-fetch and explicit-sprite paths are kept as escape
hatches and ignore the library attribute. */
  library?: string;
  /** URL of a standalone SVG file to fetch and render inline. Takes precedence
over sprite mode when both `src` and `spriteUrl`/`name` are set.

**Note:** Inline mode requires browser JavaScript (`fetch` + `DOMParser`).
It is not server-side renderable. For Drupal/Twig use sprite mode instead. */
  src?: string | undefined;
  /** Base URL of the SVG sprite sheet. Used together with `name` to construct
the `<use>` href: `${spriteUrl}#${name}`. */
  spriteUrl?: string | undefined;
  /** Size variant of the icon.

Set via the `hx-size` HTML attribute (e.g. `hx-size="lg"`) or via the
`size` JavaScript property (e.g. `el.size = 'lg'`). Both are equivalent —
the `attribute: 'hx-size'` mapping is used to avoid colliding with the
native HTMLInputElement `size` attribute in Drupal attribute-passthrough
scenarios.
The CEM exposes both the JS property name (`size`) and the HTML attribute
name (`hx-size`). */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /** Accessible label for the icon. When non-empty, `role="img"` and
`aria-label` are applied so assistive technology announces the icon.
When empty the icon is treated as decorative and `aria-hidden="true"` is
applied. */
  label?: string;
  /** Comma-separated list of allowed origins for cross-origin SVG fetches.
By default, only same-origin URLs are permitted. Set this to allow
specific CDN or asset server origins (e.g., "https://cdn.example.com,https://assets.example.com"). */
  allowedOrigins?: string;
  /** Paint-mode override for the rendered glyph geometry. `'fill'` (default)
paints with `fill: currentColor`; `'stroke'` paints outline glyphs with
`fill: none; stroke: currentColor` and the `--hx-icon-stroke-width` token.

When `library` resolves through the registry, the library's own paint mode
is applied automatically — set this ONLY for the explicit `sprite-url` /
`name="#…"` escape hatches when pinning a STROKE sprite sheet (e.g. the
bundled `feather.svg` / `lucide.svg`), where no registry library is
consulted. An explicit value overrides the library-derived mode. */
  paintMode?: string | undefined;
}
