/**
 * CEM-to-React codegen script.
 *
 * Reads the Custom Elements Manifest from packages/hx-library/custom-elements.json
 * and generates typed React wrappers using @lit/react createComponent for each
 * custom element declaration found in the manifest.
 *
 * Usage:
 *   tsx scripts/generate-wrappers.ts
 *
 * Output:
 *   - src/components/{PascalCase}.tsx  (one per element)
 *   - src/index.ts                     (barrel export)
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ---------------------------------------------------------------------------
// CEM type shapes (subset of the full CEM schema)
// ---------------------------------------------------------------------------

interface CemEvent {
  name: string;
  description?: string;
  type?: { text: string };
}

interface CemDeclaration {
  kind: string;
  name: string;
  tagName?: string;
  events?: CemEvent[];
}

interface CemModule {
  kind: string;
  path: string;
  declarations?: CemDeclaration[];
}

interface CustomElementsManifest {
  schemaVersion: string;
  modules: CemModule[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a kebab-case string to PascalCase.
 * Example: "hx-button-group" becomes "HxButtonGroup".
 */
function toPascalCase(kebab: string): string {
  return kebab
    .split('-')
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

/**
 * Convert a kebab-case event name to an "on"-prefixed React prop name.
 * Example: "hx-after-dismiss" becomes "onHxAfterDismiss".
 *          "wc-submit" becomes "onWcSubmit".
 */
function toReactEventProp(eventName: string): string {
  const pascal = toPascalCase(eventName);
  return 'on' + pascal;
}

/**
 * Derive the @helix/library import path for a given tag name.
 *
 * hx-breadcrumb-item is co-located inside the hx-breadcrumb directory.
 * Its hx-breadcrumb index.ts re-exports both HelixBreadcrumb and
 * HelixBreadcrumbItem, so we point the import at the parent directory.
 *
 * For hx-radio-group the index.ts exports both HelixRadioGroup and HelixRadio.
 *
 * All other elements map directly to their own component directory.
 */
function toLibraryImportPath(tagName: string): string {
  if (tagName === 'hx-breadcrumb-item') {
    return '@helix/library/components/hx-breadcrumb';
  }
  if (tagName === 'hx-radio') {
    return '@helix/library/components/hx-radio-group';
  }
  return '@helix/library/components/' + tagName;
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function buildEventsObject(events: CemEvent[]): string {
  if (events.length === 0) {
    return '{}';
  }
  const lines = events.map(
    (e) => '    ' + toReactEventProp(e.name) + ": '" + e.name + "',",
  );
  return '{\n' + lines.join('\n') + '\n  }';
}

function generateWrapper(declaration: CemDeclaration): string {
  const { name: className, tagName, events = [] } = declaration;

  if (!tagName) {
    throw new Error('Declaration "' + className + '" has no tagName — cannot generate wrapper.');
  }

  const componentName = toPascalCase(tagName);
  const importPath = toLibraryImportPath(tagName);
  const eventsObject = buildEventsObject(events);

  const lines: string[] = [
    "'use client';",
    '',
    "import React from 'react';",
    "import { createComponent } from '@lit/react';",
    'import { ' + className + " } from '" + importPath + "';",
    '',
    'export const ' + componentName + ' = createComponent({',
    '  react: React,',
    "  tagName: '" + tagName + "',",
    '  elementClass: ' + className + ',',
    '  events: ' + eventsObject + ',',
    '});',
    '',
  ];

  return lines.join('\n');
}

function generateBarrel(componentNames: string[]): string {
  const sorted = [...componentNames].sort();
  const header = [
    '// Generated by scripts/generate-wrappers.ts',
    "// Do not edit this file directly — run `npm run generate` to regenerate.",
  ];
  const exports = sorted.map(
    (name) => "export { " + name + " } from './components/" + name + ".js';",
  );
  return [...header, ...exports, ''].join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const cemPath = resolve(__dirname, '../../hx-library/custom-elements.json');
  const componentsOutDir = resolve(__dirname, '../src/components');
  const indexOutPath = resolve(__dirname, '../src/index.ts');

  const cemRaw = readFileSync(cemPath, 'utf-8');
  const cem = JSON.parse(cemRaw) as CustomElementsManifest;

  mkdirSync(componentsOutDir, { recursive: true });

  const generatedComponentNames: string[] = [];

  for (const mod of cem.modules) {
    if (!mod.declarations) continue;

    for (const declaration of mod.declarations) {
      // Only process custom element class declarations that have a tagName
      if (declaration.kind !== 'class' || !declaration.tagName) continue;

      const componentName = toPascalCase(declaration.tagName);
      const outPath = resolve(componentsOutDir, componentName + '.tsx');

      const content = generateWrapper(declaration);
      writeFileSync(outPath, content, 'utf-8');

      console.log('  Generated: src/components/' + componentName + '.tsx');
      generatedComponentNames.push(componentName);
    }
  }

  // Deduplicate in case the same component appears in multiple CEM modules
  const unique = [...new Set(generatedComponentNames)];

  const barrel = generateBarrel(unique);
  writeFileSync(indexOutPath, barrel, 'utf-8');

  console.log('\n  Generated: src/index.ts (' + String(unique.length) + ' components)');
  console.log('\nDone.');
}

main();
