'use client';
/**
 * React wrapper for <hx-tbody> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTableBody } from '@helixui/library/components/hx-table';

import type { HxTbodyProps } from './types.js';

export type { HxTbodyProps };

/**
 * Semantic table body section. Must be a direct child of `hx-table`.
Contains `hx-tr` rows with `hx-td` data cells.
 *
 * @example
 * ```tsx
 * import { HxTbody } from '@helixui/react';
 *
 * <HxTbody />
 * ```
 */
export const HxTbody = createComponent({
  tagName: 'hx-tbody',
  elementClass: HelixTableBody,
  react: React,
  events: {},
  displayName: 'HxTbody',
});

export default HxTbody;
