'use client';
/**
 * React wrapper for <hx-pagination> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixPagination } from '@helixui/library/components/hx-pagination';

import type { HxPaginationProps } from './types.js';

export type { HxPaginationProps };

/**
 * A pagination component for navigating content listings.
 *
 * @example
 * ```tsx
 * import { HxPagination } from '@helixui/react';
 *
 * <HxPagination />
 * ```
 */
export const HxPagination = createComponent({
  tagName: 'hx-pagination',
  elementClass: HelixPagination,
  react: React,
  events: {
    onHxPageChange: 'hx-page-change',
    onHxPageSizeChange: 'hx-page-size-change',
  },
  displayName: 'HxPagination',
});

export default HxPagination;
