/**
 * TypeScript types for HxPagination React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxPaginationProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Total number of pages. */
  totalPages?: number;
  /** The currently active page (1-based). */
  currentPage?: number;
  /** Number of page buttons shown on each side of the current page. */
  siblingCount?: number;
  /** Number of pages always shown at the start and end of the list. */
  boundaryCount?: number;
  /** Whether to show First and Last page buttons. */
  showFirstLast?: boolean;
  /** Accessible label for the `<nav>` element. */
  label?: string;
  /** The number of items displayed per page. When set, a page-size selector
`<select>` is rendered. Set `show-page-size` to display the selector. */
  pageSize?: number;
  /** Whether to show the page-size selector UI. */
  showPageSize?: boolean;
  /** Label text for the rows-per-page selector. */
  labelRowsPerPage?: string;
  /** Accessible label for the "First page" navigation button. */
  firstPageLabel?: string;
  /** Accessible label for the "Previous page" navigation button. */
  previousPageLabel?: string;
  /** Accessible label for the "Next page" navigation button. */
  nextPageLabel?: string;
  /** Accessible label for the "Last page" navigation button. */
  lastPageLabel?: string;

  // Event callbacks
  /** Fired when the user navigates to a new page. */
  onHxPageChange?: (event: Event) => void;
  /** Fired when the user selects a new page size. */
  onHxPageSizeChange?: (event: Event) => void;
}
