'use client';
/**
 * React wrapper for <hx-stat> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixStat } from '@helixui/library/components/hx-stat';

import type { HxStatProps } from './types.js';

export type { HxStatProps };

/**
 * A static stat display component for presenting key metrics in a healthcare dashboard.
 *
 * @example
 * ```tsx
 * import { HxStat } from '@helixui/react';
 *
 * <HxStat />
 * ```
 */
export const HxStat = createComponent({
  tagName: 'hx-stat',
  elementClass: HelixStat,
  react: React,
  events: {},
  displayName: 'HxStat',
});

export default HxStat;
