'use client';
/**
 * React wrapper for <hx-stat> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixStat } from '@helixui/library/components/hx-stat';

import type { HxStatProps } from './types.js';

export type { HxStatProps };

/**
 * A static stat display component for presenting key metrics in a healthcare dashboard.

Group 7 host-canonical: `role="group"` lives on the **host** via
`_internals.role`. The host carries the resolved accessible name so AT
walks `<hx-stat>` (role=group, label="value: label") directly. The
internal `aria-live="polite"` announcer remains in the shadow tree —
`role="group"` does NOT imply a live region, so the announcer is required
for value/label/trend update announcements.
 *
 * @example
 * ```tsx
 * import { HxStat } from '@helixui/react';
 *
 * <HxStat />
 * ```
 */
export const HxStat = createComponent({
  tagName: 'hx-stat',
  elementClass: HelixStat,
  react: React,
  events: {},
  displayName: 'HxStat',
});

export default HxStat;
