/**
 * TypeScript types for HxStat React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxStatProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The metric label displayed below the value. */
  label?: string;
  /** The metric value displayed prominently. */
  value?: string;
  /** Trend direction indicator. 'neutral' hides the indicator. */
  trend?: 'up' | 'down' | 'neutral';
  /** Size variant controlling font size. */
  size?: 'sm' | 'md' | 'lg';
  /** Prefix label for trend indicator. Override for i18n. */
  labelTrend?: string;
}
