'use client';
/**
 * React wrapper for <hx-select> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSelect } from '@helixui/library/components/hx-select';

import type { HxSelectProps } from './types.js';

export type { HxSelectProps };

/**
 * A form-associated select component with custom styling, label, error, and
help text. Options are provided via slotted `<option>` (and `<optgroup>`)
elements in the light DOM. The component wraps a hidden native `<select>`
for form participation and provides a combobox trigger for consistent
cross-browser styling.
 *
 * @example
 * ```tsx
 * import { HxSelect } from '@helixui/react';
 *
 * <HxSelect />
 * ```
 */
export const HxSelect = createComponent({
  tagName: 'hx-select',
  elementClass: HelixSelect,
  react: React,
  events: {
    onHxChange: 'hx-change'
  },
  displayName: 'HxSelect',
});

export default HxSelect;
