/**
 * TypeScript types for HxSelect React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxSelectProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The visible label text for the select. */
  label?: string;
  /** Placeholder text shown in the trigger when no option is selected. */
  placeholder?: string;
  /** The current value of the select. */
  value?: string;
  /** Whether the select is required for form submission. */
  required?: boolean;
  /** Whether the select is disabled. */
  disabled?: boolean;
  /** The name used for form submission. */
  name?: string;
  /** Error message to display. When set, the field enters an error state. */
  error?: string;
  /** Help text displayed below the select for guidance. */
  helpText?: string;
  /** Size variant of the select trigger. */
  size?: 'sm' | 'md' | 'lg';
  /** Accessible name for screen readers, if different from the visible label.
Uses `accessible-label` attribute instead of `aria-label` to avoid
ARIAMixin shadowing on the host element.

Note: `mixinDelegatesAria` is not applied to this component because form
inputs with associated labels delegate accessible naming via `<label>`
association and `aria-labelledby`, not host-level ARIA delegation. The
`accessible-label` attribute is a fallback for label-free usage. The value is forwarded to the
internal trigger button's `aria-label`. */
  accessibleLabel?: string | null;
  /** Controls whether the dropdown listbox is open. */
  open?: boolean;
  /** Validation message when no option is selected. Override for i18n. */
  labelRequired?: string;
  /** Label shown when no options are available. Override for i18n. */
  labelNoOptions?: string;

  // Event callbacks
  /** Dispatched when the selected option changes. */
  onHxChange?: (event: Event) => void;
  /** Platform constraint-validation event fired when checkValidity() / reportValidity() determine the value is invalid (form-associated component contract via ElementInternals.setValidity). */
  onInvalid?: (event: Event) => void;
}
