'use client';
/**
 * React wrapper for <hx-format-date> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixFormatDate } from '@helixui/library/components/hx-format-date';

import type { HxFormatDateProps } from './types.js';

export type { HxFormatDateProps };

/**
 * Formats and displays a date/time value using the browser's `Intl.DateTimeFormat`
(or `Intl.RelativeTimeFormat` when `relative` is set). Renders as an inline
`<time>` element — machine-readable via `datetime`, human-readable via formatted text.

No external dependencies. Uses native Intl APIs only.
 *
 * @example
 * ```tsx
 * import { HxFormatDate } from '@helixui/react';
 *
 * <HxFormatDate />
 * ```
 */
export const HxFormatDate = createComponent({
  tagName: 'hx-format-date',
  elementClass: HelixFormatDate,
  react: React,
  events: {},
  displayName: 'HxFormatDate',
});

export default HxFormatDate;
