/**
 * TypeScript types for HxFormatDate React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxFormatDateProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The date/time value to format. Accepts an ISO string, a Unix timestamp (ms), or
a `Date` object. Defaults to the current date/time when empty. */
  date?: string | number | Date;
  /** BCP 47 locale tag used for formatting (e.g. `"en-US"`, `"de"`, `"ja"`).
Defaults to `document.documentElement.lang`, then `navigator.language`. */
  lang?: string;
  /** Month display format. */
  month?: 'narrow' | 'short' | 'long' | 'numeric' | '2-digit' | undefined;
  /** Year display format. */
  year?: 'numeric' | '2-digit' | undefined;
  /** Day display format. */
  day?: 'numeric' | '2-digit' | undefined;
  /** Weekday display format. */
  weekday?: 'narrow' | 'short' | 'long' | undefined;
  /** Hour display format. */
  hour?: 'numeric' | '2-digit' | undefined;
  /** Minute display format. */
  minute?: 'numeric' | '2-digit' | undefined;
  /** Second display format. */
  second?: 'numeric' | '2-digit' | undefined;
  /** Time zone name display format. Accepts all values supported by
`Intl.DateTimeFormatOptions.timeZoneName` including `'short'`, `'long'`,
`'shortOffset'`, `'longOffset'`, `'shortGeneric'`, and `'longGeneric'`. */
  timeZoneName?: string;
  /** IANA time zone identifier (e.g. `"America/New_York"`, `"UTC"`). */
  timeZone?: string | undefined;
  /** Whether to use 12-hour or 24-hour clock. `"auto"` defers to locale default. */
  hourFormat?: 'auto' | '12' | '24';
  /** Controls whether `Intl.RelativeTimeFormat` always shows numeric output
(`"always"`) or uses natural language when possible (`"auto"`, e.g. "yesterday").
Only used when `relative` is true. */
  numeric?: 'always' | 'auto';
  /** When true, displays a relative time string such as "2 hours ago" or "in 3 days"
using `Intl.RelativeTimeFormat`.

**Important:** The relative time string is computed once at render time and does
not auto-update. If the displayed text must stay current (e.g. a live "X minutes
ago" counter), the consuming component must re-set the `date` property on its own
interval to trigger a re-render. */
  relative?: boolean;
}
