'use client';
/**
 * React wrapper for <hx-popup> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixPopup } from '@helixui/library/components/hx-popup';

import type { HxPopupProps } from './types.js';

export type { HxPopupProps };

/**
 * A low-level positioning primitive that anchors a floating panel to a reference element.
This is the base that hx-tooltip, hx-dropdown, and hx-popover build upon.
 *
 * @example
 * ```tsx
 * import { HxPopup } from '@helixui/react';
 *
 * <HxPopup />
 * ```
 */
export const HxPopup = createComponent({
  tagName: 'hx-popup',
  elementClass: HelixPopup,
  react: React,
  events: {
    onHxReposition: 'hx-reposition',
  },
  displayName: 'HxPopup',
});

export default HxPopup;
