/**
 * TypeScript types for HxPopup React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxPopupProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The reference element to anchor the popup to.

- **Attribute form** (`anchor="#selector"`): Accepts a CSS selector string resolved via
  `querySelector` from the component's root node. Use this in HTML/Twig markup.
- **Property form** (`el.anchor = element`): Accepts an `Element` reference directly.
  Setting an Element via JS property does NOT reflect to the attribute.

If not set, the element in the `anchor` slot is used. */
  anchor?: string | Element | null;
  /** Preferred placement of the popup relative to the anchor. */
  placement?:
    | string
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'left'
    | 'left-start'
    | 'left-end'
    | 'auto';
  /** Whether the popup is visible. */
  active?: boolean;
  /** Gap in pixels between the popup and the anchor element. */
  distance?: number;
  /** Offset in pixels along the anchor element's axis. */
  skidding?: number;
  /** Whether to show an arrow pointing to the anchor element. */
  arrow?: boolean;
  /** Manual placement of the arrow along the popup edge.
When not set, floating-ui calculates the optimal position. */
  arrowPlacement?: 'start' | 'center' | 'end' | null;
  /** Minimum padding in pixels from the popup edge to the arrow. */
  arrowPadding?: number;
  /** When true, flips the popup to the opposite side to avoid overflow. */
  flip?: boolean;
  /** Fallback placements to try when flipping. Accepts a JSON array string. */
  flipFallbackPlacements?: (
    | string
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'left'
    | 'left-start'
    | 'left-end'
    | 'auto'
  )[];
  /** When true, shifts the popup along the axis to remain in the viewport. */
  shift?: boolean;
  /** When true, resizes the popup to fit within the viewport.
Sets --hx-auto-size-available-width and --hx-auto-size-available-height CSS custom
properties on `:host` so they cascade into shadow DOM and are readable from light DOM. */
  autoSize?: boolean;
  /** Positioning strategy passed to floating-ui's `computePosition`.

- `'fixed'` (default): works for most cases; positions relative to the viewport.
- `'absolute'`: use inside `overflow: hidden` / scroll containers where the popup is
  positioned relative to the nearest positioned ancestor instead of the viewport. */
  strategy?: 'fixed' | 'absolute';

  // Event callbacks
  /** Emitted after the popup is repositioned. ## Accessibility Contract `hx-popup` is a **positioning utility**, not an interactive widget. It does not provide ARIA semantics. Consumers are responsible for all accessibility: - **Popup role**: Add `role="tooltip"`, `role="dialog"`, `role="listbox"`, etc. to the slotted popup content depending on its purpose. - **Trigger state**: The element that triggers the popup MUST set `aria-expanded="true/false"`. - **Association**: Use `aria-controls` on the trigger to reference the popup content element, and `aria-labelledby` / `aria-describedby` as appropriate. - **Focus management**: `hx-popup` does NOT trap focus. Consumers building dialogs or menus MUST implement focus trapping and keyboard dismiss (Escape key) themselves. - **Visibility**: The popup is hidden via `display: none` (CSS) and the `inert` attribute when inactive. Both are reliable accessibility-tree hiding mechanisms. */
  onHxReposition?: (event: Event) => void;
}
