'use client';
/**
 * React wrapper for <hx-drawer> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixDrawer } from '@helixui/library/components/hx-drawer';

import type { HxDrawerProps } from './types.js';

export type { HxDrawerProps };

/**
 * A slide-in drawer panel that can appear from any edge of the viewport.
Supports focus trapping, overlay backdrop, keyboard navigation, and full
ARIA labelling for enterprise healthcare accessibility requirements.

## Architecture Note: Native `<dialog>` Migration

This component currently uses `role="dialog"` + `aria-modal="true"` on a
`<div>` rather than the native `<dialog>` element. This is intentional for
the current release because:

1. **SSR compatibility**: Native `<dialog>` requires `showModal()` to activate
   its modal behavior (focus trapping, backdrop, top-layer). This JavaScript
   call is not available during server-side rendering, which is a primary
   consumption pattern for Drupal/Twig templates.

2. **Contained mode**: The `contained` property constrains the drawer to a
   positioned parent. Native `<dialog>` in modal mode renders in the top layer
   and cannot be constrained to a parent element.

3. **Animation control**: The current CSS transition approach provides precise
   control over slide-in/slide-out animations. Native `<dialog>` `::backdrop`
   animations have inconsistent cross-browser support.

Migration to native `<dialog>` is tracked as a future enhancement. When browser
support for `CloseWatcher`, `::backdrop` transitions, and declarative dialog
opening stabilizes, this component will be migrated to native semantics.
 *
 * @example
 * ```tsx
 * import { HxDrawer } from '@helixui/react';
 *
 * <HxDrawer />
 * ```
 */
export const HxDrawer = createComponent({
  tagName: 'hx-drawer',
  elementClass: HelixDrawer,
  react: React,
  events: {
    onHxShow: 'hx-show',
    onHxAfterShow: 'hx-after-show',
    onHxHide: 'hx-hide',
    onHxAfterHide: 'hx-after-hide',
    onHxInitialFocus: 'hx-initial-focus'
  },
  displayName: 'HxDrawer',
});

export default HxDrawer;
