'use client';
/**
 * React wrapper for <hx-drawer> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixDrawer } from '@helixui/library/components/hx-drawer';

import type { HxDrawerProps } from './types.js';

export type { HxDrawerProps };

/**
 * A slide-in drawer panel that can appear from any edge of the viewport.
Supports focus trapping, overlay backdrop, keyboard navigation, and full
ARIA labelling for enterprise healthcare accessibility requirements.
 *
 * @example
 * ```tsx
 * import { HxDrawer } from '@helixui/react';
 *
 * <HxDrawer />
 * ```
 */
export const HxDrawer = createComponent({
  tagName: 'hx-drawer',
  elementClass: HelixDrawer,
  react: React,
  events: {
    onHxShow: 'hx-show',
    onHxAfterShow: 'hx-after-show',
    onHxHide: 'hx-hide',
    onHxAfterHide: 'hx-after-hide',
    onHxInitialFocus: 'hx-initial-focus',
  },
  displayName: 'HxDrawer',
});

export default HxDrawer;
