/**
 * TypeScript types for HxDrawer React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxDrawerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Controls whether the drawer is open. */
  open?: boolean;
  /** Which edge of the viewport the drawer slides in from. */
  placement?: string;
  /** The size of the drawer panel. Use 'sm', 'md', 'lg', 'full', or any valid CSS length. */
  size?: string;
  /** When true, the drawer is constrained to its positioned parent instead of the viewport.
The host element must have `position: relative` (or the library handles it via :host). */
  contained?: boolean;
  /** When true, the header (title, header-actions, close button) is hidden. */
  noHeader?: boolean;
  /** When true, the footer slot is hidden. */
  noFooter?: boolean;
  /** Accessible label for the dialog when the `label` slot is not populated.
When the `label` slot is used, `aria-labelledby` takes precedence. */
  label?: string;

  // Event callbacks
  /** Fired when the drawer begins to open. */
  onHxShow?: (event: Event) => void;
  /** Fired after the drawer open animation completes. */
  onHxAfterShow?: (event: Event) => void;
  /** Fired when the drawer begins to close. */
  onHxHide?: (event: Event) => void;
  /** Fired after the drawer close animation completes. */
  onHxAfterHide?: (event: Event) => void;
  /** Fired when initial focus is set inside the drawer. Cancelable to override focus behavior. */
  onHxInitialFocus?: (event: Event) => void;
}
