'use client';
/**
 * React wrapper for <hx-data-table> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixDataTable } from '@helixui/library/components/hx-data-table';

import type { HxDataTableProps } from './types.js';

export type { HxDataTableProps };

/**
 * An enterprise data table with sorting, row selection, and keyboard navigation.
 *
 * @example
 * ```tsx
 * import { HxDataTable } from '@helixui/react';
 *
 * <HxDataTable />
 * ```
 */
export const HxDataTable = createComponent({
  tagName: 'hx-data-table',
  elementClass: HelixDataTable,
  react: React,
  events: {
    onHxSort: 'hx-sort',
    onHxRowClick: 'hx-row-click',
    onHxSelect: 'hx-select'
  },
  displayName: 'HxDataTable',
});

export default HxDataTable;
