/**
 * TypeScript types for HxDataTable React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxDataTableProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Column definitions. Each item: `{ key, label, sortable?, width? }`.
Can be set as a JS array or a JSON string (e.g., from a Drupal Twig attribute). */
  columns?: string;
  /** Row data. Each item is a plain object keyed by column `key` values.
Can be set as a JS array or a JSON string (e.g., from a Drupal Twig attribute). */
  rows?: Record<string, unknown>[];
  /** When true, renders a checkbox column for row selection. */
  selectable?: boolean;
  /** The column key currently used for sorting. */
  sortKey?: string;
  /** Current sort direction. */
  sortDirection?: 'asc' | 'desc';
  /** When true, renders a loading skeleton and sets `aria-busy="true"` on the host. */
  loading?: boolean;
  /** Text displayed in the default empty state when `rows` is empty and not loading. */
  emptyLabel?: string;
  /** Accessible name for the table. Exposed via `aria-label` on the `<table>` element.
Required when the table has columns — a missing label is a WCAG 4.1.2 violation. */
  label?: string;
  /** When true, the header row is sticky (position: sticky; top: 0). */
  stickyHeader?: boolean;
  /** Current page (1-based). Set to 0 or leave at default (0) to disable pagination. */
  page?: number;
  /** Number of rows per page. Set to 0 to disable pagination (show all rows). */
  pageSize?: number;

  // Event callbacks
  /** Dispatched when a sortable column header is clicked. */
  onHxSort?: (event: Event) => void;
  /** Dispatched when a data row is clicked. */
  onHxRowClick?: (event: Event) => void;
  /** Dispatched when row selection changes. */
  onHxSelect?: (event: Event) => void;
}
