'use client';
/**
 * React wrapper for <hx-dropdown> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixDropdown } from '@helixui/library/components/hx-dropdown';

import type { HxDropdownProps } from './types.js';

export type { HxDropdownProps };

/**
 * A dropdown component — a button that opens a floating panel on click.
 *
 * @example
 * ```tsx
 * import { HxDropdown } from '@helixui/react';
 *
 * <HxDropdown />
 * ```
 */
export const HxDropdown = createComponent({
  tagName: 'hx-dropdown',
  elementClass: HelixDropdown,
  react: React,
  events: {
    onHxShow: 'hx-show',
    onHxHide: 'hx-hide',
    onHxSelect: 'hx-select',
  },
  displayName: 'HxDropdown',
});

export default HxDropdown;
