/**
 * TypeScript types for HxDropdown React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxDropdownProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Whether the dropdown panel is open. */
  open?: boolean;
  /** Preferred placement of the panel relative to the trigger. */
  placement?:
    | string
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'start'
    | 'end';
  /** Accessible label for the dropdown menu panel. Override for i18n. */
  label?: string;
  /** Whether the dropdown is disabled. Prevents opening. */
  disabled?: boolean;
  /** Gap in pixels between the trigger and the panel. */
  distance?: number;

  // Event callbacks
  /** Dispatched when the dropdown is opened. */
  onHxShow?: (event: Event) => void;
  /** Dispatched when the dropdown is closed. */
  onHxHide?: (event: Event) => void;
  /** Dispatched when a menu item is selected. */
  onHxSelect?: (event: Event) => void;
}
