'use client';
/**
 * React wrapper for <hx-popover> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixPopover } from '@helixui/library/components/hx-popover';

import type { HxPopoverProps } from './types.js';

export type { HxPopoverProps };

/**
 * A popover that displays rich floating content attached to a trigger element.
 *
 * @example
 * ```tsx
 * import { HxPopover } from '@helixui/react';
 *
 * <HxPopover />
 * ```
 */
export const HxPopover = createComponent({
  tagName: 'hx-popover',
  elementClass: HelixPopover,
  react: React,
  events: {
    onHxShow: 'hx-show',
    onHxAfterShow: 'hx-after-show',
    onHxHide: 'hx-hide',
    onHxAfterHide: 'hx-after-hide'
  },
  displayName: 'HxPopover',
});

export default HxPopover;
