/**
 * TypeScript types for HxPopover React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxPopoverProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Whether the popover is open. */
  open?: boolean;
  /** Preferred placement of the popover relative to the anchor. */
  placement?:
    | string
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'right'
    | 'right-start'
    | 'right-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'left'
    | 'left-start'
    | 'left-end';
  /** How the popover is triggered. */
  trigger?: 'click' | 'hover' | 'focus' | 'manual';
  /** Distance in pixels between the popover and the anchor. */
  distance?: number;
  /** Alignment offset in pixels along the anchor. */
  skidding?: number;
  /** Whether to show an arrow pointing to the anchor. */
  arrow?: boolean;
  /** Accessible label for the popover body (sets aria-label on the dialog). */
  label?: string;

  // Event callbacks
  /** Emitted when the popover begins to show. */
  onHxShow?: (event: Event) => void;
  /** Emitted after the popover is fully visible. */
  onHxAfterShow?: (event: Event) => void;
  /** Emitted when the popover begins to hide. */
  onHxHide?: (event: Event) => void;
  /** Emitted after the popover is fully hidden. */
  onHxAfterHide?: (event: Event) => void;
}
