'use client';
/**
 * React wrapper for <hx-text> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixText } from '@helixui/library/components/hx-text';

import type { HxTextProps } from './types.js';

export type { HxTextProps };

/**
 * A semantic typography wrapper that applies consistent text styles using design tokens.
 *
 * @example
 * ```tsx
 * import { HxText } from '@helixui/react';
 *
 * <HxText />
 * ```
 */
export const HxText = createComponent({
  tagName: 'hx-text',
  elementClass: HelixText,
  react: React,
  events: {},
  displayName: 'HxText',
});

export default HxText;
