/**
 * TypeScript types for HxText React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTextProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Typography variant controlling font size, line height, and letter spacing.

Note: The public variant set (body / body-sm / body-lg / label / label-sm / caption / code /
overline) intentionally extends the original audit spec (body / lead / small / caption /
overline). `lead` and `small` were replaced with the more granular `body-lg`, `body-sm`,
`label`, `label-sm`, and `code` variants to better serve healthcare UI density requirements.
There are no `lead` or `small` variants — consumers must use `body-lg` and `body-sm`
respectively. */
  variant?: 'body' | 'body-sm' | 'body-lg' | 'label' | 'label-sm' | 'caption' | 'code' | 'overline';
  /** Font weight override. When unset, the variant's default weight is used. */
  weight?: 'regular' | 'medium' | 'semibold' | 'bold' | undefined;
  /** Semantic color intent. */
  color?: 'default' | 'subtle' | 'disabled' | 'inverse' | 'danger' | 'success' | 'warning';
  /** When true, clips text to a single line with an ellipsis overflow. */
  truncate?: boolean;
  /** Maximum number of lines to display before clamping with ellipsis.
When set, overrides `truncate`. Set to 0 to disable. */
  lines?: number;
  /** The HTML element to render as the inner base element.
Use to produce semantically appropriate markup (e.g., `p`, `strong`, `em`).
Defaults to `span` for inline usage.

In Drupal Twig: `<hx-text as="p" variant="body">...</hx-text>` */
  as?: 'span' | 'p' | 'strong' | 'em' | 'div';
}
