'use client';
/**
 * React wrapper for <hx-nav-item> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixNavItem } from '@helixui/library/components/hx-side-nav';

import type { HxNavItemProps } from './types.js';

export type { HxNavItemProps };

/**
 * A navigation item for use inside hx-side-nav.
Supports icons, badges, sub-navigation, and active/disabled states.
 *
 * @example
 * ```tsx
 * import { HxNavItem } from '@helixui/react';
 *
 * <HxNavItem />
 * ```
 */
export const HxNavItem = createComponent({
  tagName: 'hx-nav-item',
  elementClass: HelixNavItem,
  react: React,
  events: {},
  displayName: 'HxNavItem',
});

export default HxNavItem;
