/**
 * TypeScript types for HxNavItem React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxNavItemProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The URL this nav item links to. */
  href?: string;
  /** Whether this item is the current/active page. */
  active?: boolean;
  /** Whether the sub-navigation is expanded. */
  expanded?: boolean;
  /** Whether this nav item is disabled. */
  disabled?: boolean;
}
