'use client';
/**
 * React wrapper for <hx-rating> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixRating } from '@helixui/library/components/hx-rating';

import type { HxRatingProps } from './types.js';

export type { HxRatingProps };

/**
 * A star rating input component for user feedback and display.
Supports whole and half-star ratings, keyboard navigation, hover preview,
and native form participation via ElementInternals.

### Accessibility

- **Interactive mode (precision=1)**: Uses `role="radiogroup"` with individual `role="radio"` stars.
  Each star has `aria-label` ("1 star", "2 stars", etc.) and `aria-checked`.
- **Interactive mode (precision=0.5)**: Uses `role="slider"` with `aria-valuemin`, `aria-valuemax`,
  `aria-valuenow`, and `aria-valuetext` (e.g. "2.5 out of 5 stars"). Star elements are
  `aria-hidden="true"` decorative visuals. This avoids a WCAG 2.5.3 label-content-name mismatch
  that would occur if a `role="radio"` labeled "3 stars" were checked for a value of 2.5.
- **Readonly mode**: Uses `role="img"` with a descriptive `aria-label` ("Rating: 3 out of 5").
- **Keyboard**: Arrow keys (Left/Right/Up/Down) adjust value by `precision` step.
  Home sets to 0, End sets to `max`. Focus follows the active tab stop.
- **Disabled**: Sets `aria-disabled="true"` on the group and prevents interaction.
 *
 * @example
 * ```tsx
 * import { HxRating } from '@helixui/react';
 *
 * <HxRating />
 * ```
 */
export const HxRating = createComponent({
  tagName: 'hx-rating',
  elementClass: HelixRating,
  react: React,
  events: {
    onHxChange: 'hx-change',
    onHxHover: 'hx-hover',
  },
  displayName: 'HxRating',
});

export default HxRating;
