/**
 * TypeScript types for HxRating React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxRatingProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The current rating value (0 to max). */
  value?: number;
  /** The maximum number of stars. */
  max?: number;
  /** The minimum selectable increment. Use 0.5 for half-star ratings. */
  precision?: string | string;
  /** When true, the rating is display-only and cannot be changed. */
  readonly?: boolean;
  /** When true, the rating is disabled and cannot be interacted with. */
  disabled?: boolean;
  /** The name submitted with the form. */
  name?: string;
  /** Accessible label for the rating group. */
  label?: string;

  // Event callbacks
  /** Dispatched when the rating value changes. */
  onHxChange?: (event: Event) => void;
  /** Dispatched while hovering over a star for preview. */
  onHxHover?: (event: Event) => void;
}
