'use client';
/**
 * React wrapper for <hx-breadcrumb> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixBreadcrumb } from '@helixui/library/components/hx-breadcrumb';

import type { HxBreadcrumbProps } from './types.js';

export type { HxBreadcrumbProps };

/**
 * Breadcrumb navigation component with automatic truncation and JSON-LD structured data.
 *
 * @example
 * ```tsx
 * import { HxBreadcrumb } from '@helixui/react';
 *
 * <HxBreadcrumb />
 * ```
 */
export const HxBreadcrumb = createComponent({
  tagName: 'hx-breadcrumb',
  elementClass: HelixBreadcrumb,
  react: React,
  events: {},
  displayName: 'HxBreadcrumb',
});

export default HxBreadcrumb;
