'use client';
/**
 * React wrapper for <hx-progress-bar> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixProgressBar } from '@helixui/library/components/hx-progress-bar';

import type { HxProgressBarProps } from './types.js';

export type { HxProgressBarProps };

/**
 * A linear progress indicator for determinate and indeterminate states.

Group 7 host-canonical: `role="progressbar"` is mirrored onto the **host**
via `_internals.role` (cross-shadow IDREF wiring) AND kept on the inner
`[role="progressbar"]` track for legacy AT and consumer queries. This is
the hx-progress-ring dual-surface pattern (Group 7 gold-standard).
Consumer-supplied `aria-labelledby` / `aria-describedby` on the host
resolves through the shared IDREF mirror so cross-shadow naming reaches
the announced surface even when the labels live in another shadow tree.

The internal `aria-live="polite"` announcer for the "Complete" milestone
is preserved (`role="progressbar"` does NOT imply a live region — an
explicit live announcer is required for value-update announcements).
 *
 * @example
 * ```tsx
 * import { HxProgressBar } from '@helixui/react';
 *
 * <HxProgressBar />
 * ```
 */
export const HxProgressBar = createComponent({
  tagName: 'hx-progress-bar',
  elementClass: HelixProgressBar,
  react: React,
  events: {
    onHxComplete: 'hx-complete',
  },
  displayName: 'HxProgressBar',
});

export default HxProgressBar;
