'use client';
/**
 * React wrapper for <hx-progress-bar> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixProgressBar } from '@helixui/library/components/hx-progress-bar';

import type { HxProgressBarProps } from './types.js';

export type { HxProgressBarProps };

/**
 * A linear progress indicator for determinate and indeterminate states.
 *
 * @example
 * ```tsx
 * import { HxProgressBar } from '@helixui/react';
 *
 * <HxProgressBar />
 * ```
 */
export const HxProgressBar = createComponent({
  tagName: 'hx-progress-bar',
  elementClass: HelixProgressBar,
  react: React,
  events: {
    onHxComplete: 'hx-complete'
  },
  displayName: 'HxProgressBar',
});

export default HxProgressBar;
