/**
 * TypeScript types for HxProgressBar React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxProgressBarProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Current progress value (min–max). Set to null for indeterminate state. */
  value?: number | null;
  /** Minimum value for the progress bar. */
  min?: number;
  /** Maximum value for the progress bar. */
  max?: number;
  /** When true, displays an animated indeterminate loading state regardless of value. */
  indeterminate?: boolean;
  /** Accessible label for the progress bar (maps to aria-label when no label slot content is used). */
  label?: string;
  /** Additional description for the progress operation, linked via aria-describedby. */
  description?: string;
  /** Size of the progress bar track. */
  size?: 'sm' | 'md' | 'lg';
  /** Visual variant controlling the indicator color. */
  variant?: 'default' | 'success' | 'warning' | 'danger';

  // Event callbacks
  /** Emitted when progress reaches 100%. */
  onHxComplete?: (event: Event) => void;
}
