'use client';
/**
 * React wrapper for <hx-field> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixField } from '@helixui/library/components/hx-field';

import type { HxFieldProps } from './types.js';

export type { HxFieldProps };

/**
 * Layout wrapper providing consistent label + input + help text + validation
message structure for any form control. Use this when wrapping non-HELiX
form controls or native HTML elements in the HELiX form field pattern.

This component is NOT form-associated — it is a pure visual layout wrapper.

**Light DOM side effect:** This component injects a visually-hidden `<span>`
into its light DOM children for ARIA describedby linkage across the shadow
DOM boundary. This span has `id="${fieldId}-desc"` and is removed on
`disconnectedCallback`. This is an intentional, documented accessibility
mechanism.
 *
 * @example
 * ```tsx
 * import { HxField } from '@helixui/react';
 *
 * <HxField />
 * ```
 */
export const HxField = createComponent({
  tagName: 'hx-field',
  elementClass: HelixField,
  react: React,
  events: {},
  displayName: 'HxField',
});

export default HxField;
