/**
 * TypeScript types for HxField React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxFieldProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The visible label text for the field. */
  label?: string;
  /** Whether the field is required. Shows a required indicator on the label. */
  required?: boolean;
  /** Error message to display. When set, the field enters an error state. */
  error?: string;
  /** Help text displayed below the control for guidance. */
  helpText?: string;
  /** Visual disabled state applied via opacity. Does not affect slotted control
interactivity — set disabled on the slotted control directly. */
  disabled?: boolean;
  /** Size variant controlling label and help text font sizes. */
  hxSize?: 'sm' | 'md' | 'lg';
  /** Layout variant. 'column' stacks label above control; 'inline' places them side-by-side. */
  layout?: 'column' | 'inline';
}
