'use client';
/**
 * React wrapper for <hx-text-input> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTextInput } from '@helixui/library/components/hx-text-input';

import type { HxTextInputProps } from './types.js';

export type { HxTextInputProps };

/**
 * A text input component with label, validation, and form association.
Supports accessible labeling via `label` property, `aria-label` attribute, or the `label` slot.
Uses `aria-invalid` and `aria-describedby` on the native input for screen reader support. Native `required` provides implicit aria-required mapping per HTML-AAM.
Error messages are announced via `role="alert"`. Keyboard navigation follows native input behavior.
 *
 * @example
 * ```tsx
 * import { HxTextInput } from '@helixui/react';
 *
 * <HxTextInput />
 * ```
 */
export const HxTextInput = createComponent({
  tagName: 'hx-text-input',
  elementClass: HelixTextInput,
  react: React,
  events: {
    onHxInput: 'hx-input',
    onHxChange: 'hx-change',
  },
  displayName: 'HxTextInput',
});

export default HxTextInput;
