/**
 * TypeScript types for HxTextInput React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTextInputProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The visible label text for the input. */
  label?: string;
  /** Placeholder text shown when the input is empty. */
  placeholder?: string;
  /** The current value of the input. */
  value?: string;
  /** The type of the native input element. */
  type?: 'text' | 'email' | 'password' | 'tel' | 'url' | 'search' | 'number' | 'date';
  /** Whether the input is required for form submission. */
  required?: boolean;
  /** Whether the input is disabled. */
  disabled?: boolean;
  /** Error message to display. When set, the input enters an error state. */
  error?: string;
  /** Help text displayed below the input for guidance. */
  helpText?: string;
  /** The name of the input, used for form submission. */
  name?: string;
  /** Accessible name for screen readers, if different from the visible label. */
  ariaLabel?: string | null;
  /** Whether the input is read-only. */
  readonly?: boolean;
  /** Minimum number of characters allowed. */
  minlength?: number | undefined;
  /** Maximum number of characters allowed. */
  maxlength?: number | undefined;
  /** A regular expression pattern the value must match for form validation. */
  pattern?: string;
  /** Hint for the browser's autocomplete feature. Accepts standard HTML autocomplete values. */
  autocomplete?: string;
  /** Visual size of the input field. */
  size?: 'sm' | 'md' | 'lg';
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched on every keystroke as the user types. */
  onHxInput?: (event: Event) => void;
  /** Dispatched when the input loses focus after its value changed. */
  onHxChange?: (event: Event) => void;
}
