/**
 * TypeScript types for HxTextInput React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTextInputProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The visible label text for the input. */
  label?: string;
  /** Placeholder text shown when the input is empty. */
  placeholder?: string;
  /** The current value of the input. */
  value?: string;
  /** The type of the native input element. */
  type?: 'text' | 'email' | 'password' | 'tel' | 'url' | 'search' | 'number' | 'date';
  /** Whether the input is required for form submission. */
  required?: boolean;
  /** Whether the input is disabled. */
  disabled?: boolean;
  /** Error message to display. When set, the input enters an error state. */
  error?: string;
  /** Help text displayed below the input for guidance. */
  helpText?: string;
  /** The name of the input, used for form submission. */
  name?: string;
  /** Accessible name for screen readers, if different from the visible label.
Uses `accessible-label` attribute instead of `aria-label` to avoid
ARIAMixin shadowing on the host element. The value is forwarded to the
internal native input's `aria-label`.

Note: `mixinDelegatesAria` is not applied to this component because form
inputs with associated labels delegate accessible naming via `<label>`
association and `aria-labelledby`, not host-level ARIA delegation. The
`accessible-label` attribute is a fallback for label-free usage. */
  accessibleLabel?: string | null;
  /** Whether the input is read-only. */
  readonly?: boolean;
  /** Minimum number of characters allowed. */
  minlength?: number | undefined;
  /** Maximum number of characters allowed. */
  maxlength?: number | undefined;
  /** A regular expression pattern the value must match for form validation. */
  pattern?: string;
  /** Hint for the browser's autocomplete feature. Accepts standard HTML autocomplete values. */
  autocomplete?: string;
  /** Validation message shown when the field is required but empty. */
  requiredMessage?: string;
  /** Validation message shown when the value is shorter than `minlength`.
Supports a `{min}` placeholder that is substituted with the resolved
`minlength` value (mirrors the `{label}` token convention used elsewhere
in the library). When empty, the built-in English message is used, so
default output is unchanged. */
  minlengthMessage?: string;
  /** Validation message shown when the value is longer than `maxlength`.
Supports a `{max}` placeholder that is substituted with the resolved
`maxlength` value (mirrors the `{label}` token convention used elsewhere
in the library). When empty, the built-in English message is used, so
default output is unchanged. */
  maxlengthMessage?: string;
  /** Visual size of the input field. */
  size?: 'sm' | 'md' | 'lg';
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched on every keystroke as the user types. */
  onHxInput?: (event: Event) => void;
  /** Dispatched when the input loses focus after its value changed. */
  onHxChange?: (event: Event) => void;
}
