'use client';
/**
 * React wrapper for <hx-alert> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixAlert } from '@helixui/library/components/hx-alert';

import type { HxAlertProps } from './types.js';

export type { HxAlertProps };

/**
 * A feedback component for communicating status messages, warnings, and errors.
Critical for healthcare patient safety alerts.
 *
 * @example
 * ```tsx
 * import { HxAlert } from '@helixui/react';
 *
 * <HxAlert />
 * ```
 */
export const HxAlert = createComponent({
  tagName: 'hx-alert',
  elementClass: HelixAlert,
  react: React,
  events: {
    onHxClose: 'hx-close',
    onHxAfterClose: 'hx-after-close',
  },
  displayName: 'HxAlert',
});

export default HxAlert;
