/**
 * TypeScript types for HxAlert React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxAlertProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual variant of the alert that determines colors and ARIA semantics. */
  variant?: 'info' | 'success' | 'warning' | 'error';
  /** Whether the alert can be dismissed by the user. */
  dismissible?: boolean;
  /** Optional heading text that provides context for the close button's accessible label.
When provided, the close button is announced as "Close [heading] alert".
When absent, the close button falls back to "Close alert". */
  heading?: string;
  /** Accessible label for the close button. Override for i18n. */
  labelClose?: string;
  /** Whether the alert is visible. Add the `open` attribute to show the alert. */
  open?: boolean;
  /** Whether to show the default variant icon. Add `show-icon` attribute to display the icon. */
  showIcon?: boolean;
  /** When true, applies a left border accent stripe instead of a full border.
Common healthcare/enterprise dashboard pattern for visual distinction of alert types. */
  accent?: boolean;
  /** Override for the severity prefix announced to screen readers (e.g., "Info:", "Error:").
When not set, defaults to the English label matching the current variant. */
  severityLabel?: string | undefined;
  /** CSS selector for the element to return focus to after the alert is dismissed.
When set, the component will find and focus the matching element after dismissal.
If not set, focus management is the caller's responsibility via the hx-after-close event. */
  returnFocusTo?: string | null;

  // Event callbacks
  /** Dispatched when the user dismisses the alert. */
  onHxClose?: (event: Event) => void;
  /** Dispatched after the alert is dismissed. */
  onHxAfterClose?: (event: Event) => void;
}
