'use client';
/**
 * React wrapper for <hx-checkbox> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixCheckbox } from '@helixui/library/components/hx-checkbox';

import type { HxCheckboxProps } from './types.js';

export type { HxCheckboxProps };

/**
 * A checkbox component with label, validation, and form association.
 *
 * @example
 * ```tsx
 * import { HxCheckbox } from '@helixui/react';
 *
 * <HxCheckbox />
 * ```
 */
export const HxCheckbox = createComponent({
  tagName: 'hx-checkbox',
  elementClass: HelixCheckbox,
  react: React,
  events: {
    onHxChange: 'hx-change',
  },
  displayName: 'HxCheckbox',
});

export default HxCheckbox;
