/**
 * TypeScript types for HxCheckbox React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxCheckboxProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Whether the checkbox is checked. */
  checked?: boolean;
  /** Whether the checkbox is in an indeterminate state (e.g., for "select all" patterns). */
  indeterminate?: boolean;
  /** Whether the checkbox is disabled. */
  disabled?: boolean;
  /** Whether the checkbox is required for form submission. */
  required?: boolean;
  /** The name of the checkbox, used for form submission. */
  name?: string;
  /** The value submitted when the checkbox is checked. */
  value?: string;
  /** The visible label text for the checkbox. */
  label?: string;
  /** Error message to display. When set, the checkbox enters an error state. */
  error?: string;
  /** Help text displayed below the checkbox for guidance. */
  helpText?: string;
  /** The size of the checkbox. */
  size?: 'sm' | 'md' | 'lg';
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched when the checkbox is toggled. */
  onHxChange?: (event: Event) => void;
}
