'use client';
/**
 * React wrapper for <hx-date-picker> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixDatePicker } from '@helixui/library/components/hx-date-picker';

import type { HxDatePickerProps } from './types.js';

export type { HxDatePickerProps };

/**
 * Date picker component for selecting dates with keyboard-accessible calendar popup.
 *
 * @example
 * ```tsx
 * import { HxDatePicker } from '@helixui/react';
 *
 * <HxDatePicker />
 * ```
 */
export const HxDatePicker = createComponent({
  tagName: 'hx-date-picker',
  elementClass: HelixDatePicker,
  react: React,
  events: {
    onHxChange: 'hx-change',
  },
  displayName: 'HxDatePicker',
});

export default HxDatePicker;
