/**
 * TypeScript types for HxDatePicker React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxDatePickerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The name of the field, used for form submission. */
  name?: string;
  /** The current value as an ISO 8601 date string (e.g. 2026-03-04). */
  value?: string;
  /** The minimum selectable date as an ISO 8601 string. */
  min?: string;
  /** The maximum selectable date as an ISO 8601 string. */
  max?: string;
  /** The visible label text. */
  label?: string;
  /** Whether the field is required for form submission. */
  required?: boolean;
  /** Whether the field is disabled. */
  disabled?: boolean;
  /** Error message to display. When set, the field enters an error state. */
  error?: string;
  /** Help text displayed below the field for guidance. */
  helpText?: string;
  /** Display format hint shown as placeholder (e.g. MM/DD/YYYY). */
  format?: string;
  /** Locale string used for formatting the display value. */
  locale?: string;
  /** Validation message shown when the field is required but empty. */
  requiredMessage?: string;
  /** Accessible label for the calendar dialog. */
  chooseDateLabel?: string;
  /** Accessible label for the calendar trigger button when the calendar is closed. */
  openCalendarLabel?: string;
  /** Accessible label for the calendar trigger button when the calendar is open. */
  closeCalendarLabel?: string;
  /** Accessible label for the previous month navigation button. */
  previousMonthLabel?: string;
  /** Accessible label for the next month navigation button. */
  nextMonthLabel?: string;
  /** The form element associated with this component, or null if not in a form. */
  form?: HTMLFormElement | null;
  /** The current validation message, or an empty string if the field is valid. */
  validationMessage?: string;
  /** The current validity state of the field. */
  validity?: ValidityState;

  // Event callbacks
  /** Emitted when the selected date changes. */
  onHxChange?: (event: Event) => void;
}
