'use client';
/**
 * React wrapper for <hx-structured-list-row> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixStructuredListRow } from '@helixui/library/components/hx-structured-list';

import type { HxStructuredListRowProps } from './types.js';

export type { HxStructuredListRowProps };

/**
 * A single row within an `hx-structured-list`. Renders a label/value pair
with an optional actions area.
 *
 * @example
 * ```tsx
 * import { HxStructuredListRow } from '@helixui/react';
 *
 * <HxStructuredListRow />
 * ```
 */
export const HxStructuredListRow = createComponent({
  tagName: 'hx-structured-list-row',
  elementClass: HelixStructuredListRow,
  react: React,
  events: {},
  displayName: 'HxStructuredListRow',
});

export default HxStructuredListRow;
