'use client';
/**
 * React wrapper for <hx-list> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixList } from '@helixui/library/components/hx-list';

import type { HxListProps } from './types.js';

export type { HxListProps };

/**
 * A styled list container supporting plain, bulleted, numbered, description, and interactive variants.

Group 7 host-canonical: `role="list"` (or `role="listbox"` in interactive
mode) lives on the **host** via `_internals.role`, harmonizing with
`hx-structured-list` (the gold-standard exemplar for Group 7). The `<dl>`
description variant keeps native semantics — no host role assigned, since
`<dl>` IS the semantic surface and AT walks it directly.
 *
 * @example
 * ```tsx
 * import { HxList } from '@helixui/react';
 *
 * <HxList />
 * ```
 */
export const HxList = createComponent({
  tagName: 'hx-list',
  elementClass: HelixList,
  react: React,
  events: {
    onHxSelect: 'hx-select',
  },
  displayName: 'HxList',
});

export default HxList;
