/**
 * TypeScript types for HxList React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxListProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual variant of the list. */
  variant?: 'plain' | 'bulleted' | 'numbered' | 'description' | 'interactive';
  /** Whether to show dividers between list items. */
  divided?: boolean;
  /** Accessible label for the list. Required when variant is "interactive" (listbox role). */
  label?: string | undefined;

  // Event callbacks
  /** Dispatched when an item is clicked in interactive mode. */
  onHxSelect?: (event: Event) => void;
}
