'use client';
/**
 * React wrapper for <hx-tab> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTab } from '@helixui/library/components/hx-tabs';

import type { HxTabProps } from './types.js';

export type { HxTabProps };

/**
 * An individual tab button, designed to be used inside an `<hx-tabs>` container.
Must be placed in the `tab` named slot of `<hx-tabs>`.
 *
 * @example
 * ```tsx
 * import { HxTab } from '@helixui/react';
 *
 * <HxTab />
 * ```
 */
export const HxTab = createComponent({
  tagName: 'hx-tab',
  elementClass: HelixTab,
  react: React,
  events: {},
  displayName: 'HxTab',
});

export default HxTab;
