/**
 * TypeScript types for HxTab React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTabProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The name of the `<hx-tab-panel>` this tab controls. Must match the `name`
attribute on the corresponding `<hx-tab-panel>`. */
  panel?: string;
  /** Whether this tab is currently selected. Managed by the parent `<hx-tabs>`. */
  selected?: boolean;
  /** Whether this tab is disabled. Prevents selection and keyboard navigation. */
  disabled?: boolean;
}
