'use client';
/**
 * React wrapper for <hx-tooltip> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTooltip } from '@helixui/library/components/hx-tooltip';

import type { HxTooltipProps } from './types.js';

export type { HxTooltipProps };

/**
 * A tooltip that displays contextual help text on hover or focus.
 *
 * @example
 * ```tsx
 * import { HxTooltip } from '@helixui/react';
 *
 * <HxTooltip />
 * ```
 */
export const HxTooltip = createComponent({
  tagName: 'hx-tooltip',
  elementClass: HelixTooltip,
  react: React,
  events: {},
  displayName: 'HxTooltip',
});

export default HxTooltip;
