/**
 * TypeScript types for HxTooltip React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTooltipProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Preferred placement of the tooltip relative to the trigger.
Supports all Floating UI placement values including alignment variants
(e.g. 'top-start', 'bottom-end') and 'auto'. */
  placement?: string | 'top' | 'top-start' | 'top-end' | 'right' | 'right-start' | 'right-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end';
  /** Delay in milliseconds before the tooltip is shown. */
  showDelay?: number;
  /** Delay in milliseconds before the tooltip is hidden. */
  hideDelay?: number;
}
