'use client';
/**
 * React wrapper for <hx-side-nav> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSideNav } from '@helixui/library/components/hx-side-nav';

import type { HxSideNavProps } from './types.js';

export type { HxSideNavProps };

/**
 * A collapsible left-side navigation panel with nested menu item support.
Designed for clinical portals, admin dashboards, and department navigation.
 *
 * @example
 * ```tsx
 * import { HxSideNav } from '@helixui/react';
 *
 * <HxSideNav />
 * ```
 */
export const HxSideNav = createComponent({
  tagName: 'hx-side-nav',
  elementClass: HelixSideNav,
  react: React,
  events: {
    onHxCollapse: 'hx-collapse',
    onHxExpand: 'hx-expand'
  },
  displayName: 'HxSideNav',
});

export default HxSideNav;
