/**
 * TypeScript types for HxSideNav React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxSideNavProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** When true, the nav collapses to show icons only. */
  collapsed?: boolean;
  /** The accessible label for the nav landmark. */
  label?: string;

  // Event callbacks
  /** Dispatched when the nav collapses to icon-only mode. */
  onHxCollapse?: (event: Event) => void;
  /** Dispatched when the nav expands to full width. */
  onHxExpand?: (event: Event) => void;
}
