'use client';
/**
 * React wrapper for <hx-breadcrumb-item> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixBreadcrumbItem } from '@helixui/library/components/hx-breadcrumb';

import type { HxBreadcrumbItemProps } from './types.js';

export type { HxBreadcrumbItemProps };

/**
 * A single breadcrumb navigation item.
 *
 * @example
 * ```tsx
 * import { HxBreadcrumbItem } from '@helixui/react';
 *
 * <HxBreadcrumbItem />
 * ```
 */
export const HxBreadcrumbItem = createComponent({
  tagName: 'hx-breadcrumb-item',
  elementClass: HelixBreadcrumbItem,
  react: React,
  events: {},
  displayName: 'HxBreadcrumbItem',
});

export default HxBreadcrumbItem;
