/**
 * TypeScript types for HxBreadcrumbItem React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxBreadcrumbItemProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The URL for this breadcrumb link. Omit for the current page item.
When `current` is true, this attribute is ignored and the item always
renders as static text per WAI-ARIA APG breadcrumb guidance. */
  href?: string | undefined;
  /** Marks this item as the current page. When set, the item always renders as
static text (never a navigable link) and `aria-current="page"` is placed on
the inner text element per WAI-ARIA APG breadcrumb guidance, yielding the
canonical AT announcement ("current page, Patient Records").

Can be set explicitly by consumers (e.g. Drupal Twig templates) to override
the default positional last-item detection in `hx-breadcrumb`. When any item
in the breadcrumb has an explicit `current` attribute, the parent will not
override it. */
  current?: boolean;
}
