'use client';
/**
 * React wrapper for <hx-file-upload> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixFileUpload } from '@helixui/library/components/hx-file-upload';

import type { HxFileUploadProps } from './types.js';

export type { HxFileUploadProps };

/**
 * A drag-and-drop file upload component with client-side validation,
file list management, per-file progress, and native form association.
 *
 * @example
 * ```tsx
 * import { HxFileUpload } from '@helixui/react';
 *
 * <HxFileUpload />
 * ```
 */
export const HxFileUpload = createComponent({
  tagName: 'hx-file-upload',
  elementClass: HelixFileUpload,
  react: React,
  events: {
    onHxError: 'hx-error',
    onHxUpload: 'hx-upload',
    onHxRemove: 'hx-remove',
  },
  displayName: 'HxFileUpload',
});

export default HxFileUpload;
