/**
 * TypeScript types for HxFileUpload React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxFileUploadProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The form field name used during form submission. */
  name?: string;
  /** Accepted file types as a comma-separated list of MIME types or extensions.
Mirrors the native `<input type="file" accept>` attribute. */
  accept?: string;
  /** Maximum allowed file size in bytes. 0 means unlimited. */
  maxSize?: number;
  /** Maximum number of files that can be selected. 0 means unlimited. */
  maxFiles?: number;
  /** Whether multiple files may be selected at once. */
  multiple?: boolean;
  /** Visible label text for the dropzone. */
  label?: string;
  /** Whether the component is disabled. */
  disabled?: boolean;
  /** Error message displayed below the dropzone. Also puts the dropzone in an error visual state. */
  error?: string;
  /** Instructional text shown in the dropzone when no custom slot content is provided.
Also used as the accessible label for the dropzone. */
  labelDropzone?: string;
  /** Accessible label for the selected files list. */
  labelFileList?: string;
  /** Generates upload progress description for screen readers. */
  labelUploadProgress?: string;
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;
  /** Returns a read-only copy of the currently selected files. */
  files?: File[];

  // Event callbacks
  /** Dispatched when file validation fails (type or size constraint). */
  onHxError?: (event: Event) => void;
  /** Dispatched when valid files are selected via drag-and-drop or the file picker. */
  onHxUpload?: (event: Event) => void;
  /** Dispatched when a file is removed from the list. */
  onHxRemove?: (event: Event) => void;
}
