'use client';
/**
 * React wrapper for <hx-image> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixImage } from '@helixui/library/components/hx-image';

import type { HxImageProps } from './types.js';

export type { HxImageProps };

/**
 * An accessible image wrapper with lazy loading, fallback support, aspect ratio control,
responsive image (srcset/sizes) support, and optional caption.
 *
 * @example
 * ```tsx
 * import { HxImage } from '@helixui/react';
 *
 * <HxImage />
 * ```
 */
export const HxImage = createComponent({
  tagName: 'hx-image',
  elementClass: HelixImage,
  react: React,
  events: {
    onHxLoad: 'hx-load',
    onHxError: 'hx-error'
  },
  displayName: 'HxImage',
});

export default HxImage;
