/**
 * TypeScript types for HxImage React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxImageProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The URL of the image to display. */
  src?: string;
  /** Accessible text description of the image.
Required for informative images. Use the `decorative` prop for decorative images
instead of setting this to an empty string — explicit decorative intent is preferred. */
  alt?: string | undefined;
  /** Marks the image as decorative (hidden from screen readers).
Use this instead of `alt=""` to make decorative intent explicit in markup.
When set, the inner img receives `alt=""` and `role="presentation"`. */
  decorative?: boolean;
  /** Width of the image element. */
  width?: number | string | undefined;
  /** Height of the image element. */
  height?: number | string | undefined;
  /** Loading strategy for the image. */
  loading?: 'lazy' | 'eager';
  /** How the image should be resized to fit its container.
Maps to CSS object-fit. */
  fit?: 'contain' | 'cover' | 'fill' | 'none' | 'scale-down' | undefined;
  /** CSS aspect-ratio value (e.g. "16/9", "1", "4/3").
When set, the container maintains this ratio. */
  ratio?: string | undefined;
  /** Border radius for the image.
Boolean attribute (or `true`) applies the theme's medium radius token.
A string value is used directly as a CSS border-radius value (e.g. "1rem", "50%").

Note: When set as an HTML attribute (`<hx-image rounded>`), Lit receives the value as
an empty string (`''`). When set programmatically (`el.rounded = true`), it receives
a boolean. Both forms apply the theme radius token. */
  rounded?: boolean | string | undefined;
  /** Fallback image URL shown when the primary src fails to load. */
  fallbackSrc?: string | undefined;
  /** A comma-separated list of image candidates for responsive images.
Passed directly to the inner img's srcset attribute.
Enables Drupal responsive image styles and browser-native image selection. */
  srcset?: string | undefined;
  /** Media conditions indicating which image size to use alongside srcset.
Works in conjunction with the `srcset` attribute. */
  sizes?: string | undefined;

  // Event callbacks
  /** Dispatched when the image has successfully loaded. */
  onHxLoad?: (event: Event) => void;
  /** Dispatched when the image fails to load (including after fallback-src also fails). */
  onHxError?: (event: Event) => void;
}
