'use client';
/**
 * React wrapper for <hx-combobox> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixCombobox } from '@helixui/library/components/hx-combobox';

import type { HxComboboxProps } from './types.js';

export type { HxComboboxProps };

/**
 * A form-associated combobox component combining a text input with a listbox
for autocomplete and typeahead. Supports filtering, free-text entry,
keyboard navigation, and async option loading.
 *
 * @example
 * ```tsx
 * import { HxCombobox } from '@helixui/react';
 *
 * <HxCombobox />
 * ```
 */
export const HxCombobox = createComponent({
  tagName: 'hx-combobox',
  elementClass: HelixCombobox,
  react: React,
  events: {
    onHxShow: 'hx-show',
    onHxHide: 'hx-hide',
    onHxInput: 'hx-input',
    onHxClear: 'hx-clear',
    onHxChange: 'hx-change',
  },
  displayName: 'HxCombobox',
});

export default HxCombobox;
