/**
 * TypeScript types for HxCombobox React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxComboboxProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The visible label text for the combobox. */
  label?: string;
  /** Placeholder text shown in the input when no value is entered. */
  placeholder?: string;
  /** The current value of the combobox. */
  value?: string;
  /** Whether the combobox is required for form submission. */
  required?: boolean;
  /** Whether the combobox is disabled. */
  disabled?: boolean;
  /** The name used for form submission. */
  name?: string;
  /** Error message to display. When set, the field enters an error state. */
  error?: string;
  /** Help text displayed below the combobox for guidance. */
  helpText?: string;
  /** Size variant of the combobox. */
  size?: string;
  /** Whether multiple options can be selected. */
  multiple?: boolean;
  /** Whether the combobox shows a clear button when a value is set. */
  clearable?: boolean;
  /** Whether the combobox is in a loading state (shows spinner). */
  loading?: boolean;
  /** Debounce delay in milliseconds for the filter input event. */
  filterDebounce?: number;
  /** Accessible name for screen readers, if different from the visible label. */
  ariaLabel?: string | null;
  /** Text shown when no options match the current filter. */
  labelNoOptions?: string;
  /** Validation message shown when the field is required but empty. */
  labelRequired?: string;
  /** Generates the accessible label for multi-select chip remove buttons. */
  labelRemoveOption?: string;
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched when the listbox opens. */
  onHxShow?: (event: Event) => void;
  /** Dispatched when the listbox closes. */
  onHxHide?: (event: Event) => void;
  /** Dispatched on each keystroke as the user types. */
  onHxInput?: (event: Event) => void;
  /** Dispatched when the clear button is activated. */
  onHxClear?: (event: Event) => void;
  /** Dispatched when an option is selected. */
  onHxChange?: (event: Event) => void;
}
