'use client';
/**
 * React wrapper for <hx-structured-list> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixStructuredList } from '@helixui/library/components/hx-structured-list';

import type { HxStructuredListProps } from './types.js';

export type { HxStructuredListProps };

/**
 * Container for structured key-value data display. Renders as a list with
`role="list"` on the host and `role="listitem"` on each `hx-structured-list-row`,
preserving the list/listitem relationship across shadow DOM boundaries.
Use `hx-structured-list-row` as direct children.
 *
 * @example
 * ```tsx
 * import { HxStructuredList } from '@helixui/react';
 *
 * <HxStructuredList />
 * ```
 */
export const HxStructuredList = createComponent({
  tagName: 'hx-structured-list',
  elementClass: HelixStructuredList,
  react: React,
  events: {},
  displayName: 'HxStructuredList',
});

export default HxStructuredList;
