/**
 * TypeScript types for HxStructuredList React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxStructuredListProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Renders a border around the entire list. */
  bordered?: boolean;
  /** Reduces row padding for denser layouts. */
  condensed?: boolean;
  /** Alternates row background colors for easier scanning. */
  striped?: boolean;
}
