'use client';
/**
 * React wrapper for <hx-spinner> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSpinner } from '@helixui/library/components/hx-spinner';

import type { HxSpinnerProps } from './types.js';

export type { HxSpinnerProps };

/**
 * A circular loading indicator for inline and overlay loading states.
Purely visual — no slots. Announces loading state to screen readers via
`role="status"` and an `aria-label` (customizable via the `label` prop).

When used alongside visible loading text, set `decorative` to suppress
duplicate AT announcements.
 *
 * @example
 * ```tsx
 * import { HxSpinner } from '@helixui/react';
 *
 * <HxSpinner />
 * ```
 */
export const HxSpinner = createComponent({
  tagName: 'hx-spinner',
  elementClass: HelixSpinner,
  react: React,
  events: {},
  displayName: 'HxSpinner',
});

export default HxSpinner;
