'use client';
/**
 * React wrapper for <hx-spinner> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSpinner } from '@helixui/library/components/hx-spinner';

import type { HxSpinnerProps } from './types.js';

export type { HxSpinnerProps };

/**
 * A circular loading indicator for inline and overlay loading states.
Purely visual — no slots. Announces loading state to screen readers via
`role="status"` and an `aria-label` (customizable via the `label` prop).

When used alongside visible loading text, set `decorative` to suppress
duplicate AT announcements.

**WCAG 4.1.2 — `aria-busy` pattern for consumers:**
When this spinner indicates that a region of the page is loading, set
`aria-busy="true"` on the container element that wraps the loading content
and remove it (or set `aria-busy="false"`) once loading completes. This
communicates the loading state to assistive technologies at the region level,
complementing the spinner's own `role="status"` announcement.

```html
<section aria-busy="true" aria-label="Patient records">
  <hx-spinner label="Loading patient records"></hx-spinner>
</section>
```
 *
 * @example
 * ```tsx
 * import { HxSpinner } from '@helixui/react';
 *
 * <HxSpinner />
 * ```
 */
export const HxSpinner = createComponent({
  tagName: 'hx-spinner',
  elementClass: HelixSpinner,
  react: React,
  events: {},
  displayName: 'HxSpinner',
});

export default HxSpinner;
