/**
 * TypeScript types for HxSpinner React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxSpinnerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Size of the spinner. Accepts `SpinnerSize` token values ('sm' | 'md' | 'lg'),
or any valid CSS size string (e.g. "3rem", "48px") for custom dimensions.

The type is `SpinnerSize | string` which widens to `string` at the TypeScript
level — this is intentional to support CSS size overrides. Use `SpinnerSize`
values for standard sizing; custom strings bypass token-based scaling. */
  size?: 'sm' | 'md' | 'lg' | string;
  /** Visual variant of the spinner. */
  variant?: 'default' | 'primary' | 'inverted';
  /** Accessible label announced to screen readers. Defaults to "Loading".
Reflected as an attribute for Drupal/Twig compatibility. */
  label?: string;
  /** When true, the spinner is decorative and suppresses all ARIA announcements.
Use this when the spinner appears alongside visible loading text to prevent
duplicate announcements. Sets `role="presentation"` and removes `aria-label`. */
  decorative?: boolean;
}
