'use client';
/**
 * React wrapper for <hx-textarea> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTextarea } from '@helixui/library/components/hx-textarea';

import type { HxTextareaProps } from './types.js';

export type { HxTextareaProps };

/**
 * A multi-line text area component with label, validation, and form association.

Uses `aria-invalid` to convey error state and `aria-describedby` to link
error/help text to the textarea. Label association is handled through
`aria-labelledby` (for slotted labels) or the standard `<label for>` pattern.
Supports `aria-label` for cases where a visible label is not present.
Validation errors are announced via `role="alert"` (assertive live region).
 *
 * @example
 * ```tsx
 * import { HxTextarea } from '@helixui/react';
 *
 * <HxTextarea />
 * ```
 */
export const HxTextarea = createComponent({
  tagName: 'hx-textarea',
  elementClass: HelixTextarea,
  react: React,
  events: {
    onHxInput: 'hx-input',
    onHxChange: 'hx-change',
  },
  displayName: 'HxTextarea',
});

export default HxTextarea;
