/**
 * TypeScript types for HxTextarea React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTextareaProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The visible label text for the textarea. */
  label?: string;
  /** Placeholder text shown when the textarea is empty. */
  placeholder?: string;
  /** The current value of the textarea. */
  value?: string;
  /** Whether the textarea is required for form submission. */
  required?: boolean;
  /** Whether the textarea is disabled. */
  disabled?: boolean;
  /** Error message to display. When set, the textarea enters an error state. */
  error?: string;
  /** Help text displayed below the textarea for guidance. */
  helpText?: string;
  /** The name of the textarea, used for form submission. */
  name?: string;
  /** The number of visible text rows. Must be a positive integer (minimum 1).
Invalid values are clamped to the nearest valid value. */
  rows?: number;
  /** Minimum number of characters required. */
  minlength?: number | undefined;
  /** Maximum number of characters allowed. */
  maxlength?: number | undefined;
  /** Whether the textarea is read-only. Read-only fields are visible but
cannot be edited by the user. Common in healthcare for displaying
non-editable patient data inline with editable fields. */
  readonly?: boolean;
  /** Controls how the textarea can be resized. Use 'auto' for auto-grow behavior. */
  resize?: 'none' | 'vertical' | 'both' | 'auto';
  /** Whether to show a character count below the textarea. */
  showCount?: boolean;
  /** Validation message shown when the field is required but empty. */
  requiredMessage?: string;
  /** Accessible name for screen readers, if different from the visible label. */
  ariaLabel?: string | null;
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched on every keystroke as the user types. */
  onHxInput?: (event: Event) => void;
  /** Dispatched when the textarea loses focus after its value changed. */
  onHxChange?: (event: Event) => void;
}
