'use client';
/**
 * React wrapper for <hx-card> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixCard } from '@helixui/library/components/hx-card';

import type { HxCardProps } from './types.js';

export type { HxCardProps };

/**
 * A flexible card component for displaying grouped content.
 *
 * @example
 * ```tsx
 * import { HxCard } from '@helixui/react';
 *
 * <HxCard />
 * ```
 */
export const HxCard = createComponent({
  tagName: 'hx-card',
  elementClass: HelixCard,
  react: React,
  events: {
    onHxClick: 'hx-click',
  },
  displayName: 'HxCard',
});

export default HxCard;
