/**
 * TypeScript types for HxCard React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxCardProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual style variant of the card. */
  variant?: 'default' | 'featured' | 'compact';
  /** Elevation (shadow depth) of the card. */
  elevation?: 'flat' | 'raised' | 'floating';
  /** Optional URL. When set, the card becomes interactive (clickable)
and navigates to this URL on click.
Uses the hx-href attribute to avoid conflicting with the native HTML href attribute. */
  href?: string | undefined;
  /** Accessible label for interactive cards. Use this to provide a meaningful
description of the card's purpose rather than exposing the raw URL.
Only applies when hx-href is set. */
  label?: string | undefined;

  // Event callbacks
  /** Dispatched when an interactive card (with hx-href) is clicked. */
  onHxClick?: (event: Event) => void;
}
