'use client';
/**
 * React wrapper for <hx-help-text> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixHelpText } from '@helixui/library/components/hx-help-text';

import type { HxHelpTextProps } from './types.js';

export type { HxHelpTextProps };

/**
 * Standardized help/hint text displayed below form fields.
Used by hx-field as a consistent sub-component for guidance and validation messages.

Non-default variants render an inline icon alongside the text to satisfy
WCAG 1.4.1 (color is not the sole visual indicator). The `error` variant
uses `role="alert"` for immediate screen-reader announcement; `warning`
and `success` use `aria-live="polite"` for non-intrusive announcements.
 *
 * @example
 * ```tsx
 * import { HxHelpText } from '@helixui/react';
 *
 * <HxHelpText />
 * ```
 */
export const HxHelpText = createComponent({
  tagName: 'hx-help-text',
  elementClass: HelixHelpText,
  react: React,
  events: {},
  displayName: 'HxHelpText',
});

export default HxHelpText;
