/**
 * TypeScript types for HxHelpText React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxHelpTextProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual variant that determines the text color and icon.
Use `error` for validation errors, `warning` for cautions, `success` for confirmation. */
  variant?: 'default' | 'error' | 'warning' | 'success';
}
