'use client';
/**
 * React wrapper for <hx-tag> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTag } from '@helixui/library/components/hx-tag';

import type { HxTagProps } from './types.js';

export type { HxTagProps };

/**
 * A compact label for categorization, filtering, and selection.
 *
 * @example
 * ```tsx
 * import { HxTag } from '@helixui/react';
 *
 * <HxTag />
 * ```
 */
export const HxTag = createComponent({
  tagName: 'hx-tag',
  elementClass: HelixTag,
  react: React,
  events: {
    onHxRemove: 'hx-remove'
  },
  displayName: 'HxTag',
});

export default HxTag;
