/**
 * TypeScript types for HxTag React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTagProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual style variant of the tag. */
  variant?: 'default' | 'primary' | 'success' | 'warning' | 'danger';
  /** Size of the tag. */
  size?: 'sm' | 'md' | 'lg';
  /** Whether the tag uses fully rounded (pill) styling. */
  pill?: boolean;
  /** Whether the tag renders a dismiss button. */
  removable?: boolean;
  /** Whether the tag is disabled. When disabled, interactions are suppressed. */
  disabled?: boolean;

  // Event callbacks
  /** Dispatched when the user clicks the remove button. */
  onHxRemove?: (event: Event) => void;
}
