'use client';
/**
 * React wrapper for <hx-status-indicator> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixStatusIndicator } from '@helixui/library/components/hx-status-indicator';

import type { HxStatusIndicatorProps } from './types.js';

export type { HxStatusIndicatorProps };

/**
 * A colored dot/badge indicating system or entity health status.
Purely visual — no slots. Supports an animated pulse ring.

Uses `role="img"` with an auto-generated `aria-label` (e.g. "Status: Online").
When used decoratively alongside visible text that conveys the same status information
(e.g. "Provider is available"), set `aria-hidden="true"` on the host element to prevent
duplicate announcements to screen reader users. This is the recommended composition
pattern in healthcare dashboards.
 *
 * @example
 * ```tsx
 * import { HxStatusIndicator } from '@helixui/react';
 *
 * <HxStatusIndicator />
 * ```
 */
export const HxStatusIndicator = createComponent({
  tagName: 'hx-status-indicator',
  elementClass: HelixStatusIndicator,
  react: React,
  events: {},
  displayName: 'HxStatusIndicator',
});

export default HxStatusIndicator;
