/**
 * TypeScript types for HxStatusIndicator React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxStatusIndicatorProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The status to display. */
  status?: 'online' | 'offline' | 'away' | 'busy' | 'unknown';
  /** Size of the indicator dot. */
  size?: 'sm' | 'md' | 'lg';
  /** Whether to show an animated pulse ring around the dot.
Animation is suppressed when prefers-reduced-motion is active. */
  pulse?: boolean;
  /** Accessible label for the indicator. Defaults to "Status: {Status}".
Set aria-hidden="true" on the host when status is conveyed by adjacent text. */
  label?: string;
}
