'use client';
/**
 * React wrapper for <hx-menu> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixMenu } from '@helixui/library/components/hx-menu';

import type { HxMenuProps } from './types.js';

export type { HxMenuProps };

/**
 * A menu container that manages keyboard navigation over a list of menu items.
Use with `hx-menu-item` and `hx-menu-divider`.

Group 5b host-canonical: `role="menu"` lives on the **host** via
`_internals.role`. The host carries the announced surface so AT walks
`<hx-menu>` (role=menu) → slotted `<hx-menu-item>` (role=menuitem on host)
directly without two layers of indirection. Consumer-supplied
`aria-label` / `aria-labelledby` on the host are resolved via the shared
IDREF mirror; cross-shadow naming uses `ariaLabelledByElements` (modern)
with a flattened-string fallback (legacy).

Submenu coordination: when an `hx-menu-item` emits `hx-item-submenu-open`
or `hx-item-submenu-close`, the parent menu auto-handles the toggle by
calling `setSubmenuOpen()` on the item — UNLESS the consumer has called
`event.preventDefault()` on the bubbled event, signaling that they own the
submenu lifecycle. This matches APG-mandated behaviour while leaving an
opt-out for advanced consumers.
 *
 * @example
 * ```tsx
 * import { HxMenu } from '@helixui/react';
 *
 * <HxMenu />
 * ```
 */
export const HxMenu = createComponent({
  tagName: 'hx-menu',
  elementClass: HelixMenu,
  react: React,
  events: {
    onHxClose: 'hx-close',
    onHxSelect: 'hx-select',
  },
  displayName: 'HxMenu',
});

export default HxMenu;
