'use client';
/**
 * React wrapper for <hx-menu> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixMenu } from '@helixui/library/components/hx-menu';

import type { HxMenuProps } from './types.js';

export type { HxMenuProps };

/**
 * A menu container that manages keyboard navigation over a list of menu items.
Use with `hx-menu-item` and `hx-menu-divider`.
 *
 * @example
 * ```tsx
 * import { HxMenu } from '@helixui/react';
 *
 * <HxMenu />
 * ```
 */
export const HxMenu = createComponent({
  tagName: 'hx-menu',
  elementClass: HelixMenu,
  react: React,
  events: {
    onHxClose: 'hx-close',
    onHxSelect: 'hx-select',
  },
  displayName: 'HxMenu',
});

export default HxMenu;
