/**
 * TypeScript types for HxMenu React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxMenuProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Accessible label for the menu. Rendered as `aria-label` on the inner
`role="menu"` element when set. */
  label?: string;

  // Event callbacks
  /** Dispatched when Escape is pressed. */
  onHxClose?: (event: Event) => void;
  /** Dispatched when an item is selected. */
  onHxSelect?: (event: Event) => void;
}
