'use client';
/**
 * React wrapper for <hx-tabs> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTabs } from '@helixui/library/components/hx-tabs';

import type { HxTabsProps } from './types.js';

export type { HxTabsProps };

/**
 * A tabbed content organizer that manages a set of `<hx-tab>` and `<hx-tab-panel>` children.
Supports horizontal and vertical orientations, automatic and manual activation modes,
and full keyboard navigation per the ARIA Authoring Practices Guide.
 *
 * @example
 * ```tsx
 * import { HxTabs } from '@helixui/react';
 *
 * <HxTabs />
 * ```
 */
export const HxTabs = createComponent({
  tagName: 'hx-tabs',
  elementClass: HelixTabs,
  react: React,
  events: {
    onHxTabChange: 'hx-tab-change',
  },
  displayName: 'HxTabs',
});

export default HxTabs;
