/**
 * TypeScript types for HxTabs React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTabsProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The layout orientation of the tabs. */
  orientation?: 'horizontal' | 'vertical';
  /** Controls how keyboard navigation activates tabs.
In `automatic` mode, focus also activates the tab.
In `manual` mode, focus moves independently; Space or Enter activates. */
  activation?: 'manual' | 'automatic';
  /** Accessible label for the tablist. Rendered as `aria-label` on the tablist container.
Provide a brief description of what the tabs represent (e.g., "Patient record sections"). */
  label?: string;
  /** Gets or sets the zero-based index of the currently selected tab.
Setting this programmatically activates the tab at the given index. */
  selectedIndex?: number;

  // Event callbacks
  /** Dispatched when the active tab changes. */
  onHxTabChange?: (event: Event) => void;
}
