/**
 * TypeScript types for HxTabs React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTabsProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The layout orientation of the tabs. */
  orientation?: 'horizontal' | 'vertical';
  /** Controls how keyboard navigation activates tabs.
In `automatic` mode, focus also activates the tab.
In `manual` mode, focus moves independently; Space or Enter activates.

Group 5a default: `manual` — safer for healthcare patterns where panel
content may be heavy or announce updates via live regions. APG explicitly
allows both modes; manual avoids disorienting auto-activation when users
scan tabs with arrow keys. */
  activation?: 'manual' | 'automatic';
  /** Accessible label for the tablist. Drives the host `internals.ariaLabel`.
Provide a brief description of what the tabs represent (e.g., "Patient
record sections"). Consumer `aria-label` / `aria-labelledby` on the host
override this property when present. */
  label?: string;
  /** Gets or sets the zero-based index of the currently selected tab.
Setting this programmatically activates the tab at the given index.
Can also be set via the `selected-index` HTML attribute for server-side
pre-selection (e.g. Drupal Twig templates). */
  selectedIndex?: number;

  // Event callbacks
  /** Dispatched when the active tab changes. */
  onHxTabChange?: (event: Event) => void;
}
