'use client';
/**
 * React wrapper for <hx-carousel> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixCarousel } from '@helixui/library/components/hx-carousel';

import type { HxCarouselProps } from './types.js';

export type { HxCarouselProps };

/**
 * A scrollable carousel/slider for images or content slides.
 *
 * @example
 * ```tsx
 * import { HxCarousel } from '@helixui/react';
 *
 * <HxCarousel />
 * ```
 */
export const HxCarousel = createComponent({
  tagName: 'hx-carousel',
  elementClass: HelixCarousel,
  react: React,
  events: {
    onHxSlideChange: 'hx-slide-change'
  },
  displayName: 'HxCarousel',
});

export default HxCarousel;
