/**
 * TypeScript types for HxCarousel React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxCarouselProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Accessible label identifying this carousel to assistive technology.
When multiple carousels appear on the same page, each must have a unique label. */
  label?: string;
  /** Whether the carousel wraps around from last to first slide and vice-versa. */
  loop?: boolean;
  /** Whether the carousel auto-advances slides.
Automatically pauses on hover, focus, and when prefers-reduced-motion is active. */
  autoplay?: boolean;
  /** Milliseconds between auto-advance transitions. */
  autoplayInterval?: number;
  /** Number of slides visible at once. */
  slidesPerPage?: number;
  /** Number of slides to advance per navigation action. */
  slidesPerMove?: number;
  /** Scroll axis of the carousel. */
  orientation?: 'horizontal' | 'vertical';
  /** Whether click-drag scrolling is enabled. */
  mouseDragging?: boolean;
  /** Accessible label for the previous slide button. */
  labelPrevSlide?: string;
  /** Accessible label for the next slide button. */
  labelNextSlide?: string;
  /** Accessible label for the autoplay pause button. */
  labelPauseAutoplay?: string;
  /** Accessible label for the autoplay play button. */
  labelPlayAutoplay?: string;

  // Event callbacks
  /** Dispatched when the active slide changes. */
  onHxSlideChange?: (event: Event) => void;
}
