'use client';
/**
 * React wrapper for <hx-split-panel> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSplitPanel } from '@helixui/library/components/hx-split-panel';

import type { HxSplitPanelProps } from './types.js';

export type { HxSplitPanelProps };

/**
 * A resizable two-pane layout with a draggable divider.
 *
 * @example
 * ```tsx
 * import { HxSplitPanel } from '@helixui/react';
 *
 * <HxSplitPanel />
 * ```
 */
export const HxSplitPanel = createComponent({
  tagName: 'hx-split-panel',
  elementClass: HelixSplitPanel,
  react: React,
  events: {
    onHxReposition: 'hx-reposition',
  },
  displayName: 'HxSplitPanel',
});

export default HxSplitPanel;
