/**
 * TypeScript types for HxSplitPanel React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxSplitPanelProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Position of the divider as a percentage (0–100) of the start panel. */
  position?: number;
  /** Position of the divider in pixels (alternative to `position`).
When set, takes precedence over `position` until the host is measured. */
  positionInPixels?: number | undefined;
  /** Orientation of the split. */
  orientation?: 'horizontal' | 'vertical';
  /** Minimum position as a percentage (0–100). Prevents full collapse of start panel. */
  min?: number;
  /** Maximum position as a percentage (0–100). Prevents full expansion of start panel. */
  max?: number;
  /** Snap points as an array of percentages. The divider snaps to the
nearest point within a 5% threshold.
Accepts JSON array string in HTML: snap="[25, 50, 75]" */
  snap?: number[];
  /** When true, the divider cannot be dragged. */
  disabled?: boolean;
  /** When true, collapse/expand buttons appear on the divider. */
  collapsible?: boolean;
  /** Which panel is collapsed: 'start', 'end', or null (not collapsed). */
  collapsed?: 'start' | 'end' | null;

  // Event callbacks
  /** Fired when the divider is moved. Detail: `{ position: number }`. */
  onHxReposition?: (event: Event) => void;
}
