'use client';
/**
 * React wrapper for <hx-th> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTableHeader } from '@helixui/library/components/hx-table';

import type { HxThProps } from './types.js';

export type { HxThProps };

/**
 * Semantic table header cell. Must be a child of `hx-tr`.
Supports sortable columns with accessible sort state.
 *
 * @example
 * ```tsx
 * import { HxTh } from '@helixui/react';
 *
 * <HxTh />
 * ```
 */
export const HxTh = createComponent({
  tagName: 'hx-th',
  elementClass: HelixTableHeader,
  react: React,
  events: {
    onHxSort: 'hx-sort'
  },
  displayName: 'HxTh',
});

export default HxTh;
