/**
 * TypeScript types for HxTh React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxThProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** When true, the header renders a sort button and emits `hx-sort` on activation. */
  sortable?: boolean;
  /** Current sort direction. Reflected for CSS targeting. */
  sortDirection?: 'asc' | 'desc' | 'none';
  /** The `scope` attribute for the underlying `<th>` element. */
  scope?: 'col' | 'row' | 'colgroup' | 'rowgroup';
  /** Number of columns this header spans. */
  colspan?: number;
  /** Number of rows this header spans. */
  rowspan?: number;

  // Event callbacks
  /** Dispatched when a sortable header is activated. */
  onHxSort?: (event: Event) => void;
}
