'use client';
/**
 * React wrapper for <hx-slider> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSlider } from '@helixui/library/components/hx-slider';

import type { HxSliderProps } from './types.js';

export type { HxSliderProps };

/**
 * A range slider component for selecting a numeric value within a min/max boundary.
Supports tick marks, value display, range labels, and native form participation
via ElementInternals.

The native `<input type="range">` receives `role="slider"` with `aria-valuenow`,
`aria-valuemin`, and `aria-valuemax`. Label association uses `aria-labelledby`
when a label is present, or `aria-label` as a fallback. Help text is linked via
`aria-describedby`. Keyboard navigation follows the native range behavior:
Arrow keys increment/decrement by step, Home jumps to min, End jumps to max.
 *
 * @example
 * ```tsx
 * import { HxSlider } from '@helixui/react';
 *
 * <HxSlider />
 * ```
 */
export const HxSlider = createComponent({
  tagName: 'hx-slider',
  elementClass: HelixSlider,
  react: React,
  events: {
    onHxInput: 'hx-input',
    onHxChange: 'hx-change'
  },
  displayName: 'HxSlider',
});

export default HxSlider;
