/**
 * TypeScript types for HxSlider React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxSliderProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The name submitted with the form. */
  name?: string;
  /** The current numeric value of the slider. */
  value?: number;
  /** The minimum allowed value. */
  min?: number;
  /** The maximum allowed value. */
  max?: number;
  /** The stepping interval between values. */
  step?: number;
  /** Whether the slider is disabled. */
  disabled?: boolean;
  /** The visible label text for the slider. */
  label?: string;
  /** Help text displayed below the slider for guidance. */
  helpText?: string;
  /** When true, the current value is shown next to the label. */
  showValue?: boolean;
  /** When true, tick marks are rendered at each step interval. */
  showTicks?: boolean;
  /** The size variant of the slider. */
  size?: 'sm' | 'md' | 'lg';
  /** Human-readable text alternative for the current value, announced by screen readers
instead of the numeric value. For example, on a pain scale: "7 — Moderate-Severe". */
  valueText?: string;
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched continuously while the user drags. */
  onHxInput?: (event: Event) => void;
  /** Dispatched when the user releases the thumb. */
  onHxChange?: (event: Event) => void;
}
