'use client';
/**
 * React wrapper for <hx-link> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixLink } from '@helixui/library/components/hx-link';

import type { HxLinkProps } from './types.js';

export type { HxLinkProps };

/**
 * A semantic hyperlink component with accessibility-first design.
Renders a native `<a>` element for enabled state and a `<span>` for
disabled state with full keyboard and screen reader support.
 *
 * @example
 * ```tsx
 * import { HxLink } from '@helixui/react';
 *
 * <HxLink />
 * ```
 */
export const HxLink = createComponent({
  tagName: 'hx-link',
  elementClass: HelixLink,
  react: React,
  events: {
    onHxClick: 'hx-click',
  },
  displayName: 'HxLink',
});

export default HxLink;
