/**
 * TypeScript types for HxLink React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxLinkProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The URL the link points to. */
  href?: string | undefined;
  /** Where to display the linked URL (_self, _blank, etc.).
When set to "_blank", automatically adds rel="noopener noreferrer"
and shows an external-link indicator. */
  target?: string | undefined;
  /** Visual style variant of the link. */
  variant?: string;
  /** Whether the link is disabled. Renders a span instead of an anchor.
The disabled span is keyboard-focusable (tabindex="0") and announces
as a disabled link to screen readers. */
  disabled?: boolean;
  /** Prompts the user to download the linked URL. When set to a string,
the value is used as the suggested filename. */
  download?: string | undefined;
  /** Relationship between the current document and the linked URL.
Automatically set to "noopener noreferrer" when target="_blank". */
  rel?: string | undefined;

  // Event callbacks
  /** Dispatched when the link is clicked and is not disabled. */
  onHxClick?: (event: Event) => void;
}
