'use client';
/**
 * React wrapper for <hx-thead> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTableHead } from '@helixui/library/components/hx-table';

import type { HxTheadProps } from './types.js';

export type { HxTheadProps };

/**
 * Semantic table head section. Must be a direct child of `hx-table`.
Contains `hx-tr` rows with `hx-th` header cells.
 *
 * @example
 * ```tsx
 * import { HxThead } from '@helixui/react';
 *
 * <HxThead />
 * ```
 */
export const HxThead = createComponent({
  tagName: 'hx-thead',
  elementClass: HelixTableHead,
  react: React,
  events: {},
  displayName: 'HxThead',
});

export default HxThead;
