'use client';
/**
 * React wrapper for <hx-overflow-menu> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixOverflowMenu } from '@helixui/library/components/hx-overflow-menu';

import type { HxOverflowMenuProps } from './types.js';

export type { HxOverflowMenuProps };

/**
 * An overflow menu (kebab/meatball menu) that reveals hidden actions via a
floating panel. Composed from a trigger button and a slotted menu panel.
 *
 * @example
 * ```tsx
 * import { HxOverflowMenu } from '@helixui/react';
 *
 * <HxOverflowMenu />
 * ```
 */
export const HxOverflowMenu = createComponent({
  tagName: 'hx-overflow-menu',
  elementClass: HelixOverflowMenu,
  react: React,
  events: {
    onHxShow: 'hx-show',
    onHxHide: 'hx-hide',
    onHxSelect: 'hx-select',
  },
  displayName: 'HxOverflowMenu',
});

export default HxOverflowMenu;
