/**
 * TypeScript types for HxOverflowMenu React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxOverflowMenuProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Preferred placement of the floating panel relative to the trigger. */
  placement?:
    | string
    | 'top'
    | 'top-start'
    | 'top-end'
    | 'bottom'
    | 'bottom-start'
    | 'bottom-end'
    | 'left'
    | 'left-start'
    | 'left-end'
    | 'right'
    | 'right-start'
    | 'right-end';
  /** Size of the trigger button. */
  size?: 'sm' | 'md' | 'lg';
  /** Whether the trigger button is disabled. */
  disabled?: boolean;
  /** Icon orientation: vertical (kebab ⋮) or horizontal (meatball ···). */
  icon?: 'vertical' | 'horizontal';
  /** Accessible label for the trigger button. Used as a fallback when no
consumer-supplied `aria-label` / `aria-labelledby` is present on the
host. Consumer host attributes win in the AccName 1.2 §4.3.1 cascade. */
  label?: string;
  /** Accessible label for the menu panel. Reflected as `label-menu`. */
  labelMenu?: string;

  // Event callbacks
  /** Dispatched when the panel opens. */
  onHxShow?: (event: Event) => void;
  /** Dispatched when the panel closes. */
  onHxHide?: (event: Event) => void;
  /** Dispatched when a menu item is selected. */
  onHxSelect?: (event: Event) => void;
}
