'use client';
/**
 * React wrapper for <hx-radio-group> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixRadioGroup } from '@helixui/library/components/hx-radio-group';

import type { HxRadioGroupProps } from './types.js';

export type { HxRadioGroupProps };

/**
 * A form-associated radio group that manages a set of `<hx-radio>` children.
 *
 * @example
 * ```tsx
 * import { HxRadioGroup } from '@helixui/react';
 *
 * <HxRadioGroup />
 * ```
 */
export const HxRadioGroup = createComponent({
  tagName: 'hx-radio-group',
  elementClass: HelixRadioGroup,
  react: React,
  events: {
    onHxChange: 'hx-change',
    onHxRadioSelect: 'hx-radio-select',
  },
  displayName: 'HxRadioGroup',
});

export default HxRadioGroup;
