/**
 * TypeScript types for HxRadioGroup React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxRadioGroupProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The selected radio's value. */
  value?: string;
  /** The name used for form submission. */
  name?: string;
  /** The fieldset legend/label text. */
  label?: string;
  /** Whether a selection is required for form submission. */
  required?: boolean;
  /** Whether the entire group is disabled. */
  disabled?: boolean;
  /** Error message to display. When set, the group enters an error state. */
  error?: string;
  /** Help text displayed below the group for guidance. */
  helpText?: string;
  /** Layout orientation of the radio items. */
  orientation?: 'vertical' | 'horizontal';
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched when the selected radio changes. */
  onHxChange?: (event: Event) => void;
  /** Internal event dispatched by `hx-radio` when selected; consumed by the group. */
  onHxRadioSelect?: (event: Event) => void;
}
