import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { hxStyleScopeStyles } from './hx-style-scope.styles.js';
import { injectLightStyles } from '../../utilities/injectLightStyles.js';

/**
 * A transparent wrapper component that injects scoped light DOM styles for its
 * slotted children. Designed for use in Drupal Twig templates where slotted
 * content lives in the light DOM and cannot inherit Shadow DOM styles.
 *
 * On connection, the component:
 * 1. Sets `data-hx-styled` on itself so scoped CSS selectors resolve correctly.
 * 2. Calls `injectLightStyles` to inject a `<style>` into `document.head` — once
 *    per component type, deduplicated via `lightStyleRegistry`.
 *
 * The element renders as `display: contents` so it does not affect layout.
 *
 * @summary Scoped light DOM style injection wrapper for Drupal-slotted content.
 *
 * @tag hx-style-scope
 *
 * @slot - Default slot for any light DOM content that should receive scoped styles.
 *
 * @example
 * ```html
 * <hx-style-scope component="hx-card">
 *   <p>This paragraph will receive hx-card light DOM styles.</p>
 * </hx-style-scope>
 * ```
 *
 * @example Drupal Twig usage via macro
 * ```twig
 * {% import '@helix/hx-style-scope.macro.twig' as hx %}
 * {{ hx.scope('hx-card', content) }}
 * ```
 */
@customElement('hx-style-scope')
export class HxStyleScope extends LitElement {
  static override styles = [hxStyleScopeStyles];

  /**
   * The component tag name whose light DOM styles should be injected.
   * Must match a registered component name (e.g. `'hx-card'`).
   *
   * When set, the element also applies `data-hx-styled` to itself so that
   * scoped CSS selectors generated by `generateScopedSelectors` resolve
   * correctly against slotted child elements.
   *
   * @attr component
   */
  @property({ type: String, reflect: true })
  component: string = '';

  /**
   * The CSS to inject as scoped light DOM styles. When provided alongside
   * `component`, this CSS will be scoped under `[data-hx-styled="component"]`
   * and injected into `document.head` (once per component type).
   *
   * If omitted, `injectLightStyles` is still called but with an empty string,
   * which is a no-op for actual style injection.
   *
   * @attr light-css
   */
  @property({ type: String, attribute: 'light-css' })
  lightCss: string = '';

  override connectedCallback(): void {
    super.connectedCallback();
    this._applyScope();
  }

  override updated(changed: Map<string, unknown>): void {
    if (changed.has('component') || changed.has('lightCss')) {
      this._applyScope();
    }
  }

  /**
   * Applies the `data-hx-styled` attribute and triggers style injection.
   * Called on connect and whenever `component` or `lightCss` changes.
   */
  private _applyScope(): void {
    if (!this.component) return;

    // Set the scoping attribute so CSS selectors from generateScopedSelectors work.
    this.setAttribute('data-hx-styled', this.component);

    if (this.lightCss) {
      injectLightStyles(this.component, this.lightCss);
    }
  }

  override render() {
    return html`<slot></slot>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'hx-style-scope': HxStyleScope;
  }
}
