'use client';
/**
 * React wrapper for <hx-action-bar> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixActionBar } from '@helixui/library/components/hx-action-bar';

import type { HxActionBarProps } from './types.js';

export type { HxActionBarProps };

/**
 * A horizontal toolbar container for grouping related action buttons and controls.
Implements the ARIA toolbar pattern with roving tabindex keyboard navigation.
 *
 * @example
 * ```tsx
 * import { HxActionBar } from '@helixui/react';
 *
 * <HxActionBar />
 * ```
 */
export const HxActionBar = createComponent({
  tagName: 'hx-action-bar',
  elementClass: HelixActionBar,
  react: React,
  events: {},
  displayName: 'HxActionBar',
});

export default HxActionBar;
