/**
 * TypeScript types for HxActionBar React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxActionBarProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Size of the action bar — propagated as a data attribute to slotted children. */
  size?: 'sm' | 'md' | 'lg';
  /** Visual variant controlling the bar background. */
  variant?: 'default' | 'outlined' | 'filled';
  /** Position and sticky behavior of the action bar.
- `top` — normal flow (default)
- `sticky` — sticks to the top of the scroll container; add `scroll-padding-top` to the
  scroll container equal to the bar height to prevent anchor targets from scrolling behind it
- `bottom` — sticks to the bottom of the scroll container with iOS safe-area-inset support */
  position?: 'top' | 'bottom' | 'sticky';
  /** When true, the bar sticks to the top of its scroll container. */
  sticky?: boolean;
  /** Accessible label for the toolbar.
Required when multiple toolbars appear on the same page.

Accepts both `accessible-label` and the standard `aria-label` HTML attribute.
The `accessible-label` attribute takes precedence when both are set.

Previously this was exposed as the `ariaLabel` JS property, which shadowed
the native `HTMLElement.ariaLabel`. That shadowing is removed; use
`accessibleLabel` or the HTML attributes instead. */
  accessibleLabel?: string;
}
