'use client';
/**
 * React wrapper for <hx-skeleton> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSkeleton } from '@helixui/library/components/hx-skeleton';

import type { HxSkeletonProps } from './types.js';

export type { HxSkeletonProps };

/**
 * An animated placeholder used to indicate loading content.
Purely decorative — hidden from assistive technology.
Supports a `loaded` state that announces content availability to screen readers.
 *
 * @example
 * ```tsx
 * import { HxSkeleton } from '@helixui/react';
 *
 * <HxSkeleton />
 * ```
 */
export const HxSkeleton = createComponent({
  tagName: 'hx-skeleton',
  elementClass: HelixSkeleton,
  react: React,
  events: {
    onHxLoaded: 'hx-loaded',
  },
  displayName: 'HxSkeleton',
});

export default HxSkeleton;
