/**
 * TypeScript types for HxSkeleton React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxSkeletonProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Shape variant of the skeleton placeholder. */
  variant?: 'text' | 'circle' | 'rect' | 'button' | 'paragraph';
  /** CSS width of the skeleton. Accepts any valid CSS width value. */
  width?: string;
  /** CSS height of the skeleton. Accepts any valid CSS height value.
Defaults vary by variant when not set. */
  height?: string | undefined;
  /** Whether the shimmer wave animation is active.
Set to false to display a static skeleton. */
  animated?: boolean;
  /** When true, hides the skeleton and dispatches an `hx-loaded` event.
Consumers should pair this with an external `aria-live` region to
announce loading completion to assistive technology users. */
  loaded?: boolean;

  // Event callbacks
  /** Dispatched when `loaded` transitions to `true`. Consumers should use this event to update an external `aria-live` region announcing content availability. */
  onHxLoaded?: (event: Event) => void;
}
