'use client';
/**
 * React wrapper for <hx-carousel-item> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixCarouselItem } from '@helixui/library/components/hx-carousel';

import type { HxCarouselItemProps } from './types.js';

export type { HxCarouselItemProps };

/**
 * A wrapper for individual carousel slides.
 *
 * @example
 * ```tsx
 * import { HxCarouselItem } from '@helixui/react';
 *
 * <HxCarouselItem />
 * ```
 */
export const HxCarouselItem = createComponent({
  tagName: 'hx-carousel-item',
  elementClass: HelixCarouselItem,
  react: React,
  events: {},
  displayName: 'HxCarouselItem',
});

export default HxCarouselItem;
