/**
 * TypeScript types for HxCarouselItem React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxCarouselItemProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The 0-based index of this slide within the carousel. Set by hx-carousel. */
  slideIndex?: number;
  /** Total number of slides in the carousel. Set by hx-carousel. */
  totalSlides?: number;
}
