'use client';
/**
 * React wrapper for <hx-menu-divider> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixMenuDivider } from '@helixui/library/components/hx-menu';

import type { HxMenuDividerProps } from './types.js';

export type { HxMenuDividerProps };

/**
 * A visual separator for grouping items within an `hx-menu`.
 *
 * @example
 * ```tsx
 * import { HxMenuDivider } from '@helixui/react';
 *
 * <HxMenuDivider />
 * ```
 */
export const HxMenuDivider = createComponent({
  tagName: 'hx-menu-divider',
  elementClass: HelixMenuDivider,
  react: React,
  events: {},
  displayName: 'HxMenuDivider',
});

export default HxMenuDivider;
