'use client';
/**
 * React wrapper for <hx-phi-field> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixPhiField } from '@helixui/library/components/hx-phi-field';

import type { HxPhiFieldProps } from './types.js';

export type { HxPhiFieldProps };

/**
 * HIPAA-compliant field component for rendering masked Protected Health Information (PHI).
PHI is masked by default and only rendered to the DOM when explicitly revealed. Access
events are fired on reveal, hide, and clipboard auto-clear for audit trail purposes.
 *
 * @example
 * ```tsx
 * import { HxPhiField } from '@helixui/react';
 *
 * <HxPhiField />
 * ```
 */
export const HxPhiField = createComponent({
  tagName: 'hx-phi-field',
  elementClass: HelixPhiField,
  react: React,
  events: {
    onHxPhiAccess: 'hx-phi-access'
  },
  displayName: 'HxPhiField',
});

export default HxPhiField;
