/**
 * TypeScript types for HxPhiField React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxPhiFieldProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The Protected Health Information value to display or mask.
Must be set via the JavaScript property (`element.data = "..."`) — not as an HTML attribute.
Setting PHI as an HTML attribute exposes it in the DOM and browser caches (HIPAA violation). */
  data?: string;
  /** The type of PHI field. Controls the masking pattern applied. */
  fieldType?: 'ssn' | 'mrn' | 'dob' | 'insurance';
  /** Identifier used in audit events. Falls back to the element's id attribute. */
  fieldId?: string;
  /** Milliseconds after clipboard write before the clipboard is automatically cleared.
Defaults to 30000 (30 seconds). */
  clipboardTimeout?: number;
  /** Accessible label describing the PHI field. Used as a prefix in screen reader
announcements (e.g., "Social Security Number is masked"). */
  label?: string;
  /** Seconds of inactivity after reveal before PHI is automatically re-masked.
Prevents PHI from remaining visible indefinitely when a clinician walks away.
Set to 0 to disable auto-hide. Defaults to 60 seconds. */
  autoHideDelay?: number;
  /** When set, disables all interaction with the field and prevents reveal. */
  disabled?: boolean;
  /** Opt-in fail-closed DETECTOR for PHI exposed via the `data` HTML attribute
(FS-029). Defaults to `false`, which preserves the existing best-effort
silent-rescue behavior and is fully backward compatible.

**This is a detector, not a cure.** By the time `connectedCallback` runs,
a server-rendered page has already serialized the raw PHI into the HTML
sent over the wire — the leak happened server-side and cannot be undone
client-side. Stripping the attribute here only cleans up the *live* DOM.

When `strict` is `true` and a `data` attribute is detected, the component
still strips the attribute first (so PHI leaves the live DOM), then fails
LOUDLY instead of silently: it dispatches an `hx-phi-access` event with
`action: 'attribute-exposure-refused'` for the audit trail, and — in
development/test/CI builds (`import.meta.env.DEV`) — logs a `console.error`
so the SSR misconfiguration surfaces during testing rather than shipping
unnoticed. It does NOT throw: an exception from `connectedCallback` is
reported as an uncaught browser error and aborts the callback, which would
destabilise a live field. Production builds emit nothing to the console (the
`import.meta.env.DEV` branch is tree-shaken away), so an opted-in app still
degrades to the audit-event signal rather than logging for end users.

Its value is surfacing the defect (an upstream SSR `data` attribute) before
it reaches production — not preventing the server-side serialization, which
already occurred. */
  strict?: boolean;

  // Event callbacks
  /** Fired on reveal, hide, auto-hide, clipboard-clear, clipboard-clear-failed, and attribute-exposure-refused actions. Contains audit metadata only — never raw PHI. Dispatched with `composed: true` to cross shadow boundaries for application-level audit listeners. */
  onHxPhiAccess?: (event: Event) => void;
}
