/**
 * TypeScript types for HxPhiField React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxPhiFieldProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The Protected Health Information value to display or mask. */
  data?: string;
  /** The type of PHI field. Controls the masking pattern applied. */
  fieldType?: 'ssn' | 'mrn' | 'dob' | 'insurance';
  /** Identifier used in audit events. Falls back to the element's id attribute. */
  fieldId?: string;
  /** Milliseconds after clipboard write before the clipboard is automatically cleared.
Defaults to 30000 (30 seconds). */
  clipboardTimeout?: number;

  // Event callbacks
  /** Fired on reveal, hide, and clipboard auto-clear. */
  onHxPhiAccess?: (event: Event) => void;
}
