/**
 * TypeScript types for HxPhiField React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxPhiFieldProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The Protected Health Information value to display or mask.
Must be set via the JavaScript property (`element.data = "..."`) — not as an HTML attribute.
Setting PHI as an HTML attribute exposes it in the DOM and browser caches (HIPAA violation). */
  data?: string;
  /** The type of PHI field. Controls the masking pattern applied. */
  fieldType?: 'ssn' | 'mrn' | 'dob' | 'insurance';
  /** Identifier used in audit events. Falls back to the element's id attribute. */
  fieldId?: string;
  /** Milliseconds after clipboard write before the clipboard is automatically cleared.
Defaults to 30000 (30 seconds). */
  clipboardTimeout?: number;
  /** Accessible label describing the PHI field. Used as a prefix in screen reader
announcements (e.g., "Social Security Number is masked"). */
  label?: string;
  /** Seconds of inactivity after reveal before PHI is automatically re-masked.
Prevents PHI from remaining visible indefinitely when a clinician walks away.
Set to 0 to disable auto-hide. Defaults to 60 seconds. */
  autoHideDelay?: number;
  /** When set, disables all interaction with the field and prevents reveal. */
  disabled?: boolean;

  // Event callbacks
  /** Fired on reveal, hide, auto-hide, clipboard-clear, and clipboard-clear-failed actions. Contains audit metadata only — never raw PHI. Dispatched with `composed: true` to cross shadow boundaries for application-level audit listeners. */
  onHxPhiAccess?: (event: Event) => void;
}
