'use client';
/**
 * React wrapper for <hx-list-item> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixListItem } from '@helixui/library/components/hx-list';

import type { HxListItemProps } from './types.js';

export type { HxListItemProps };

/**
 * A rich list item for use inside `hx-list`.

Group 7 host-canonical: `role="option"` (interactive listbox mode) is
mirrored onto the **host** via `_internals.role` AND the legacy
setAttribute('role',...) path. The dual-surface pattern preserves the
existing imperative host-attribute behaviour (so consumers querying
`host.getAttribute('role')` still work) while adding cross-shadow IDREF
wiring through `internals.ariaLabelledByElements` for engines that
support it.
 *
 * @example
 * ```tsx
 * import { HxListItem } from '@helixui/react';
 *
 * <HxListItem />
 * ```
 */
export const HxListItem = createComponent({
  tagName: 'hx-list-item',
  elementClass: HelixListItem,
  react: React,
  events: {
    onHxListItemClick: 'hx-list-item-click',
  },
  displayName: 'HxListItem',
});

export default HxListItem;
