'use client';
/**
 * React wrapper for <hx-list-item> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixListItem } from '@helixui/library/components/hx-list';

import type { HxListItemProps } from './types.js';

export type { HxListItemProps };

/**
 * A rich list item for use inside `hx-list`.
 *
 * @example
 * ```tsx
 * import { HxListItem } from '@helixui/react';
 *
 * <HxListItem />
 * ```
 */
export const HxListItem = createComponent({
  tagName: 'hx-list-item',
  elementClass: HelixListItem,
  react: React,
  events: {
    onHxListItemClick: 'hx-list-item-click'
  },
  displayName: 'HxListItem',
});

export default HxListItem;
