/**
 * TypeScript types for HxListItem React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxListItemProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Whether the item is disabled. Prevents interaction. */
  disabled?: boolean;
  /** Whether the item is selected (used in interactive mode). */
  selected?: boolean;
  /** When set, renders the item as a link (only in non-interactive variants). */
  href?: string | undefined;
  /** The value associated with this item (used with hx-select). */
  value?: string | undefined;
  /** Set by the parent hx-list to indicate this item is part of an interactive listbox.
Controls CSS styling and ARIA role via host attributes. */
  interactive?: boolean;
  /** Item type for description list variant. Use 'term' for <dt> and 'definition' for <dd>. */
  type?: 'default' | 'term' | 'definition';

  // Event callbacks
  /** Dispatched when the item is clicked and not disabled. */
  onHxListItemClick?: (event: Event) => void;
}
