'use client';
/**
 * React wrapper for <hx-avatar> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixAvatar } from '@helixui/library/components/hx-avatar';

import type { HxAvatarProps } from './types.js';

export type { HxAvatarProps };

/**
 * A user avatar component that displays an image, initials, or a fallback icon.
Supports a badge slot for status indicator overlays.
 *
 * @example
 * ```tsx
 * import { HxAvatar } from '@helixui/react';
 *
 * <HxAvatar />
 * ```
 */
export const HxAvatar = createComponent({
  tagName: 'hx-avatar',
  elementClass: HelixAvatar,
  react: React,
  events: {},
  displayName: 'HxAvatar',
});

export default HxAvatar;
