/**
 * TypeScript types for HxAvatar React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxAvatarProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Image URL. When provided and successfully loaded, displays the image. */
  src?: string | undefined;
  /** Accessible label for the image. Required when `src` is provided.
Used as the container's aria-label in image mode. */
  alt?: string;
  /** Human-readable accessible name for non-image states (initials, fallback icon).
In healthcare contexts, provide the full person name (e.g., "Dr. Jane Doe") rather than
relying on raw initials, which screen readers announce as individual letters.
When set, takes precedence over raw initials and the generic "Avatar" fallback. */
  label?: string;
  /** Fallback initials text displayed when no image is available. */
  initials?: string;
  /** Size variant of the avatar. */
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /** Shape variant of the avatar. */
  shape?: 'circle' | 'square';
}
