'use client';
/**
 * React wrapper for <hx-container> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixContainer } from '@helixui/library/components/hx-container';

import type { HxContainerProps } from './types.js';

export type { HxContainerProps };

/**
 * A layout container that constrains content width and provides
consistent vertical spacing and horizontal gutters.

Uses a two-layer model: the outer host spans full width (background,
vertical padding), while the inner wrapper constrains max-width,
centers content, and applies horizontal gutters.

## Accessibility

`hx-container` is a purely visual layout primitive with no semantic meaning.
It carries no ARIA role and is intentionally transparent to assistive
technologies. Screen readers announce the container's children directly,
not the container itself.

The inner wrapper always centers content horizontally (via `margin: auto`).
This is by design for page-layout use cases. If you need non-centered
alignment at a specific breakpoint, override `margin-left` and
`margin-right` on `::part(inner)` from your stylesheet.
 *
 * @example
 * ```tsx
 * import { HxContainer } from '@helixui/react';
 *
 * <HxContainer />
 * ```
 */
export const HxContainer = createComponent({
  tagName: 'hx-container',
  elementClass: HelixContainer,
  react: React,
  events: {},
  displayName: 'HxContainer',
});

export default HxContainer;
