/**
 * TypeScript types for HxContainer React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxContainerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Controls the max-width of the inner content wrapper. */
  width?: 'full' | 'content' | 'narrow' | 'sm' | 'md' | 'lg' | 'xl';
  /** Vertical padding applied to the outer wrapper. */
  padding?: 'none' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';
}
