'use client';
/**
 * React wrapper for <hx-tree-view> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTreeView } from '@helixui/library/components/hx-tree-view';

import type { HxTreeViewProps } from './types.js';

export type { HxTreeViewProps };

/**
 * A hierarchical tree component for navigating nested data structures.
Used in healthcare applications for org charts, ICD-10 code hierarchies, and department navigation.

Implements WAI-ARIA tree view pattern with `role="tree"` on the container
and `role="treeitem"` on each item. Supports `aria-label` via the `label` property
for screen reader identification. Full keyboard navigation: Arrow keys for movement,
Enter/Space for selection, Home/End for first/last item.

## Scale Limits

This component renders all tree items simultaneously in the DOM. It is suitable for
trees with up to ~500 visible items. For large taxonomies (e.g., ICD-10 with 70,000+
codes), use async/lazy loading: only render top-level nodes initially and populate
child nodes on `hx-select` or expand events. The component exposes the `expanded`
property on `hx-tree-item` for programmatic control of subtrees, enabling consumer-level
virtualization strategies without requiring changes to this component.
 *
 * @example
 * ```tsx
 * import { HxTreeView } from '@helixui/react';
 *
 * <HxTreeView />
 * ```
 */
export const HxTreeView = createComponent({
  tagName: 'hx-tree-view',
  elementClass: HelixTreeView,
  react: React,
  events: {
    onHxSelect: 'hx-select'
  },
  displayName: 'HxTreeView',
});

export default HxTreeView;
