'use client';
/**
 * React wrapper for <hx-tree-view> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTreeView } from '@helixui/library/components/hx-tree-view';

import type { HxTreeViewProps } from './types.js';

export type { HxTreeViewProps };

/**
 * A hierarchical tree component for navigating nested data structures.
Used in healthcare applications for org charts, ICD-10 code hierarchies, and department navigation.

Group 5c host-canonical: `role="tree"` lives on the **host** via
`_internals.role` on the modern path. The host carries the announced
surface so AT walks `<hx-tree-view>` (role=tree) → slotted
`<hx-tree-item>` (role=treeitem on host) directly without two layers of
indirection. Consumer-supplied `aria-label` / `aria-labelledby` on the
host are resolved via the shared IDREF mirror; cross-shadow naming uses
`ariaLabelledByElements` (modern) with a flattened-string fallback
(legacy). On the legacy fallback path the inner `[role="tree"]` carries
the role + accessible name and the host role is suppressed so AT only
sees one tree per logical surface (mirrors `hx-menu` round-8).

Full keyboard navigation: Arrow keys for movement, Enter/Space for
selection, Home/End for first/last item, ArrowRight/Left for
expand/collapse + parent/child traversal, typeahead.

## Scale Limits

This component renders all tree items simultaneously in the DOM. It is suitable for
trees with up to ~500 visible items. For large taxonomies (e.g., ICD-10 with 70,000+
codes), use async/lazy loading: only render top-level nodes initially and populate
child nodes on `hx-select` or expand events. The component exposes the `expanded`
property on `hx-tree-item` for programmatic control of subtrees, enabling consumer-level
virtualization strategies without requiring changes to this component.
 *
 * @example
 * ```tsx
 * import { HxTreeView } from '@helixui/react';
 *
 * <HxTreeView />
 * ```
 */
export const HxTreeView = createComponent({
  tagName: 'hx-tree-view',
  elementClass: HelixTreeView,
  react: React,
  events: {
    onHxSelect: 'hx-select',
  },
  displayName: 'HxTreeView',
});

export default HxTreeView;
