/**
 * TypeScript types for HxTreeView React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTreeViewProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Accessible label for the tree. Used as a fallback when no
consumer-supplied `aria-label` / `aria-labelledby` is present on the
host. On the modern host-canonical path this projects onto
`internals.ariaLabel`; on the legacy fallback path it appears as
`aria-label` on the inner `[role="tree"]` element. */
  label?: string;
  /** Selection mode for the tree.
- `none` — items cannot be selected
- `single` — only one item can be selected at a time
- `multiple` — multiple items can be selected */
  selection?: 'none' | 'single' | 'multiple';

  // Event callbacks
  /** Dispatched when a tree item is selected or deselected. */
  onHxSelect?: (event: Event) => void;
}
