/**
 * TypeScript types for HxTreeView React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTreeViewProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Accessible label for the tree. Applied as `aria-label` on the tree container.
Provides context to screen readers about the tree's purpose. */
  label?: string;
  /** Selection mode for the tree.
- `none` — items cannot be selected
- `single` — only one item can be selected at a time
- `multiple` — multiple items can be selected */
  selection?: string;

  // Event callbacks
  /** Dispatched when a tree item is selected or deselected. */
  onHxSelect?: (event: Event) => void;
}
