'use client';
/**
 * React wrapper for <hx-prose> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixProse } from '@helixui/library/components/hx-prose';

import type { HxProseProps } from './types.js';

export type { HxProseProps };

/**
 * A Light DOM prose container that applies typographic styles to rich text
content such as CKEditor output, Markdown-rendered HTML, or any structured
body copy.

Renders in the Light DOM (no Shadow DOM) so that global and scoped styles
can target child elements directly. Uses the AdoptedStylesheetsController
to inject scoped prose CSS into the document without duplication.
 *
 * @example
 * ```tsx
 * import { HxProse } from '@helixui/react';
 *
 * <HxProse />
 * ```
 */
export const HxProse = createComponent({
  tagName: 'hx-prose',
  elementClass: HelixProse,
  react: React,
  events: {},
  displayName: 'HxProse',
});

export default HxProse;
