/**
 * TypeScript types for HxProse React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxProseProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  adoptedStyles?: unknown;
  /** Typography scale for the prose content. */
  size?: 'sm' | 'base' | 'lg';
  /** Maximum content width. When set, overrides the --hx-prose-max-width token.
Accepts any valid CSS width value (e.g., '640px', '80ch', '100%'). */
  maxWidth?: string;
}
