import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { TokenParser } from '../core/token-parser.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ScaffoldThemeOptions {
  /** CSS scoping selector. Defaults to `.hx-theme`. */
  selector?: string;
  /** Optional file path to write the generated CSS. Omit to return CSS only. */
  outputPath?: string;
}

export interface ScaffoldThemeResult {
  css: string;
  tokenCount: number;
  categories: string[];
  outputPath?: string;
}

// ─── Category display labels ──────────────────────────────────────────────────

const CATEGORY_LABELS: Record<string, string> = {
  color: 'Color',
  space: 'Spacing',
  font: 'Typography / Font',
  'line-height': 'Line Height',
  'letter-spacing': 'Letter Spacing',
  border: 'Border',
  shadow: 'Shadow',
  duration: 'Animation Duration',
  easing: 'Animation Easing',
  transition: 'Transition',
  focus: 'Focus',
  state: 'State',
  filter: 'Filter',
  transform: 'Transform',
  container: 'Container',
  input: 'Input',
  divider: 'Divider',
  'z-index': 'Z-Index',
  opacity: 'Opacity',
  size: 'Size',
  overlay: 'Overlay',
  breakpoint: 'Breakpoint',
  'aspect-ratio': 'Aspect Ratio',
  body: 'Body Defaults',
  heading: 'Heading Defaults',
  dark: 'Dark Mode',
  'high-contrast': 'High Contrast Mode',
};

function getCategoryLabel(category: string): string {
  return CATEGORY_LABELS[category] ?? category;
}

// ─── CSS generation ───────────────────────────────────────────────────────────

function buildCssBlock(
  selector: string,
  tokensByCategory: Map<string, Array<{ cssVar: string; value: string; description?: string }>>,
  categories: string[],
): string {
  const lines: string[] = [
    `/**`,
    ` * HELiX UI Theme Scaffold`,
    ` *`,
    ` * Generated by @helixui/mcp scaffold-theme tool.`,
    ` *`,
    ` * Override semantic-tier design tokens for your theme by un-commenting`,
    ` * the properties you want to customize. All tokens are shown with their`,
    ` * default values from @helixui/tokens.`,
    ` *`,
    ` * Usage:`,
    ` *   Apply the scoping selector to a container element:`,
    ` *   <div class="${selector.replace(/^\./, '')}">...your content...</div>`,
    ` *`,
    ` *   Or scope to :root for a global theme override:`,
    ` *   Replace "${selector}" with ":root" below.`,
    ` */`,
    '',
    `${selector} {`,
  ];

  for (const category of categories) {
    const tokens = tokensByCategory.get(category);
    if (!tokens || tokens.length === 0) continue;

    const label = getCategoryLabel(category);
    lines.push('');
    lines.push(`  /* ── ${label} ${'─'.repeat(Math.max(0, 55 - label.length))} */`);

    for (const token of tokens) {
      if (token.description !== undefined) {
        lines.push(`  /* ${token.description} */`);
      }
      lines.push(`  /* ${token.cssVar}: ${token.value}; */`);
    }
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

// ─── Main export ──────────────────────────────────────────────────────────────

export function scaffoldTheme(options: ScaffoldThemeOptions = {}): ScaffoldThemeResult {
  const selector = options.selector ?? '.hx-theme';

  const parser = new TokenParser();
  const allTokens = parser.load();

  // Group by category (path[0])
  const tokensByCategory = new Map<
    string,
    Array<{ cssVar: string; value: string; description?: string }>
  >();

  for (const token of allTokens) {
    const category = token.path[0] ?? 'other';
    if (!tokensByCategory.has(category)) {
      tokensByCategory.set(category, []);
    }
    const entry: { cssVar: string; value: string; description?: string } = {
      cssVar: token.cssVar,
      value: token.value,
    };
    if (token.description !== undefined) {
      entry.description = token.description;
    }
    tokensByCategory.get(category)!.push(entry);
  }

  // Preserve category order from parser (insertion order)
  const categories = Array.from(tokensByCategory.keys());

  const css = buildCssBlock(selector, tokensByCategory, categories);

  const result: ScaffoldThemeResult = {
    css,
    tokenCount: allTokens.length,
    categories,
  };

  if (options.outputPath !== undefined) {
    mkdirSync(dirname(options.outputPath), { recursive: true });
    writeFileSync(options.outputPath, css, 'utf8');
    result.outputPath = options.outputPath;
  }

  return result;
}
