'use client';
/**
 * React wrapper for <hx-button> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixButton } from '@helixui/library/components/hx-button';

import type { HxButtonProps } from './types.js';

export type { HxButtonProps };

/**
 * A production-grade button component for user interaction. Supports multiple
visual variants, sizes, loading state, prefix/suffix slots, anchor rendering,
and full ElementInternals form association.
 *
 * @example
 * ```tsx
 * import { HxButton } from '@helixui/react';
 *
 * <HxButton />
 * ```
 */
export const HxButton = createComponent({
  tagName: 'hx-button',
  elementClass: HelixButton,
  react: React,
  events: {
    onHxClick: 'hx-click'
  },
  displayName: 'HxButton',
});

export default HxButton;
