/**
 * TypeScript types for HxButton React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxButtonProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual style variant of the button. */
  variant?: 'primary' | 'secondary' | 'tertiary' | 'danger' | 'ghost' | 'outline';
  /** Size of the button. */
  size?: 'sm' | 'md' | 'lg';
  /** Whether the button is disabled. Prevents all interaction and form actions. */
  disabled?: boolean;
  /** Whether the button is in a loading state. Shows spinner, prevents interaction,
and sets aria-busy. Does not set the disabled attribute. */
  loading?: boolean;
  /** The type attribute for the underlying button element. Ignored when href is set. */
  type?: 'button' | 'submit' | 'reset';
  /** When set, renders an anchor element instead of a button. */
  href?: string | undefined;
  /** Anchor target attribute. Only used when href is set. */
  target?: string | undefined;
  /** Form field name submitted via ElementInternals.setFormValue on submit. */
  name?: string | undefined;
  /** Form field value submitted via ElementInternals.setFormValue on submit. */
  value?: string | undefined;
  /** When true, the button stretches to fill its container width.
Sets the host to `display: block` and the inner element to `width: 100%`. */
  full?: boolean;
  /** When true, flips button colors for placement on dark or gradient backgrounds.
Forces text to white and adjusts hover/focus ring colors across all variants.

**Mode scope:** `[inverted]` is validated for placement on a dark *region*
within a light-mode-active page (hero banners, gradient sections, dark
cards). It is NOT validated for use within a dark-mode-active root
context: in dark mode, `surface.inverse` flips to a light surface
(neutral-100), and the lifted `-400` hover/active fills lose UI-floor
contrast against it (primary ≈ 2.20:1, danger ≈ 2.43:1 vs WCAG 1.4.11's
3:1 floor). Mode-aware fill stops + foreground for the dark-mode-inverted
combination are tracked as a 3.2.x follow-up. */
  inverted?: boolean;
  /** Accessible label for icon-only or text-less buttons.
Required when the button has no visible text content.

Accepts both `accessible-label` and the standard `aria-label` HTML attribute.
`accessible-label` takes precedence when both are set. */
  accessibleLabel?: string;

  // Event callbacks
  /** Dispatched when the button is clicked and is neither disabled nor loading. */
  onHxClick?: (event: Event) => void;
}
