'use client';
/**
 * React wrapper for <hx-table> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTable } from '@helixui/library/components/hx-table';

import type { HxTableProps } from './types.js';

export type { HxTableProps };

/**
 * A semantic table container with variant styling and accessibility support.
Compose with `hx-thead`, `hx-tbody`, `hx-tfoot`, `hx-tr`, `hx-th`, and `hx-td`.
 *
 * @example
 * ```tsx
 * import { HxTable } from '@helixui/react';
 *
 * <HxTable />
 * ```
 */
export const HxTable = createComponent({
  tagName: 'hx-table',
  elementClass: HelixTable,
  react: React,
  events: {},
  displayName: 'HxTable',
});

export default HxTable;
