/**
 * TypeScript types for HxTable React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTableProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Accessible name for the table (WCAG 4.1.2 requirement).
Exposed via `aria-label` on the `<table>` element. */
  label?: string;
  /** Visible caption text. When set, renders a `<caption>` element.
Use the `caption` slot for richer caption content. */
  caption?: string;
  /** Visual variant that controls row styling. */
  variant?: 'default' | 'striped' | 'hover' | 'compact';
  /** When true, the header row stays fixed while the table body scrolls. */
  stickyHeader?: boolean;
  /** When true, the table expands to fill 100% of its container width. */
  fullWidth?: boolean;
}
