'use client';
/**
 * React wrapper for <hx-counter> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixCounter } from '@helixui/library/components/hx-counter';

import type { HxCounterProps } from './types.js';

export type { HxCounterProps };

/**
 * Animated number counter that counts from 0 (or the previous value) to the
target value using requestAnimationFrame. Respects prefers-reduced-motion.
 *
 * @example
 * ```tsx
 * import { HxCounter } from '@helixui/react';
 *
 * <HxCounter />
 * ```
 */
export const HxCounter = createComponent({
  tagName: 'hx-counter',
  elementClass: HelixCounter,
  react: React,
  events: {},
  displayName: 'HxCounter',
});

export default HxCounter;
