/**
 * TypeScript types for HxCounter React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxCounterProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The target numeric value to count to. */
  value?: number;
  /** Animation duration in milliseconds. */
  duration?: number;
  /** Easing function applied to the animation progress. */
  easing?: 'linear' | 'ease-in' | 'ease-out' | 'ease-in-out';
  /** Number format. 'integer' rounds to the nearest whole number;
'decimal' shows two decimal places. */
  format?: 'integer' | 'decimal';
  /** String prepended to the formatted value (e.g., '$'). */
  prefix?: string;
  /** String appended to the formatted value (e.g., '%'). */
  suffix?: string;
  /** Size variant controlling font size. */
  size?: 'sm' | 'md' | 'lg';
  /** Accessible label describing the counter's context (e.g. "Total patients", "Active alerts").
WCAG 4.1.2: a numeric value alone is meaningless without context for screen readers.
When provided, the value is applied as aria-label on the counter element. */
  label?: string;
}
