/**
 * TypeScript types for HxCounter React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxCounterProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The target numeric value to count to. */
  value?: number;
  /** Animation duration in milliseconds. */
  duration?: number;
  /** Easing function applied to the animation progress. */
  easing?: string;
  /** Number format. 'integer' rounds to the nearest whole number;
'decimal' shows two decimal places. */
  format?: string;
  /** String prepended to the formatted value (e.g., '$'). */
  prefix?: string;
  /** String appended to the formatted value (e.g., '%'). */
  suffix?: string;
  /** Size variant controlling font size. */
  size?: string;
}
