'use client';
/**
 * React wrapper for <hx-checkbox-group> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixCheckboxGroup } from '@helixui/library/components/hx-checkbox-group';

import type { HxCheckboxGroupProps } from './types.js';

export type { HxCheckboxGroupProps };

/**
 * A form-associated checkbox group that manages a set of `<hx-checkbox>` children.
 *
 * @example
 * ```tsx
 * import { HxCheckboxGroup } from '@helixui/react';
 *
 * <HxCheckboxGroup />
 * ```
 */
export const HxCheckboxGroup = createComponent({
  tagName: 'hx-checkbox-group',
  elementClass: HelixCheckboxGroup,
  react: React,
  events: {
    onHxChange: 'hx-change',
  },
  displayName: 'HxCheckboxGroup',
});

export default HxCheckboxGroup;
