/**
 * TypeScript types for HxCheckboxGroup React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxCheckboxGroupProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The name used for form submission. Passed to child `hx-checkbox` elements. */
  name?: string;
  /** The fieldset legend/label text. */
  label?: string;
  /** Whether at least one checkbox must be checked for form submission. */
  required?: boolean;
  /** Whether the entire group is disabled. */
  disabled?: boolean;
  /** Error message to display. When set, the group enters an error state. */
  error?: string;
  /** Layout orientation of the checkbox items. */
  orientation?: 'vertical' | 'horizontal';
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched when any child checkbox changes. */
  onHxChange?: (event: Event) => void;
}
