'use client';
/**
 * React wrapper for <hx-grid-item> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixGridItem } from '@helixui/library/components/hx-grid';

import type { HxGridItemProps } from './types.js';

export type { HxGridItemProps };

/**
 * Optional companion element for precise grid item placement.
Applies grid-column and grid-row directly to the host element
so it participates correctly in the parent CSS grid layout.
 *
 * @example
 * ```tsx
 * import { HxGridItem } from '@helixui/react';
 *
 * <HxGridItem />
 * ```
 */
export const HxGridItem = createComponent({
  tagName: 'hx-grid-item',
  elementClass: HelixGridItem,
  react: React,
  events: {},
  displayName: 'HxGridItem',
});

export default HxGridItem;
