/**
 * TypeScript types for HxGridItem React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxGridItemProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** CSS grid-column value (e.g., "1 / 3", "span 2"). */
  column?: string | undefined;
  /** CSS grid-row value (e.g., "1 / 2"). */
  row?: string | undefined;
  /** Column span shorthand — equivalent to setting `column: "span N"`. */
  span?: number | undefined;
}
