'use client';
/**
 * React wrapper for <hx-grid> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixGrid } from '@helixui/library/components/hx-grid';

import type { HxGridProps } from './types.js';

export type { HxGridProps };

/**
 * A CSS Grid layout wrapper with design-token-based column and gap system.
 *
 * @example
 * ```tsx
 * import { HxGrid } from '@helixui/react';
 *
 * <HxGrid />
 * ```
 */
export const HxGrid = createComponent({
  tagName: 'hx-grid',
  elementClass: HelixGrid,
  react: React,
  events: {},
  displayName: 'HxGrid',
});

export default HxGrid;
