/**
 * TypeScript types for HxGrid React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxGridProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Number of equal columns (`repeat(N, 1fr)`) or a CSS grid-template-columns string. */
  columns?: number | string;
  /** Gap size applied to both row and column gaps. */
  gap?: string;
  /** Row gap override. When set, takes precedence over `gap` for row spacing. */
  rowGap?: string | undefined;
  /** Column gap override. When set, takes precedence over `gap` for column spacing. */
  columnGap?: string | undefined;
  /** Aligns grid items along the block axis (align-items). */
  align?: string;
  /** Justifies grid items along the inline axis (justify-items). */
  justify?: string;
}
