'use client';
/**
 * React wrapper for <hx-badge> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixBadge } from '@helixui/library/components/hx-badge';

import type { HxBadgeProps } from './types.js';

export type { HxBadgeProps };

/**
 * A small status indicator for notifications, counts, and labels.
 *
 * @example
 * ```tsx
 * import { HxBadge } from '@helixui/react';
 *
 * <HxBadge />
 * ```
 */
export const HxBadge = createComponent({
  tagName: 'hx-badge',
  elementClass: HelixBadge,
  react: React,
  events: {
    onHxRemove: 'hx-remove'
  },
  displayName: 'HxBadge',
});

export default HxBadge;
