/**
 * TypeScript types for HxBadge React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxBadgeProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual style variant of the badge. */
  variant?: 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'neutral' | 'info';
  /** Size of the badge. */
  size?: 'sm' | 'md' | 'lg';
  /** Whether the badge uses fully rounded (pill) styling. */
  pill?: boolean;
  /** Whether the badge displays an animated pulse for attention. */
  pulse?: boolean;
  /** Whether the badge renders a dismiss button. */
  removable?: boolean;
  /** Numeric count to display. When set, renders the count as badge content.
When count exceeds `max`, displays `${max}+` (e.g. `99+`). */
  count?: number | undefined;
  /** Maximum count value before truncation to `${max}+`. Defaults to 99. */
  max?: number;
  /** Accessible label for the dot indicator mode (pulse + empty slot).
Required for WCAG 4.1.2 compliance when using the dot indicator pattern.
Example: `dot-label="3 new messages"`. */
  dotLabel?: string;
  /** Accessible label for the remove button. Should describe what is being removed.
Defaults to "Remove". For better accessibility, include context: e.g. "Remove Critical badge". */
  removeLabel?: string;

  // Event callbacks
  /** Dispatched when the user clicks the remove button. */
  onHxRemove?: (event: Event) => void;
}
