'use client';
/**
 * React wrapper for <hx-split-button> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSplitButton } from '@helixui/library/components/hx-split-button';

import type { HxSplitButtonProps } from './types.js';

export type { HxSplitButtonProps };

/**
 * A split button combining a primary action button with an attached dropdown
menu for secondary actions. Implements the ARIA menu button pattern for
full keyboard and screen reader support.
 *
 * @example
 * ```tsx
 * import { HxSplitButton } from '@helixui/react';
 *
 * <HxSplitButton />
 * ```
 */
export const HxSplitButton = createComponent({
  tagName: 'hx-split-button',
  elementClass: HelixSplitButton,
  react: React,
  events: {
    onHxClick: 'hx-click',
    onHxSelect: 'hx-select'
  },
  displayName: 'HxSplitButton',
});

export default HxSplitButton;
