/**
 * TypeScript types for HxSplitButton React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxSplitButtonProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual style variant of the split button. */
  variant?: 'primary' | 'secondary' | 'tertiary' | 'danger' | 'ghost' | 'outline';
  /** Size of the split button. */
  size?: 'sm' | 'md' | 'lg';
  /** Whether the split button is disabled. Both the primary button and the
trigger are disabled when this is true. */
  disabled?: boolean;
  /** Primary button label text. When set, overrides the default slot content. */
  label?: string | undefined;
  /** Accessible label for the dropdown trigger button. Override for localization. */
  triggerLabel?: string;
  /** Accessible label for the dropdown menu panel. Override for localization. */
  menuLabel?: string;

  // Event callbacks
  /** Dispatched when the primary button is clicked and is not disabled. */
  onHxClick?: (event: Event) => void;
  /** Dispatched when a menu item is selected from the dropdown. */
  onHxSelect?: (event: Event) => void;
}
