'use client';
/**
 * React wrapper for <hx-patient-banner> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixPatientBanner } from '@helixui/library/components/hx-patient-banner';

import type { HxPatientBannerProps } from './types.js';

export type { HxPatientBannerProps };

/**
 * Patient identification banner implementing Joint Commission NPSG.01.01.01 two-identifier rule.
Renders as a landmark region containing named slots for patient identification fields.
Integrates with hx-phi-field for HIPAA-compliant display of masked identifiers.
Note: hx-phi-access events fired by slotted hx-phi-field elements bubble through this
component via composed: true — no re-dispatch is required.
 *
 * @example
 * ```tsx
 * import { HxPatientBanner } from '@helixui/react';
 *
 * <HxPatientBanner />
 * ```
 */
export const HxPatientBanner = createComponent({
  tagName: 'hx-patient-banner',
  elementClass: HelixPatientBanner,
  react: React,
  events: {
    onHxIdentifierRuleViolation: 'hx-identifier-rule-violation'
  },
  displayName: 'HxPatientBanner',
});

export default HxPatientBanner;
