/**
 * TypeScript types for HxPatientBanner React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxPatientBannerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Optional patient ID used as context in identifier rule violation events. */
  patientId?: string;
  /** Accessible label for the banner landmark region. */
  labelPatient?: string;
  /** Visible label for the name field. */
  labelName?: string;
  /** Visible label for the MRN field. */
  labelMrn?: string;
  /** Visible label for the date of birth field. */
  labelDob?: string;
  /** Visible label for the allergies field. */
  labelAllergies?: string;
  /** Visible label for the code status field. */
  labelCodeStatus?: string;
  /** Whether to enforce the Joint Commission NPSG.01.01.01 two-identifier rule.
When true, fires hx-identifier-rule-violation if fewer than 2 identifier
slots (name, mrn, dob) are populated. */
  enforceIdentifierRule?: boolean;

  // Event callbacks
  /** Fired when fewer than 2 identifier slots are populated and enforce-identifier-rule is true. */
  onHxIdentifierRuleViolation?: (event: Event) => void;
}
