'use client';
/**
 * React wrapper for <hx-step> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixStep } from '@helixui/library/components/hx-steps';

import type { HxStepProps } from './types.js';

export type { HxStepProps };

/**
 * An individual step, designed to be used inside an `<hx-steps>` container.
Represents a single step in a multi-step wizard or progress indicator.
 *
 * @example
 * ```tsx
 * import { HxStep } from '@helixui/react';
 *
 * <HxStep />
 * ```
 */
export const HxStep = createComponent({
  tagName: 'hx-step',
  elementClass: HelixStep,
  react: React,
  events: {},
  displayName: 'HxStep',
});

export default HxStep;
