/**
 * TypeScript types for HxStep React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxStepProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The step label text. */
  label?: string;
  /** Current status of the step. */
  status?: 'pending' | 'active' | 'complete' | 'error';
  /** Optional description text shown below the label. */
  description?: string;
  /** Whether the step is disabled and non-interactive. */
  disabled?: boolean;
}
