'use client';
/**
 * React wrapper for <hx-progress-ring> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixProgressRing } from '@helixui/library/components/hx-progress-ring';

import type { HxProgressRingProps } from './types.js';

export type { HxProgressRingProps };

/**
 * SVG-based circular progress indicator. Supports determinate and indeterminate modes,
multiple size variants, semantic color variants, and a center content slot.
 *
 * @example
 * ```tsx
 * import { HxProgressRing } from '@helixui/react';
 *
 * <HxProgressRing />
 * ```
 */
export const HxProgressRing = createComponent({
  tagName: 'hx-progress-ring',
  elementClass: HelixProgressRing,
  react: React,
  events: {},
  displayName: 'HxProgressRing',
});

export default HxProgressRing;
