/**
 * TypeScript types for HxProgressRing React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxProgressRingProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Current progress value (0–max). When null, renders in indeterminate mode. */
  value?: number | null;
  /** Maximum value for the progress range. Defaults to 100. Used for aria-valuemax. */
  max?: number;
  /** Size of the ring. Controls SVG diameter. */
  size?: 'sm' | 'md' | 'lg';
  /** Stroke width of the ring circles in SVG user units. */
  strokeWidth?: number;
  /** Semantic color variant. */
  variant?: 'default' | 'success' | 'warning' | 'danger';
  /** Accessible label for the progressbar. Exposed as aria-label.
Set this attribute to satisfy WCAG 4.1.2. When absent, aria-busy reflects
indeterminate state and a console warning is emitted. */
  label?: string;
}
