'use client';
/**
 * React wrapper for <hx-style-scope> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HxStyleScope as HelixStyleScope } from '@helixui/library/components/hx-style-scope';

import type { HxStyleScopeProps } from './types.js';

export type { HxStyleScopeProps };

/**
 * A transparent wrapper component that injects scoped light DOM styles for its
slotted children. Designed for use in Drupal Twig templates where slotted
content lives in the light DOM and cannot inherit Shadow DOM styles.

On connection, the component:
1. Sets `data-hx-styled` on itself so scoped CSS selectors resolve correctly.
2. Calls `injectLightStyles` to inject a `<style>` into `document.head` — once
   per component type, deduplicated via `lightStyleRegistry`.

The element renders as `display: contents` so it does not affect layout.
 *
 * @example
 * ```tsx
 * import { HxStyleScope } from '@helixui/react';
 *
 * <HxStyleScope />
 * ```
 */
export const HxStyleScope = createComponent({
  tagName: 'hx-style-scope',
  elementClass: HelixStyleScope,
  react: React,
  events: {},
  displayName: 'HxStyleScope',
});

export default HxStyleScope;
