/**
 * TypeScript types for HxStyleScope React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxStyleScopeProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The component tag name whose light DOM styles should be injected.
Must match a registered component name (e.g. `'hx-card'`).

When set, the element also applies `data-hx-styled` to itself so that
scoped CSS selectors generated by `generateScopedSelectors` resolve
correctly against slotted child elements. */
  component?: string;
  /** The CSS to inject as scoped light DOM styles. When provided alongside
`component`, this CSS will be scoped under `[data-hx-styled="component"]`
and injected into `document.head` (once per component type).

If omitted, `injectLightStyles` is still called but with an empty string,
which is a no-op for actual style injection. */
  lightCss?: string;
}
