'use client';
/**
 * React wrapper for <hx-tab-panel> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTabPanel } from '@helixui/library/components/hx-tabs';

import type { HxTabPanelProps } from './types.js';

export type { HxTabPanelProps };

/**
 * A content panel associated with an `<hx-tab>`, managed by a parent `<hx-tabs>`.
Group 5a host-canonical: `role="tabpanel"` lives on the host via
`_internals.role`. The host carries the canonical AT surface — consumer
`aria-labelledby` / `aria-describedby` on the host resolve through the
shared IDREF mirror. The parent `hx-tabs` writes `internals.ariaLabelledByElements`
referencing the corresponding `<hx-tab>` host so cross-shadow naming works
via IDL element references (the modern path) without serializing tab text.
 *
 * @example
 * ```tsx
 * import { HxTabPanel } from '@helixui/react';
 *
 * <HxTabPanel />
 * ```
 */
export const HxTabPanel = createComponent({
  tagName: 'hx-tab-panel',
  elementClass: HelixTabPanel,
  react: React,
  events: {},
  displayName: 'HxTabPanel',
});

export default HxTabPanel;
