'use client';
/**
 * React wrapper for <hx-tab-panel> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTabPanel } from '@helixui/library/components/hx-tabs';

import type { HxTabPanelProps } from './types.js';

export type { HxTabPanelProps };

/**
 * A content panel associated with an `<hx-tab>`, managed by a parent `<hx-tabs>`.
 *
 * @example
 * ```tsx
 * import { HxTabPanel } from '@helixui/react';
 *
 * <HxTabPanel />
 * ```
 */
export const HxTabPanel = createComponent({
  tagName: 'hx-tab-panel',
  elementClass: HelixTabPanel,
  react: React,
  events: {},
  displayName: 'HxTabPanel',
});

export default HxTabPanel;
