/**
 * TypeScript types for HxTabPanel React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTabPanelProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The name that corresponds to the `panel` attribute on the associated `<hx-tab>`. */
  name?: string;
}
