'use client';
/**
 * React wrapper for <hx-accordion> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixAccordion } from '@helixui/library/components/hx-accordion';

import type { HxAccordionProps } from './types.js';

export type { HxAccordionProps };

/**
 * An accordion container that manages collapsible content sections.
 *
 * @example
 * ```tsx
 * import { HxAccordion } from '@helixui/react';
 *
 * <HxAccordion />
 * ```
 */
export const HxAccordion = createComponent({
  tagName: 'hx-accordion',
  elementClass: HelixAccordion,
  react: React,
  events: {},
  displayName: 'HxAccordion',
});

export default HxAccordion;
