/**
 * TypeScript types for HxAccordion React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxAccordionProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Expansion mode: 'single' collapses all other items when one expands.
'multi' allows multiple items open simultaneously. */
  mode?: 'single' | 'multi';
}
