'use client';
/**
 * React wrapper for <hx-tfoot> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTableFoot } from '@helixui/library/components/hx-table';

import type { HxTfootProps } from './types.js';

export type { HxTfootProps };

/**
 * Semantic table foot section. Must be a direct child of `hx-table`.
Typically contains summary or totals rows.
 *
 * @example
 * ```tsx
 * import { HxTfoot } from '@helixui/react';
 *
 * <HxTfoot />
 * ```
 */
export const HxTfoot = createComponent({
  tagName: 'hx-tfoot',
  elementClass: HelixTableFoot,
  react: React,
  events: {},
  displayName: 'HxTfoot',
});

export default HxTfoot;
