'use client';
/**
 * React wrapper for <hx-field-label> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixFieldLabel } from '@helixui/library/components/hx-field-label';

import type { HxFieldLabelProps } from './types.js';

export type { HxFieldLabelProps };

/**
 * Standardized label for form fields. Used as a consistent sub-component
for hx-field and other form field components.

## Label Association

**For inputs in light DOM (the typical consumer deployment):** Use
`aria-labelledby` pointing to the host element's `id`. The `for` attribute
renders a native `<label for="...">` inside shadow DOM, but the HTML spec
scopes `for`/`id` lookup to the same tree — a shadow-DOM label cannot
associate with a light-DOM input. Example:

```html
<hx-field-label id="label-email">Email</hx-field-label>
<input id="email" aria-labelledby="label-email" />
```

**For inputs in the same shadow root:** The `for` attribute works as
expected for direct label association.

When `for` is unset, renders a `<span>` that can be referenced via
`aria-labelledby` for labeling controls across the shadow DOM boundary.
 *
 * @example
 * ```tsx
 * import { HxFieldLabel } from '@helixui/react';
 *
 * <HxFieldLabel />
 * ```
 */
export const HxFieldLabel = createComponent({
  tagName: 'hx-field-label',
  elementClass: HelixFieldLabel,
  react: React,
  events: {},
  displayName: 'HxFieldLabel',
});

export default HxFieldLabel;
