/**
 * TypeScript types for HxFieldLabel React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxFieldLabelProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The ID of the associated form control. When set, renders a native
`<label for="...">` element for direct label association. */
  for?: string;
  /** Whether the associated field is required. Shows a required indicator (*). */
  required?: boolean;
  /** Whether the associated field is optional. Shows "(optional)" text. */
  optional?: boolean;
}
