'use client';
/**
 * React wrapper for <hx-switch> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSwitch } from '@helixui/library/components/hx-switch';

import type { HxSwitchProps } from './types.js';

export type { HxSwitchProps };

/**
 * A toggle switch component for on/off states.

Uses `role="switch"` with `aria-checked` to convey toggle state.
Supports keyboard activation via Space key (per ARIA APG switch pattern).
Label association is handled through `aria-labelledby`, and
error/help text are linked via `aria-describedby`.
 *
 * @example
 * ```tsx
 * import { HxSwitch } from '@helixui/react';
 *
 * <HxSwitch />
 * ```
 */
export const HxSwitch = createComponent({
  tagName: 'hx-switch',
  elementClass: HelixSwitch,
  react: React,
  events: {
    onHxChange: 'hx-change'
  },
  displayName: 'HxSwitch',
});

export default HxSwitch;
