/**
 * TypeScript types for HxSwitch React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxSwitchProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Whether the switch is toggled on. */
  checked?: boolean;
  /** Whether the switch is disabled. */
  disabled?: boolean;
  /** Whether the switch is required for form submission. */
  required?: boolean;
  /** The name of the switch, used for form submission. */
  name?: string;
  /** The value submitted when the switch is checked. */
  value?: string;
  /** The visible label text for the switch. */
  label?: string;
  /** Size variant of the switch. */
  size?: 'sm' | 'md' | 'lg';
  /** Error message to display. When set, the switch enters an error state. */
  error?: string;
  /** Help text displayed below the switch for guidance. */
  helpText?: string;
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched when the switch is toggled. */
  onHxChange?: (event: Event) => void;
}
