'use client';
/**
 * React wrapper for <hx-color-picker> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixColorPicker } from '@helixui/library/components/hx-color-picker';

import type { HxColorPickerProps } from './types.js';

export type { HxColorPickerProps };

/**
 * A color picker control with gradient picker, hue/opacity sliders, swatches,
and formatted text input. Supports hex, rgb, hsl, and hsv output formats.
 *
 * @example
 * ```tsx
 * import { HxColorPicker } from '@helixui/react';
 *
 * <HxColorPicker />
 * ```
 */
export const HxColorPicker = createComponent({
  tagName: 'hx-color-picker',
  elementClass: HelixColorPicker,
  react: React,
  events: {
    onHxInput: 'hx-input',
    onHxChange: 'hx-change'
  },
  displayName: 'HxColorPicker',
});

export default HxColorPicker;
