/**
 * TypeScript types for HxColorPicker React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxColorPickerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Current color value as a CSS color string. */
  value?: string;
  /** Output format for the color value. */
  format?: string;
  /** Whether to show the alpha/opacity channel slider and include alpha in the output. */
  opacity?: boolean;
  /** Array of preset swatch color strings.
Set via JS property only — arrays cannot be serialized as HTML attributes.
In Drupal/Twig, use a behavior to read `data-swatches` and set this property.
See JSDoc example above. */
  swatches?: string[];
  /** When true, hides the gradient grid and sliders, showing only swatches and the input.
Useful for compact preset-only color selection UIs. */
  swatchesOnly?: boolean;
  /** Whether the control is disabled. */
  disabled?: boolean;
  /** Form field name for form participation. */
  name?: string;
  /** When true the picker is shown inline instead of in a popover. */
  inline?: boolean;
  /** When true, the picker requires a non-empty value for form submission. */
  required?: boolean;
  /** Accessible label for the color gradient canvas. */
  labelGradient?: string;
  /** Accessible label for the hue slider. */
  labelHue?: string;
  /** Accessible label for the opacity slider. */
  labelOpacity?: string;
  /** Accessible label for the preset color swatches section. */
  labelSwatches?: string;
  /** Accessible label for the format-switch button. */
  labelSwitchFormat?: string;
  /** Accessible label for the color value input. */
  labelColorValue?: string;
  /** Accessible label for the color picker dialog/panel. */
  labelPicker?: string;
  /** Visible label rendered above the trigger. When set this becomes the
announced name of the trigger surface unless a stronger source
(`aria-labelledby`, `aria-label`, or `accessible-label`) is supplied. */
  label?: string | undefined;
  /** Visually-hidden accessible name. Highest-priority self-naming source —
outranks `label`, slotted label content, and the generated trigger label,
but defers to consumer `aria-labelledby` (effective) and `aria-label`. */
  accessibleLabel?: string | undefined;
  /** Help text rendered below the trigger and joined into the host's
announced description channel. */
  helpText?: string | undefined;
  /** Error message. When non-empty, marks the trigger surface as `aria-invalid`
and joins the host's announced description channel via a live alert. */
  error?: string | undefined;
  /** Generates the accessible label for the trigger button when no other
naming source is provided. */
  labelTrigger?: (color: string) => string;

  // Event callbacks
  /** Dispatched while dragging sliders or grid. */
  onHxInput?: (event: Event) => void;
  /** Dispatched when a color is committed. */
  onHxChange?: (event: Event) => void;
}
