/**
 * TypeScript types for HxColorPicker React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxColorPickerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Current color value as a CSS color string. */
  value?: string;
  /** Output format for the color value. */
  format?: string;
  /** Whether to show the alpha/opacity channel slider and include alpha in the output. */
  opacity?: boolean;
  /** Array of preset swatch color strings.
Set via JS property only — arrays cannot be serialized as HTML attributes.
In Drupal/Twig, use a behavior to read `data-swatches` and set this property.
See JSDoc example above. */
  swatches?: string[];
  /** When true, hides the gradient grid and sliders, showing only swatches and the input.
Useful for compact preset-only color selection UIs. */
  swatchesOnly?: boolean;
  /** Whether the control is disabled. */
  disabled?: boolean;
  /** Form field name for form participation. */
  name?: string;
  /** When true the picker is shown inline instead of in a popover. */
  inline?: boolean;
  /** When true, the picker requires a non-empty value for form submission. */
  required?: boolean;
  /** Accessible label for the color gradient canvas. */
  labelGradient?: string;
  /** Accessible label for the hue slider. */
  labelHue?: string;
  /** Accessible label for the opacity slider. */
  labelOpacity?: string;
  /** Accessible label for the preset color swatches section. */
  labelSwatches?: string;
  /** Accessible label for the format-switch button. */
  labelSwitchFormat?: string;
  /** Accessible label for the color value input. */
  labelColorValue?: string;
  /** Accessible label for the color picker dialog/panel. */
  labelPicker?: string;
  /** Generates the accessible label for the trigger button. */
  labelTrigger?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;
  /** Returns the current validation message. */
  validationMessage?: string;

  // Event callbacks
  /** Dispatched while dragging sliders or grid. */
  onHxInput?: (event: Event) => void;
  /** Dispatched when a color is committed. */
  onHxChange?: (event: Event) => void;
}
