'use client';
/**
 * React wrapper for <hx-form> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixForm } from '@helixui/library/components/hx-form';

import type { HxFormProps } from './types.js';

export type { HxFormProps };

/**
 * A Light DOM form wrapper that styles native HTML form elements and
hx-* components with the design system's form styles.

When `action` is set, renders a `<form>` wrapper around slotted content.
When no `action` is set (the Drupal pattern), renders only a `<slot>`
so Drupal can provide its own `<form>` tag.

Uses adopted stylesheets to inject scoped CSS into the document without
Shadow DOM, keeping native form participation and Drupal compatibility.
 *
 * @example
 * ```tsx
 * import { HxForm } from '@helixui/react';
 *
 * <HxForm />
 * ```
 */
export const HxForm = createComponent({
  tagName: 'hx-form',
  elementClass: HelixForm,
  react: React,
  events: {
    onHxSubmit: 'hx-submit',
    onHxInvalid: 'hx-invalid',
    onHxReset: 'hx-reset'
  },
  displayName: 'HxForm',
});

export default HxForm;
