'use client';
/**
 * React wrapper for <hx-form> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixForm } from '@helixui/library/components/hx-form';

import type { HxFormProps } from './types.js';

export type { HxFormProps };

/**
 * A pure Light DOM form wrapper that styles native HTML form elements and
hx-* components with the design system's form styles. It NEVER renders its own
`<form>` — the consumer/host always provides the actual `<form>` (a Drupal or
Marketo host form, or an action-less `<form>` slotted for controlled behavior).

The client-side submit bridge (validate + dispatch `hx-submit` / `hx-invalid`)
runs only for a submitted form that hx-form does not surrender to the host:
native submission proceeds when the submitting `<form>` declares its own
non-empty `action`, or its submit button carries a non-empty `formaction` (a
host-owned Drupal Form API or Marketo `mktoForm_*` form). Otherwise the submit
is bridged, scoped to that form's controls. If the consumer provides only loose
controls and NO `<form>`, no submit event fires and no bridge runs — wrap
controls in a `<form>` for controlled behavior. Set `no-intercept` to disable
the bridge entirely and use hx-form purely for styling.

Uses adopted stylesheets to inject scoped CSS into the document without
Shadow DOM, keeping native form participation and Drupal compatibility.
 *
 * @example
 * ```tsx
 * import { HxForm } from '@helixui/react';
 *
 * <HxForm />
 * ```
 */
export const HxForm = createComponent({
  tagName: 'hx-form',
  elementClass: HelixForm,
  react: React,
  events: {
    onHxSubmit: 'hx-submit',
    onHxInvalid: 'hx-invalid',
    onHxReset: 'hx-reset',
  },
  displayName: 'HxForm',
});

export default HxForm;
