/**
 * TypeScript types for HxForm React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxFormProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The URL to submit the form to. When empty, the form handles
submission client-side only and dispatches `hx-submit`. */
  action?: string;
  /** The HTTP method used when submitting the form. */
  method?: 'get' | 'post';
  /** When true, disables the browser's built-in constraint validation
on form submission. */
  novalidate?: boolean;
  /** Identifies the form for scripting and form discovery. */
  name?: string;
  /** The encoding type for form submission. Only used when `action` is set.
Use `multipart/form-data` for forms with file uploads. */
  enctype?: 'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain';

  // Event callbacks
  /** Dispatched on valid client-side submit when no action is set. */
  onHxSubmit?: (event: Event) => void;
  /** Dispatched when validation fails on submit. */
  onHxInvalid?: (event: Event) => void;
  /** Dispatched when the form is reset. */
  onHxReset?: (event: Event) => void;
}
