'use client';
/**
 * React wrapper for <hx-toggle-button> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixToggleButton } from '@helixui/library/components/hx-toggle-button';

import type { HxToggleButtonProps } from './types.js';

export type { HxToggleButtonProps };

/**
 * A two-state toggle button that communicates a pressed/unpressed status to
assistive technology via `aria-pressed`. Supports multiple visual variants
and sizes, prefix/suffix slots, full ElementInternals form association, and
a distinct pressed visual state for every variant.
 *
 * @example
 * ```tsx
 * import { HxToggleButton } from '@helixui/react';
 *
 * <HxToggleButton />
 * ```
 */
export const HxToggleButton = createComponent({
  tagName: 'hx-toggle-button',
  elementClass: HelixToggleButton,
  react: React,
  events: {
    onHxToggle: 'hx-toggle',
  },
  displayName: 'HxToggleButton',
});

export default HxToggleButton;
