/**
 * TypeScript types for HxToggleButton React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxToggleButtonProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Whether the toggle button is in the pressed state.
Reflected as an attribute so CSS selectors like `:host([pressed])` work. */
  pressed?: boolean;
  /** Visual style variant of the button. */
  variant?: 'primary' | 'secondary' | 'tertiary' | 'ghost' | 'outline';
  /** Size of the button. */
  size?: 'sm' | 'md' | 'lg';
  /** Whether the button is disabled. Prevents all interaction and form actions. */
  disabled?: boolean;
  /** Form field name submitted via ElementInternals when the button is pressed. */
  name?: string | undefined;
  /** Form field value submitted via ElementInternals when the button is pressed. */
  value?: string | undefined;
  /** Accessible label forwarded to the inner `<button>` as `aria-label`.
Required for icon-only toggle buttons where no visible text is present. */
  label?: string | undefined;
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;

  // Event callbacks
  /** Dispatched when the toggle state changes. Not dispatched when the button is disabled. */
  onHxToggle?: (event: Event) => void;
}
