'use client';
/**
 * React wrapper for <hx-top-nav> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTopNav } from '@helixui/library/components/hx-top-nav';

import type { HxTopNavProps } from './types.js';

export type { HxTopNavProps };

/**
 * Top-of-page site navigation bar with logo, menu items, and utility area.
Supports sticky positioning, responsive hamburger menu, and full slot-driven
content composition for Drupal and other CMS consumers.
 *
 * @example
 * ```tsx
 * import { HxTopNav } from '@helixui/react';
 *
 * <HxTopNav />
 * ```
 */
export const HxTopNav = createComponent({
  tagName: 'hx-top-nav',
  elementClass: HelixTopNav,
  react: React,
  events: {
    onHxMobileToggle: 'hx-mobile-toggle'
  },
  displayName: 'HxTopNav',
});

export default HxTopNav;
