/**
 * TypeScript types for HxTopNav React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTopNavProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** When true, the navigation bar sticks to the top of the viewport during scroll. */
  sticky?: boolean;
  /** Accessible label applied to the `<nav>` element via `aria-label`. */
  label?: string;

  // Event callbacks
  /** Dispatched when the hamburger button is toggled. Detail contains the new open state. */
  onHxMobileToggle?: (event: Event) => void;
}
