'use client';
/**
 * React wrapper for <hx-theme> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTheme } from '@helixui/library/components/hx-theme';

import type { HxThemeProps } from './types.js';

export type { HxThemeProps };

/**
 * A theme provider that injects CSS custom property tokens for a named theme
onto a scoped root element. Wrapping content with this component scopes
all `--hx-*` design tokens to the selected theme.

This is a pure infrastructure component with `display: contents` — it does
not affect layout. Use it to apply a theme to a subtree of components.

Supported themes:
- `"light"` — standard light-mode token set (default)
- `"dark"` — dark-mode semantic overrides applied on top of light primitives
- `"high-contrast"` — WCAG 7:1+ contrast token set for low-vision accessibility
- `"auto"` — follows the OS `prefers-color-scheme` media query (light or dark)
 *
 * @example
 * ```tsx
 * import { HxTheme } from '@helixui/react';
 *
 * <HxTheme />
 * ```
 */
export const HxTheme = createComponent({
  tagName: 'hx-theme',
  elementClass: HelixTheme,
  react: React,
  events: {},
  displayName: 'HxTheme',
});

export default HxTheme;
