/**
 * TypeScript types for HxTheme React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxThemeProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The theme to apply. Determines which set of --hx-* tokens are injected.
- `"light"` (default): standard light-mode tokens
- `"dark"`: dark-mode semantic overrides applied on top of light primitives
- `"high-contrast"`: WCAG 7:1+ contrast tokens for low-vision users
- `"auto"`: follows OS `prefers-color-scheme`; resolves to `"light"` or `"dark"` at runtime */
  theme?: string;
  system?: boolean;
  /** Returns the currently active theme name.
When `system=true` or `theme="auto"`, reflects the OS preference (`"light"` or `"dark"`).
Otherwise returns the `theme` property value. */
  effectiveTheme?: string;
}
