'use client';
/**
 * React wrapper for <hx-radio> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixRadio } from '@helixui/library/components/hx-radio-group';

import type { HxRadioProps } from './types.js';

export type { HxRadioProps };

/**
 * An individual radio button, designed to be used inside a `<hx-radio-group>`.
 *
 * @example
 * ```tsx
 * import { HxRadio } from '@helixui/react';
 *
 * <HxRadio />
 * ```
 */
export const HxRadio = createComponent({
  tagName: 'hx-radio',
  elementClass: HelixRadio,
  react: React,
  events: {},
  displayName: 'HxRadio',
});

export default HxRadio;
