/**
 * TypeScript types for HxRadio React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxRadioProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The value this radio represents. */
  value?: string;
  /** Visible label text for the radio. */
  label?: string;
  /** Whether this radio is disabled. */
  disabled?: boolean;
  /** Whether this radio is checked. Managed by the parent group. */
  checked?: boolean;
}
