'use client';
/**
 * React wrapper for <hx-stack> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixStack } from '@helixui/library/components/hx-stack';

import type { HxStackProps } from './types.js';

export type { HxStackProps };

/**
 * A flexbox layout wrapper for consistent vertical/horizontal spacing between children.
 *
 * @example
 * ```tsx
 * import { HxStack } from '@helixui/react';
 *
 * <HxStack />
 * ```
 */
export const HxStack = createComponent({
  tagName: 'hx-stack',
  elementClass: HelixStack,
  react: React,
  events: {},
  displayName: 'HxStack',
});

export default HxStack;
