/**
 * TypeScript types for HxStack React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxStackProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Direction of the stack layout. */
  direction?: 'horizontal' | 'vertical';
  /** Gap between children using design tokens. */
  gap?: 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  /** Align-items value for cross-axis alignment. */
  align?: 'start' | 'center' | 'end' | 'stretch' | 'baseline';
  /** Justify-content value for main-axis distribution. */
  justify?: 'start' | 'center' | 'end' | 'between' | 'around' | 'evenly';
  /** When true, children wrap onto multiple lines. */
  wrap?: boolean;
  /** When true, the component renders as `display: inline-flex`. */
  inline?: boolean;
}
