'use client';
/**
 * React wrapper for <hx-icon-button> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixIconButton } from '@helixui/library/components/hx-icon-button';

import type { HxIconButtonProps } from './types.js';

export type { HxIconButtonProps };

/**
 * An icon-only button component for compact, accessible actions.
Renders a square button or anchor element containing a single icon.
The `label` property is required and provides the accessible name via
`aria-label`, announced exactly once — the focusable element carries no
`title` attribute (an identical `title` becomes the accessible
description and double-announces in NVDA). The native hover tooltip is
preserved via an internal aria-hidden carrier that holds `title`.
 *
 * @example
 * ```tsx
 * import { HxIconButton } from '@helixui/react';
 *
 * <HxIconButton />
 * ```
 */
export const HxIconButton = createComponent({
  tagName: 'hx-icon-button',
  elementClass: HelixIconButton,
  react: React,
  events: {
    onHxClick: 'hx-click',
  },
  displayName: 'HxIconButton',
});

export default HxIconButton;
