/**
 * TypeScript types for HxIconButton React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxIconButtonProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Accessible name for the button. Required. Rendered as `aria-label` and
`title` on the underlying element. The component renders nothing when absent,
and a console warning is emitted to alert developers during authoring. */
  label?: string;
  /** Visual style variant of the button. */
  variant?: 'primary' | 'secondary' | 'tertiary' | 'danger' | 'ghost';
  /** Size of the button. */
  size?: 'sm' | 'md' | 'lg';
  /** The type attribute for the underlying button element.
Has no effect when `href` is set. */
  type?: 'button' | 'submit' | 'reset';
  /** Whether the button is disabled. */
  disabled?: boolean;
  /** When set, renders an `<a>` element instead of a `<button>`. */
  href?: string | undefined;
  /** Name submitted with form data. Only applicable when rendering as a button. */
  name?: string | undefined;
  /** Value submitted with form data. Only applicable when rendering as a button. */
  value?: string | undefined;
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;

  // Event callbacks
  /** Dispatched when the button is clicked (not disabled). */
  onHxClick?: (event: Event) => void;
}
