/**
 * Angular wrapper generator.
 *
 * Generates Angular standalone components that host the web component
 * and bridge @Input() properties and @Output() event emitters.
 *
 * Output structure per component:
 *   <outDir>/src/lib/<component-name>/
 *     <component-name>.component.ts
 *     index.ts
 *   <outDir>/src/public-api.ts
 *   <outDir>/src/index.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { CemDeclaration, CemEvent, CemProperty, ComponentEntry } from '../types.js';
import {
  escapeJsDoc,
  getPublicProperties,
  sanitizeType,
  toCamelCase,
  toPascalCase,
} from '../utils.js';

/**
 * Converts an hx-event-name to Angular @Output() property name.
 * e.g. hx-click -> hxClick
 */
function toOutputPropertyName(eventName: string): string {
  return toCamelCase(eventName);
}

function generateComponentFile(
  decl: CemDeclaration,
  componentName: string,
  componentDir: string,
  properties: CemProperty[],
  events: CemEvent[],
): string {
  const tagName = decl.tagName!;
  const kebabName = tagName; // e.g. hx-button

  // @Input() declarations
  const inputLines = properties.map((prop) => {
    const safeDesc = escapeJsDoc(prop.description ?? prop.name);
    const typeStr = sanitizeType(prop.type?.text);
    return `  /** ${safeDesc} */\n  @Input() ${prop.name}?: ${typeStr};`;
  });

  // @Output() declarations
  const outputLines = events.map((e) => {
    const propName = toOutputPropertyName(e.name);
    const desc = escapeJsDoc(e.description ?? `Event: ${e.name}`);
    return `  /** ${desc} */\n  @Output() ${propName} = new EventEmitter<Event>();`;
  });

  // Host event bindings
  const hostBindings = events.map((e) => {
    const propName = toOutputPropertyName(e.name);
    const hostEventName = `(${e.name})`;
    return `  '${hostEventName}': '${propName}.emit($event)'`;
  });

  const hasInputs = inputLines.length > 0;
  const hasOutputs = outputLines.length > 0;
  const hasHostBindings = hostBindings.length > 0;

  const inputBlock = hasInputs ? inputLines.join('\n') + '\n\n' : '';
  const outputBlock = hasOutputs ? outputLines.join('\n') + '\n' : '';
  const hostBlock = hasHostBindings
    ? `\n  host: {\n${hostBindings.map((b) => `    ${b},`).join('\n')}\n  },`
    : '';

  return `/**
 * Angular wrapper for <${tagName}> web component.
 * Auto-generated by @helixui/wrapper-gen — DO NOT EDIT MANUALLY.
 * Re-run: pnpm run generate
 */

import { Component, Input, Output, EventEmitter, OnInit, inject, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { DOCUMENT } from '@angular/common';

/**
 * ${decl.description ?? `${componentName} web component wrapper for Angular.`}
 *
 * @example
 * \`\`\`html
 * <${kebabName} variant="primary" (hxClick)="handleClick($event)"></${kebabName}>
 * \`\`\`
 */
@Component({
  selector: '${kebabName}',
  template: '<ng-content />',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],${hostBlock}
})
export class ${componentName}Component implements OnInit {
  private readonly document = inject(DOCUMENT);

${inputBlock}${outputBlock}
  ngOnInit(): void {
    // Ensure the web component is registered
    import('@helixui/library/components/${componentDir}').catch(() => undefined);
  }
}
`;
}

/**
 * Converts PascalCase to kebab-case for file naming.
 * e.g. HxButton -> hx-button
 */
function toKebabCase(pascalCase: string): string {
  return pascalCase.replace(/([A-Z])/g, (match, char: string, offset: number) =>
    offset > 0 ? `-${char.toLowerCase()}` : char.toLowerCase(),
  );
}

function generatePublicApi(componentNames: string[]): string {
  return (
    [...componentNames]
      .sort()
      .map((name) => {
        const kebab = toKebabCase(name);
        return `export { ${name}Component } from './lib/${kebab}/index.js';`;
      })
      .join('\n') + '\n'
  );
}

function generateRootIndex(): string {
  return `export * from './public-api.js';\n`;
}

export function generateAngular(components: ComponentEntry[], outDir: string): void {
  const libDir = resolve(outDir, 'src', 'lib');
  mkdirSync(libDir, { recursive: true });

  const sorted = [...components].sort((a, b) =>
    (a.decl.tagName ?? '').localeCompare(b.decl.tagName ?? ''),
  );

  const componentNames: string[] = [];

  for (const { decl, modulePath } of sorted) {
    const tagName = decl.tagName!;
    const componentName = toPascalCase(tagName);
    const componentDir = modulePath.split('/')[2] ?? tagName;
    const properties = getPublicProperties(decl);
    const events = decl.events ?? [];
    const kebabName = toKebabCase(componentName);

    const componentLibDir = resolve(libDir, kebabName);
    mkdirSync(componentLibDir, { recursive: true });

    writeFileSync(
      resolve(componentLibDir, `${kebabName}.component.ts`),
      generateComponentFile(decl, componentName, componentDir, properties, events),
    );

    writeFileSync(
      resolve(componentLibDir, 'index.ts'),
      `export { ${componentName}Component } from './${kebabName}.component.js';\n`,
    );

    componentNames.push(componentName);
  }

  const srcDir = resolve(outDir, 'src');
  writeFileSync(resolve(srcDir, 'public-api.ts'), generatePublicApi(componentNames));
  writeFileSync(resolve(srcDir, 'index.ts'), generateRootIndex());

  console.log(`  Angular: generated ${sorted.length} components → ${outDir}`);
}
