/**
 * React wrapper generator.
 *
 * Generates @lit/react createComponent() wrappers with TypeScript types
 * for each custom element in the CEM.
 *
 * Output structure per component:
 *   <outDir>/components/<ComponentName>/
 *     <ComponentName>.ts  — createComponent() wrapper
 *     types.ts            — TypeScript prop interface
 *     index.ts            — re-export barrel
 *   <outDir>/index.ts     — root barrel exporting all components
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { CemDeclaration, CemEvent, CemProperty, ComponentEntry } from '../types.js';
import {
  escapeJsDoc,
  getComponentDir,
  getPublicProperties,
  sanitizeType,
  toCamelCase,
  toEventCallbackName,
  toPascalCase,
} from '../utils.js';

function generateTypesFile(
  componentName: string,
  properties: CemProperty[],
  events: CemEvent[],
): string {
  const propLines: string[] = [];

  propLines.push('  /** Slot content (children) */');
  propLines.push('  children?: React.ReactNode;');
  propLines.push('  /** CSS class name */');
  propLines.push('  className?: string;');
  propLines.push('  /** Inline styles */');
  propLines.push('  style?: React.CSSProperties;');

  for (const prop of properties) {
    const safeDesc = escapeJsDoc(prop.description ?? '');
    const comment = safeDesc ? `  /** ${safeDesc} */\n` : '';
    const typeStr = sanitizeType(prop.type?.text);
    propLines.push(`${comment}  ${prop.name}?: ${typeStr};`);
  }

  if (events.length > 0) {
    propLines.push('');
    propLines.push('  // Event callbacks');
    for (const e of events) {
      const callbackName = toEventCallbackName(e.name);
      const desc = e.description ?? `Event: ${e.name}`;
      propLines.push(`  /** ${escapeJsDoc(desc)} */`);
      propLines.push(`  ${callbackName}?: (event: Event) => void;`);
    }
  }

  return `/**
 * TypeScript types for ${componentName} React wrapper.
 * Auto-generated by @helixui/wrapper-gen — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface ${componentName}Props {
${propLines.join('\n')}
}
`;
}

function generateComponentFile(
  decl: CemDeclaration,
  componentName: string,
  componentDir: string,
  events: CemEvent[],
): string {
  const tagName = decl.tagName!;
  const elementClassName = decl.name;
  const elementImportPath = `@helixui/library/components/${componentDir}`;

  const hasNameCollision = elementClassName === componentName;
  const importAlias = hasNameCollision ? `${elementClassName}Element` : elementClassName;
  const importStatement = hasNameCollision
    ? `import { ${elementClassName} as ${importAlias} } from '${elementImportPath}';`
    : `import { ${elementClassName} } from '${elementImportPath}';`;

  const eventMapEntries = events
    .map((e) => {
      const callbackName = toEventCallbackName(e.name);
      return `    ${callbackName}: '${e.name}'`;
    })
    .join(',\n');

  const eventMap = events.length > 0 ? `{\n${eventMapEntries}\n  }` : '{}';

  return `'use client';
/**
 * React wrapper for <${tagName}> web component.
 * Auto-generated by @helixui/wrapper-gen — DO NOT EDIT MANUALLY.
 * Re-run: pnpm run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
${importStatement}

import type { ${componentName}Props } from './types.js';

export type { ${componentName}Props };

/**
 * ${decl.description ?? `${componentName} web component wrapper for React.`}
 *
 * @example
 * \`\`\`tsx
 * import { ${componentName} } from '@helixui/react';
 *
 * <${componentName} />
 * \`\`\`
 */
export const ${componentName} = createComponent({
  tagName: '${tagName}',
  elementClass: ${importAlias},
  react: React,
  events: ${eventMap},
  displayName: '${componentName}',
});

export default ${componentName};
`;
}

function generateComponentIndex(componentName: string): string {
  return `export { ${componentName}, default } from './${componentName}.js';
export type { ${componentName}Props } from './types.js';
`;
}

function generateRootIndex(componentNames: string[]): string {
  return (
    [...componentNames]
      .sort()
      .map((name) => `export { ${name}, type ${name}Props } from './components/${name}/index.js';`)
      .join('\n') + '\n'
  );
}

export function generateReact(components: ComponentEntry[], outDir: string): void {
  const componentsDir = resolve(outDir, 'src', 'components');
  mkdirSync(componentsDir, { recursive: true });

  // Sort components deterministically by tag name
  const sorted = [...components].sort((a, b) =>
    (a.decl.tagName ?? '').localeCompare(b.decl.tagName ?? ''),
  );

  const componentNames: string[] = [];

  for (const { decl, modulePath } of sorted) {
    const tagName = decl.tagName!;
    const componentName = toPascalCase(tagName);
    const componentDir = getComponentDir(modulePath);
    const properties = getPublicProperties(decl);
    const events = decl.events ?? [];

    const componentOutDir = resolve(componentsDir, componentName);
    mkdirSync(componentOutDir, { recursive: true });

    writeFileSync(
      resolve(componentOutDir, 'types.ts'),
      generateTypesFile(componentName, properties, events),
    );

    writeFileSync(
      resolve(componentOutDir, `${componentName}.ts`),
      generateComponentFile(decl, componentName, componentDir, events),
    );

    writeFileSync(resolve(componentOutDir, 'index.ts'), generateComponentIndex(componentName));

    componentNames.push(componentName);
  }

  const srcDir = resolve(outDir, 'src');
  mkdirSync(srcDir, { recursive: true });
  writeFileSync(resolve(srcDir, 'index.ts'), generateRootIndex(componentNames));

  console.log(`  React: generated ${sorted.length} components → ${outDir}`);
}

// Named export used to map event names -> camelCase for Vue/Svelte too
export { toCamelCase };
