/**
 * Svelte wrapper generator.
 *
 * Generates Svelte 4/5 action helpers that attach web component properties
 * to DOM elements with TypeScript type support.
 *
 * Output structure:
 *   <outDir>/src/actions/<tag-name>.ts  — action helper per component
 *   <outDir>/src/types/<tag-name>.ts    — TypeScript prop interface
 *   <outDir>/src/index.ts               — root barrel
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { CemDeclaration, CemEvent, CemProperty, ComponentEntry } from '../types.js';
import {
  escapeJsDoc,
  getComponentDir,
  getPublicProperties,
  sanitizeType,
  toCamelCase,
  toPascalCase,
} from '../utils.js';

function generateTypesFile(
  componentName: string,
  tagName: string,
  properties: CemProperty[],
  events: CemEvent[],
): string {
  const propLines = properties.map((prop) => {
    const safeDesc = escapeJsDoc(prop.description ?? prop.name);
    const typeStr = sanitizeType(prop.type?.text);
    return `  /** ${safeDesc} */\n  ${prop.name}?: ${typeStr};`;
  });

  const eventLines = events.map((e) => {
    const desc = escapeJsDoc(e.description ?? `Event: ${e.name}`);
    return `  /** ${desc} */\n  'on:${e.name}'?: (event: Event) => void;`;
  });

  const allLines = [
    ...propLines,
    ...(eventLines.length > 0 ? ['', '  // Event handlers', ...eventLines] : []),
  ];

  return `/**
 * TypeScript types for <${tagName}> web component in Svelte.
 * Auto-generated by @helixui/wrapper-gen — DO NOT EDIT MANUALLY.
 */

export interface ${componentName}Props {
${allLines.join('\n')}
}
`;
}

function generateActionFile(
  decl: CemDeclaration,
  componentName: string,
  componentDir: string,
  properties: CemProperty[],
  events: CemEvent[],
): string {
  const tagName = decl.tagName!;

  // Generate property setter lines
  const propSetters = properties.map((prop) => {
    const typeStr = sanitizeType(prop.type?.text);
    return `    if (props.${prop.name} !== undefined) (node as unknown as Record<string, ${typeStr}>)['${prop.name}'] = props.${prop.name};`;
  });

  // Generate event listener attach/detach
  const eventAttachLines = events.map((e) => {
    const handlerVar = `_handler_${toCamelCase(e.name)}`;
    return `  const ${handlerVar} = props['on:${e.name}'];
  if (${handlerVar}) node.addEventListener('${e.name}', ${handlerVar});`;
  });

  const eventDetachLines = events.map((e) => {
    const handlerVar = `_handler_${toCamelCase(e.name)}`;
    return `    if (${handlerVar}) node.removeEventListener('${e.name}', ${handlerVar});`;
  });

  const hasProps = properties.length > 0;
  const hasEvents = events.length > 0;

  const attachBlock = [
    ...(hasProps
      ? [
          `  const _applyProps = (props: ${componentName}Props) => {`,
          ...propSetters.map((l) => '  ' + l),
          '  };',
          '  _applyProps(props ?? {});',
        ]
      : []),
    ...(hasEvents ? eventAttachLines : []),
  ].join('\n');

  const destroyBlock = [...(hasEvents ? eventDetachLines : [])].join('\n');

  const updateBlock = hasProps
    ? [
        `  _applyProps(newProps ?? {});`,
        ...(hasEvents
          ? ['  // Note: event handlers are not updated after mount — pass stable references']
          : []),
      ].join('\n')
    : hasEvents
      ? '  // Note: event handlers are not updated after mount — pass stable references'
      : '';

  return `/**
 * Svelte action helper for <${tagName}> web component.
 * Auto-generated by @helixui/wrapper-gen — DO NOT EDIT MANUALLY.
 * Re-run: pnpm run generate
 *
 * @example
 * \`\`\`svelte
 * <script>
 *   import { ${toCamelCase(tagName)} } from '@helixui/svelte';
 * </script>
 *
 * <${tagName} use:${toCamelCase(tagName)}={{ variant: 'primary' }} />
 * \`\`\`
 */

import '@helixui/library/components/${componentDir}';
import type { ${componentName}Props } from '../types/${tagName}.js';

export type { ${componentName}Props };

export function ${toCamelCase(tagName)}(
  node: HTMLElement,
  props?: ${componentName}Props,
): { update(newProps?: ${componentName}Props): void; destroy(): void } {
${attachBlock}

  return {
    update(newProps?: ${componentName}Props) {
${updateBlock}
    },
    destroy() {
${destroyBlock}
    },
  };
}
`;
}

function generateRootIndex(components: ComponentEntry[]): string {
  const sorted = [...components].sort((a, b) =>
    (a.decl.tagName ?? '').localeCompare(b.decl.tagName ?? ''),
  );

  const actionExports = sorted
    .map(({ decl }) => {
      const tagName = decl.tagName!;
      const actionName = toCamelCase(tagName);
      const componentName = toPascalCase(tagName);
      return `export { ${actionName}, type ${componentName}Props } from './actions/${tagName}.js';`;
    })
    .join('\n');

  return actionExports + '\n';
}

export function generateSvelte(components: ComponentEntry[], outDir: string): void {
  const actionsDir = resolve(outDir, 'src', 'actions');
  const typesDir = resolve(outDir, 'src', 'types');
  mkdirSync(actionsDir, { recursive: true });
  mkdirSync(typesDir, { recursive: true });

  const sorted = [...components].sort((a, b) =>
    (a.decl.tagName ?? '').localeCompare(b.decl.tagName ?? ''),
  );

  for (const { decl, modulePath } of sorted) {
    const tagName = decl.tagName!;
    const componentName = toPascalCase(tagName);
    const componentDir = getComponentDir(modulePath);
    const properties = getPublicProperties(decl);
    const events = decl.events ?? [];

    writeFileSync(
      resolve(typesDir, `${tagName}.ts`),
      generateTypesFile(componentName, tagName, properties, events),
    );

    writeFileSync(
      resolve(actionsDir, `${tagName}.ts`),
      generateActionFile(decl, componentName, componentDir, properties, events),
    );
  }

  const srcDir = resolve(outDir, 'src');
  writeFileSync(resolve(srcDir, 'index.ts'), generateRootIndex(sorted));

  console.log(`  Svelte: generated ${sorted.length} components → ${outDir}`);
}
