/**
 * Vue wrapper generator.
 *
 * Generates Vue 3 defineComponent wrappers that bridge web component
 * properties and events to Vue's reactivity and event system.
 *
 * Output structure per component:
 *   <outDir>/src/components/HxButton.ts
 *   <outDir>/src/index.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { CemDeclaration, CemEvent, CemProperty, ComponentEntry } from '../types.js';
import {
  escapeJsDoc,
  getComponentDir,
  getPublicProperties,
  sanitizeType,
  toCamelCase,
  toPascalCase,
} from '../utils.js';

/**
 * Maps a CEM type string to a Vue PropType constructor string.
 * Returns the TypeScript type string for inline type assertion.
 */
function toVuePropType(typeText: string | undefined): string {
  const safe = sanitizeType(typeText);

  // Boolean shorthand
  if (safe === 'boolean') return 'Boolean';
  if (safe === 'number') return 'Number';
  if (safe === 'string') return 'String';

  // Union or complex type — use PropType<T> for full type safety
  return `String as PropType<${safe}>`;
}

function generateComponentFile(
  decl: CemDeclaration,
  componentName: string,
  componentDir: string,
  properties: CemProperty[],
  events: CemEvent[],
): string {
  const tagName = decl.tagName!;

  // Build props object entries
  const propEntries = properties
    .map((prop) => {
      const safeDesc = escapeJsDoc(prop.description ?? prop.name);
      const propType = toVuePropType(prop.type?.text);
      return `    /** ${safeDesc} */\n    ${prop.name}: { type: ${propType}, required: false },`;
    })
    .join('\n');

  // Build emits object
  const emitEntries = events
    .map((e) => {
      const desc = escapeJsDoc(e.description ?? `Event: ${e.name}`);
      return `    /** ${desc} */\n    '${e.name}': (_event: Event) => true,`;
    })
    .join('\n');

  // Build event listener bindings in setup
  const eventBindings = events
    .map((e) => {
      const camelName = toCamelCase(e.name);
      const onName = 'on' + camelName.charAt(0).toUpperCase() + camelName.slice(1);
      return `      '${onName}': (e: Event) => emit('${e.name}', e),`;
    })
    .join('\n');

  const hasProps = properties.length > 0;
  const hasEvents = events.length > 0;
  const needsPropType = properties.some((p) => {
    const safe = sanitizeType(p.type?.text);
    return safe !== 'boolean' && safe !== 'number' && safe !== 'string';
  });

  const propTypeImport = needsPropType ? ', type PropType' : '';
  const propsBlock = hasProps ? `  props: {\n${propEntries}\n  },\n` : '';
  const emitsBlock = hasEvents ? `  emits: {\n${emitEntries}\n  },\n` : '';

  const setupEventSpread = hasEvents
    ? `\n      // DOM event listeners forwarded to Vue emits\n${eventBindings}`
    : '';

  const propsSpread = hasProps ? '\n      ...props,' : '';

  return `/**
 * Vue 3 wrapper for <${tagName}> web component.
 * Auto-generated by @helixui/wrapper-gen — DO NOT EDIT MANUALLY.
 * Re-run: pnpm run generate
 */

import { defineComponent, h${propTypeImport} } from 'vue';
import '@helixui/library/components/${componentDir}';

/**
 * ${decl.description ?? `${componentName} web component wrapper for Vue 3.`}
 *
 * @example
 * \`\`\`vue
 * <script setup>
 * import { ${componentName} } from '@helixui/vue';
 * </script>
 *
 * <template>
 *   <${componentName} />
 * </template>
 * \`\`\`
 */
export const ${componentName} = defineComponent({
  name: '${componentName}',
${propsBlock}${emitsBlock}  setup(props, { slots, emit }) {
    return () =>
      h(
        '${tagName}',
        {${propsSpread}${setupEventSpread}
        },
        slots,
      );
  },
});

export default ${componentName};
`;
}

function generateRootIndex(componentNames: string[]): string {
  return (
    [...componentNames]
      .sort()
      .map(
        (name) => `export { ${name}, default as ${name}Default } from './components/${name}.js';`,
      )
      .join('\n') + '\n'
  );
}

export function generateVue(components: ComponentEntry[], outDir: string): void {
  const componentsDir = resolve(outDir, 'src', 'components');
  mkdirSync(componentsDir, { recursive: true });

  const sorted = [...components].sort((a, b) =>
    (a.decl.tagName ?? '').localeCompare(b.decl.tagName ?? ''),
  );

  const componentNames: string[] = [];

  for (const { decl, modulePath } of sorted) {
    const tagName = decl.tagName!;
    const componentName = toPascalCase(tagName);
    const componentDir = getComponentDir(modulePath);
    const properties = getPublicProperties(decl);
    const events = decl.events ?? [];

    writeFileSync(
      resolve(componentsDir, `${componentName}.ts`),
      generateComponentFile(decl, componentName, componentDir, properties, events),
    );

    componentNames.push(componentName);
  }

  const srcDir = resolve(outDir, 'src');
  writeFileSync(resolve(srcDir, 'index.ts'), generateRootIndex(componentNames));

  console.log(`  Vue: generated ${sorted.length} components → ${outDir}`);
}
