'use client';
/**
 * React wrapper for <hx-toast> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixToast } from '@helixui/library/components/hx-toast';

import type { HxToastProps } from './types.js';

export type { HxToastProps };

/**
 * A transient notification message that auto-dismisses after a configurable duration.
Supports multiple visual variants, a closable button, icon/action slots, and full
ARIA live region semantics for screen readers.
 *
 * @example
 * ```tsx
 * import { HxToast } from '@helixui/react';
 *
 * <HxToast />
 * ```
 */
export const HxToast = createComponent({
  tagName: 'hx-toast',
  elementClass: HelixToast,
  react: React,
  events: {
    onHxShow: 'hx-show',
    onHxHide: 'hx-hide',
    onHxAfterHide: 'hx-after-hide',
  },
  displayName: 'HxToast',
});

export default HxToast;
