/**
 * TypeScript types for HxToast React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxToastProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Visual style variant. */
  variant?: string;
  /** Auto-dismiss duration in milliseconds. Set to 0 for persistent toasts. */
  duration?: number;
  /** Whether to show a close button. */
  closable?: boolean;
  /** Whether the toast is currently visible. */
  open?: boolean;
  /** Accessible label for the close button. Override for localization. */
  closeLabel?: string;

  // Event callbacks
  /** Dispatched when the toast becomes visible. */
  onHxShow?: (event: Event) => void;
  /** Dispatched when the toast begins hiding. */
  onHxHide?: (event: Event) => void;
  /** Dispatched after the hide animation completes. */
  onHxAfterHide?: (event: Event) => void;
}
