'use client';
/**
 * React wrapper for <hx-tr> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTableRow } from '@helixui/library/components/hx-table';

import type { HxTrProps } from './types.js';

export type { HxTrProps };

/**
 * Semantic table row. Must be a child of `hx-thead`, `hx-tbody`, or `hx-tfoot`.
Contains `hx-th` or `hx-td` cells.
 *
 * @example
 * ```tsx
 * import { HxTr } from '@helixui/react';
 *
 * <HxTr />
 * ```
 */
export const HxTr = createComponent({
  tagName: 'hx-tr',
  elementClass: HelixTableRow,
  react: React,
  events: {},
  displayName: 'HxTr',
});

export default HxTr;
