'use client';
/**
 * React wrapper for <hx-tr> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTableRow } from '@helixui/library/components/hx-table';

import type { HxTrProps } from './types.js';

export type { HxTrProps };

/**
 * Semantic table row. Must be a child of `hx-thead`, `hx-tbody`, or `hx-tfoot`.
Contains `hx-th` or `hx-td` cells.

Group 7 host-canonical: `role="row"` lives on the **host** via
`_internals.role`. The host carries `aria-selected` / `aria-disabled`
mirroring `selected` / `disabled` reflected attributes. Consumer-supplied
`aria-label` / `aria-labelledby` on the host project to the host's
announced surface so AT walks `<hx-tr>` (role=row) directly. Fallback
path keeps the inner `<tr role="row">` as the announced surface for
engines without IDL element references.
 *
 * @example
 * ```tsx
 * import { HxTr } from '@helixui/react';
 *
 * <HxTr />
 * ```
 */
export const HxTr = createComponent({
  tagName: 'hx-tr',
  elementClass: HelixTableRow,
  react: React,
  events: {},
  displayName: 'HxTr',
});

export default HxTr;
