/**
 * TypeScript types for HxTr React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTrProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** When true, marks the row as selected and applies selected styling. */
  selected?: boolean;
  /** When true, the row is visually disabled and non-interactive. */
  disabled?: boolean;
}
