'use client';
/**
 * React wrapper for <hx-steps> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixSteps } from '@helixui/library/components/hx-steps';

import type { HxStepsProps } from './types.js';

export type { HxStepsProps };

/**
 * A multi-step wizard / stepper progress indicator. Renders a sequence of
`<hx-step>` children as a horizontal or vertical step tracker with connector
lines and status-based styling.

Provide an `aria-label` on `<hx-steps>` to describe the step process for assistive technology.
 *
 * @example
 * ```tsx
 * import { HxSteps } from '@helixui/react';
 *
 * <HxSteps />
 * ```
 */
export const HxSteps = createComponent({
  tagName: 'hx-steps',
  elementClass: HelixSteps,
  react: React,
  events: {
    onHxStepClick: 'hx-step-click'
  },
  displayName: 'HxSteps',
});

export default HxSteps;
