'use client';
/**
 * React wrapper for <hx-tree-item> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTreeItem } from '@helixui/library/components/hx-tree-view';

import type { HxTreeItemProps } from './types.js';

export type { HxTreeItemProps };

/**
 * A tree item used within an hx-tree-view component.
Supports expand/collapse, selection, keyboard navigation, and icon/children slots.
 *
 * @example
 * ```tsx
 * import { HxTreeItem } from '@helixui/react';
 *
 * <HxTreeItem />
 * ```
 */
export const HxTreeItem = createComponent({
  tagName: 'hx-tree-item',
  elementClass: HelixTreeItem,
  react: React,
  events: {
    onHxTreeItemSelect: 'hx-tree-item-select',
  },
  displayName: 'HxTreeItem',
});

export default HxTreeItem;
