/**
 * TypeScript types for HxTreeItem React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTreeItemProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Whether the item is expanded (showing children). */
  expanded?: boolean;
  /** Whether the item is selected. */
  selected?: boolean;
  /** Whether the item is disabled (non-interactive). */
  disabled?: boolean;
  /** Whether this item has slotted children. */
  hasChildItems?: boolean;

  // Event callbacks
  /** Dispatched when this item is clicked or activated via keyboard. */
  onHxTreeItemSelect?: (event: Event) => void;
}
