'use client';
/**
 * React wrapper for <hx-number-input> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixNumberInput } from '@helixui/library/components/hx-number-input';

import type { HxNumberInputProps } from './types.js';

export type { HxNumberInputProps };

/**
 * A numeric input component with stepper controls, label, validation, and
full form association. Designed for healthcare data-entry contexts where
precise numeric values (dosage, age, measurements) must be captured safely.
 *
 * @example
 * ```tsx
 * import { HxNumberInput } from '@helixui/react';
 *
 * <HxNumberInput />
 * ```
 */
export const HxNumberInput = createComponent({
  tagName: 'hx-number-input',
  elementClass: HelixNumberInput,
  react: React,
  events: {
    onHxChange: 'hx-change',
    onHxInput: 'hx-input',
  },
  displayName: 'HxNumberInput',
});

export default HxNumberInput;
