/**
 * TypeScript types for HxNumberInput React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxNumberInputProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The name of the input, used for form submission. */
  name?: string;
  /** The current numeric value of the input. Null when the field is empty. */
  value?: number | null;
  /** Whether the input is required for form submission. */
  required?: boolean;
  /** Whether the input is disabled. */
  disabled?: boolean;
  /** Whether the input is read-only. */
  readonly?: boolean;
  /** Minimum allowed value. When reached, the decrement button is disabled. */
  min?: number | undefined;
  /** Maximum allowed value. When reached, the increment button is disabled. */
  max?: number | undefined;
  /** The amount to increment or decrement on each step action. */
  step?: number;
  /** The visible label text for the input. */
  label?: string;
  /** Error message to display. When set, the input enters an error state. */
  error?: string;
  /** Help text displayed below the input for guidance. */
  helpText?: string;
  /** Size variant controlling input padding and font size. */
  size?: 'sm' | 'md' | 'lg';
  /** When set, hides the +/- stepper buttons. */
  noStepper?: boolean;
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched when the input loses focus after its value changed. */
  onHxChange?: (event: Event) => void;
  /** Dispatched on every keystroke as the user types. */
  onHxInput?: (event: Event) => void;
}
