/**
 * Auto-registration for the bundled `helix` icon library.
 *
 * Importing this module registers the `helix` library with the registry.
 * No exports — this is a pure side-effect module. The companion sprite
 * sheet ships in `dist/helix.svg` (generated by `scripts/generate-sprite.ts`).
 *
 * The library is registered with `paintMode: 'fill'` because every helix
 * glyph is a solid silhouette rendered with `fill="currentColor"`. Phase 4's
 * `<hx-icon>` AAA contrast harness will skip stroke-width measurement for
 * fill libraries.
 */

import { getBasePath, registerIconLibrary } from '../registry.js';

registerIconLibrary('helix', {
  resolver: (name) => `${getBasePath()}/helix.svg#${name}`,
  spriteSheet: true,
  paintMode: 'fill',
});
