'use client';
/**
 * React wrapper for <hx-time-picker> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTimePicker } from '@helixui/library/components/hx-time-picker';

import type { HxTimePickerProps } from './types.js';

export type { HxTimePickerProps };

/**
 * A time-picker component with a combobox pattern: a text input with format
masking and a dropdown listbox of pre-generated time slots.
 *
 * @example
 * ```tsx
 * import { HxTimePicker } from '@helixui/react';
 *
 * <HxTimePicker />
 * ```
 */
export const HxTimePicker = createComponent({
  tagName: 'hx-time-picker',
  elementClass: HelixTimePicker,
  react: React,
  events: {
    onHxChange: 'hx-change',
  },
  displayName: 'HxTimePicker',
});

export default HxTimePicker;
