/**
 * TypeScript types for HxTimePicker React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTimePickerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** The name submitted with the form. Value is always HH:MM (24-hour). */
  name?: string;
  /** The current value in HH:MM (24-hour) format. */
  value?: string;
  /** The earliest selectable time in HH:MM format. */
  min?: string;
  /** The latest selectable time in HH:MM format. */
  max?: string;
  /** Step interval between dropdown options, in minutes. Defaults to 30. */
  step?: number;
  /** The visible label text for the field. */
  label?: string;
  /** Whether the field is required for form submission. */
  required?: boolean;
  /** Whether the field is disabled. */
  disabled?: boolean;
  /** Error message to display. When set, the field enters an error state. */
  error?: string;
  /** Display format for the time input. '12h' shows AM/PM; '24h' is bare HH:MM. */
  format?: '12h' | '24h';
  /** Returns the associated form element, if any. */
  form?: HTMLFormElement | null;
  /** Returns the validation message. */
  validationMessage?: string;
  /** Returns the ValidityState object. */
  validity?: ValidityState;

  // Event callbacks
  /** Dispatched when the selected time changes. Detail value is HH:MM (24h). */
  onHxChange?: (event: Event) => void;
}
