'use client';
/**
 * React wrapper for <hx-dialog> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixDialog } from '@helixui/library/components/hx-dialog';

import type { HxDialogProps } from './types.js';

export type { HxDialogProps };

/**
 * A modal and non-modal dialog component built on the native HTML `<dialog>` element.
Provides focus trapping, backdrop interaction, keyboard navigation, and full
ARIA labelling for enterprise healthcare accessibility requirements.
 *
 * @example
 * ```tsx
 * import { HxDialog } from '@helixui/react';
 *
 * <HxDialog />
 * ```
 */
export const HxDialog = createComponent({
  tagName: 'hx-dialog',
  elementClass: HelixDialog,
  react: React,
  events: {
    onHxOpen: 'hx-open',
    onHxClose: 'hx-close',
    onHxCancel: 'hx-cancel',
  },
  displayName: 'HxDialog',
});

export default HxDialog;
