/**
 * TypeScript types for HxDialog React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxDialogProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Controls whether the dialog is open. */
  open?: boolean;
  /** When true, renders as a modal dialog with a backdrop and focus trap.
When false, renders as a non-modal dialog. */
  modal?: boolean;
  /** When true, clicking the backdrop closes the dialog. */
  closeOnBackdrop?: boolean;
  /** Text content for the dialog heading. Used as the accessible label via aria-labelledby. */
  heading?: string;
  /** ARIA role variant. Use `'alertdialog'` for urgent dialogs requiring immediate attention
(e.g., drug interaction warnings, critical lab alerts). Defaults to `'dialog'`. */
  variant?: 'dialog' | 'alertdialog';
  /** Optional description text linked to the dialog via `aria-describedby`.
When provided, screen readers will announce this text when the dialog receives focus.
Recommended for dialogs that surface critical clinical information. */
  description?: string;
  /** Accessible label for the close button. Override for localized text. */
  closeLabel?: string;
  /** Returns the dialog's return value — the string passed to `close(returnValue)`.
Mirrors `HTMLDialogElement.returnValue`. */
  returnValue?: string;

  // Event callbacks
  /** Fired when the dialog opens. */
  onHxOpen?: (event: Event) => void;
  /** Fired when the dialog closes for any reason. */
  onHxClose?: (event: Event) => void;
  /** Fired when the dialog is dismissed via Escape key or cancel action. */
  onHxCancel?: (event: Event) => void;
}
