'use client';
/**
 * React wrapper for <hx-td> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixTableCell } from '@helixui/library/components/hx-table';

import type { HxTdProps } from './types.js';

export type { HxTdProps };

/**
 * Semantic table data cell. Must be a child of `hx-tr`.

Group 7 host-canonical: `role="cell"` lives on the **host** via
`_internals.role`. The host carries the cell's accessible name (resolved
from the `label` property — fixing audit B-A1, where mobile screen reader
users lost column context because `data-label` was visual-only).
 *
 * @example
 * ```tsx
 * import { HxTd } from '@helixui/react';
 *
 * <HxTd />
 * ```
 */
export const HxTd = createComponent({
  tagName: 'hx-td',
  elementClass: HelixTableCell,
  react: React,
  events: {},
  displayName: 'HxTd',
});

export default HxTd;
