/**
 * TypeScript types for HxTd React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxTdProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Horizontal alignment for cell content. */
  align?: 'left' | 'center' | 'right';
  /** Number of columns this cell spans. */
  colspan?: number;
  /** Number of rows this cell spans. */
  rowspan?: number;
  /** Column header label for this cell. Forwarded as `data-label` on the native `<td>` for
the mobile card layout (`td::before { content: attr(data-label) }`) and as `aria-label`
so screen readers identify the column when the header row is hidden. */
  label?: string;
}
