'use client';
/**
 * React wrapper for <hx-divider> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixDivider } from '@helixui/library/components/hx-divider';

import type { HxDividerProps } from './types.js';

export type { HxDividerProps };

/**
 * A visual separator element for dividing content sections. Supports
horizontal and vertical orientations, configurable spacing, and an optional
centered label rendered between two lines.
 *
 * @example
 * ```tsx
 * import { HxDivider } from '@helixui/react';
 *
 * <HxDivider />
 * ```
 */
export const HxDivider = createComponent({
  tagName: 'hx-divider',
  elementClass: HelixDivider,
  react: React,
  events: {},
  displayName: 'HxDivider',
});

export default HxDivider;
