/**
 * TypeScript types for HxDivider React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxDividerProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Orientation of the divider. */
  orientation?: 'horizontal' | 'vertical';
  /** Spacing applied to the block axis (horizontal) or inline axis (vertical). */
  spacing?: 'none' | 'sm' | 'md' | 'lg';
  /** When true, renders the divider as decorative only (role="presentation").
Screen readers will not announce decorative dividers. */
  decorative?: boolean;
  /** Optional text label rendered centered between the divider lines.
Also sets aria-label on the separator for assistive technologies. */
  label?: string | undefined;
}
