'use client';
/**
 * React wrapper for <hx-accordion-item> web component.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 * Re-run: pnpm --filter=@helixui/react run generate
 */

import React from 'react';
import { createComponent } from '@lit/react';
import { HelixAccordionItem } from '@helixui/library/components/hx-accordion';

import type { HxAccordionItemProps } from './types.js';

export type { HxAccordionItemProps };

/**
 * An individual accordion item with collapsible content.
 *
 * @example
 * ```tsx
 * import { HxAccordionItem } from '@helixui/react';
 *
 * <HxAccordionItem />
 * ```
 */
export const HxAccordionItem = createComponent({
  tagName: 'hx-accordion-item',
  elementClass: HelixAccordionItem,
  react: React,
  events: {
    onHxExpand: 'hx-expand',
    onHxCollapse: 'hx-collapse',
  },
  displayName: 'HxAccordionItem',
});

export default HxAccordionItem;
