/**
 * TypeScript types for HxAccordionItem React wrapper.
 * Auto-generated by scripts/generate-react-wrappers.ts — DO NOT EDIT MANUALLY.
 */

import type React from 'react';

export interface HxAccordionItemProps {
  /** Slot content (children) */
  children?: React.ReactNode;
  /** CSS class name */
  className?: string;
  /** Inline styles */
  style?: React.CSSProperties;
  /** Whether this item is expanded. */
  expanded?: boolean;
  /** Whether this item is disabled (cannot be toggled). */
  disabled?: boolean;
  /** Heading level (1–6) applied via `role="heading" aria-level` on the summary
trigger. Defaults to 3. Set to match the document outline around the
accordion so screen readers surface accordion items in the heading list. */
  level?: string | string | string | string | string | string;

  // Event callbacks
  /** Dispatched when the item is expanded. */
  onHxExpand?: (event: Event) => void;
  /** Dispatched when the item is collapsed. */
  onHxCollapse?: (event: Event) => void;
}
